CardNamePointersEn:
	table_width 2
	dw BEyeWhiteDragonNameEn    ; B_EYE_WHITE_DRAGON
	dw MysticalElfNameEn        ; MYSTICAL_ELF
	dw HitotsuMeGiantNameEn     ; HITOTSU_ME_GIANT
	dw BabyDragonNameEn         ; BABY_DRAGON
	dw RyuKishinNameEn          ; RYU_KISHIN
	dw FeralImpNameEn           ; FERAL_IMP
	dw WingedDragon1NameEn      ; WINGED_DRAGON_1
	dw MushroomManNameEn        ; MUSHROOM_MAN
	dw ShadowSpecterNameEn      ; SHADOW_SPECTER
	dw BlacklandDragonNameEn    ; BLACKLAND_DRAGON
	dw SwordArmDragonNameEn     ; SWORD_ARM_DRAGON
	dw SwampBattleguardNameEn   ; SWAMP_BATTLEGUARD
	dw TyhoneNameEn             ; TYHONE
	dw BattleSteerNameEn        ; BATTLE_STEER
	dw FlameSwordsmanNameEn     ; FLAME_SWORDSMAN
	dw TimeWizardNameEn         ; TIME_WIZARD
	dw RLegOfForbiddenNameEn    ; R_LEG_OF_FORBIDDEN
	dw LLegOfForbiddenNameEn    ; L_LEG_OF_FORBIDDEN
	dw RArmOfForbiddenNameEn    ; R_ARM_OF_FORBIDDEN
	dw LArmOfForbiddenNameEn    ; L_ARM_OF_FORBIDDEN
	dw ExodiaForbiddenNameEn    ; EXODIA_FORBIDDEN
	dw SummonedSkullNameEn      ; SUMMONED_SKULL
	dw WickedWormBeastNameEn    ; WICKED_WORM_BEAST
	dw SkullServantNameEn       ; SKULL_SERVANT
	dw HornImpNameEn            ; HORN_IMP
	dw BattleOxNameEn           ; BATTLE_OX
	dw BeaverWarriorNameEn      ; BEAVER_WARRIOR
	dw RockOgreGrotto1NameEn    ; ROCK_OGRE_GROTTO1
	dw MountainWarriorNameEn    ; MOUNTAIN_WARRIOR
	dw ZombieWarriorNameEn      ; ZOMBIE_WARRIOR
	dw KoumoriDragonNameEn      ; KOUMORI_DRAGON
	dw TwoHeadedKingRexNameEn   ; TWO_HEADED_KING_REX
	dw JudgeManNameEn           ; JUDGE_MAN
	dw SaggiTheClownNameEn      ; SAGGI_THE_CLOWN
	dw DarkMagicianNameEn       ; DARK_MAGICIAN
	dw TheSnakeHairNameEn       ; THE_SNAKE_HAIR
	dw GaiaDragonChampNameEn    ; GAIA_DRAGON_CHAMP
	dw GaiaFierceKnightNameEn   ; GAIA_FIERCE_KNIGHT
	dw CurseOfDragonNameEn      ; CURSE_OF_DRAGON
	dw DragonPiperNameEn        ; DRAGON_PIPER
	dw CelticGuardianNameEn     ; CELTIC_GUARDIAN
	dw IllusionFacelessNameEn   ; ILLUSION_FACELESS
	dw KarbonalaWarriorNameEn   ; KARBONALA_WARRIOR
	dw RogueDollNameEn          ; ROGUE_DOLL
	dw WattkidNameEn            ; WATTKID
	dw GrifforeNameEn           ; GRIFFORE
	dw TorikeNameEn             ; TORIKE
	dw SanganNameEn             ; SANGAN
	dw BigInsectNameEn          ; BIG_INSECT
	dw BasicInsectNameEn        ; BASIC_INSECT
	dw ArmoredLizardNameEn      ; ARMORED_LIZARD
	dw HerculesBeetleNameEn     ; HERCULES_BEETLE
	dw KillerNeedleNameEn       ; KILLER_NEEDLE
	dw GokiboreNameEn           ; GOKIBORE
	dw GiantFleaNameEn          ; GIANT_FLEA
	dw LarvaeMothNameEn         ; LARVAE_MOTH
	dw GreatMothNameEn          ; GREAT_MOTH
	dw KuribohNameEn            ; KURIBOH
	dw MammothGraveyardNameEn   ; MAMMOTH_GRAVEYARD
	dw GreatWhiteNameEn         ; GREAT_WHITE
	dw WolfNameEn               ; WOLF
	dw HarpieLadyNameEn         ; HARPIE_LADY
	dw HarpieLadySisterNameEn   ; HARPIE_LADY_SISTER
	dw TigerAxeNameEn           ; TIGER_AXE
	dw SilverFangNameEn         ; SILVER_FANG
	dw KojikocyNameEn           ; KOJIKOCY
	dw PerfectGreatMothNameEn   ; PERFECT_GREAT_MOTH
	dw GaroozisNameEn           ; GAROOZIS
	dw ThousandDragonNameEn     ; THOUSAND_DRAGON
	dw FiendKrakenNameEn        ; FIEND_KRAKEN
	dw JellyfishNameEn          ; JELLYFISH
	dw CocoonEvolutionNameEn    ; COCOON_EVOLUTION
	dw KairyuShinNameEn         ; KAIRYU_SHIN
	dw SoldierOfStoneNameEn     ; SOLDIER_OF_STONE
	dw ManEatingPlantNameEn     ; MAN_EATING_PLANT
	dw KrokodilusNameEn         ; KROKODILUS
	dw GrapplerNameEn           ; GRAPPLER
	dw AxeRaiderNameEn          ; AXE_RAIDER
	dw MegazowlerNameEn         ; MEGAZOWLER
	dw UrabyNameEn              ; URABY
	dw CrawlingDragon2NameEn    ; CRAWLING_DRAGON_2
	dw RedEyesBDragonNameEn     ; RED_EYES_B_DRAGON
	dw CastleOfDarkNameEn       ; CASTLE_OF_DARK
	dw ReaperOfTheCardNameEn    ; REAPER_OF_THE_CARD
	dw KingOfYamimakaiNameEn    ; KING_OF_YAMIMAKAI
	dw BaroxNameEn              ; BAROX
	dw DarkChimeraNameEn        ; DARK_CHIMERA
	dw MetalGuardianNameEn      ; METAL_GUARDIAN
	dw CatapultTurtleNameEn     ; CATAPULT_TURTLE
	dw GyakutennoMegamiNameEn   ; GYAKUTENNO_MEGAMI
	dw MysticHorsemanNameEn     ; MYSTIC_HORSEMAN
	dw RabidHorsemanNameEn      ; RABID_HORSEMAN
	dw ZankiNameEn              ; ZANKI
	dw CrawlingDragonNameEn     ; CRAWLING_DRAGON
	dw CrassClownNameEn         ; CRASS_CLOWN
	dw ArmoredZombieNameEn      ; ARMORED_ZOMBIE
	dw DragonZombieNameEn       ; DRAGON_ZOMBIE
	dw ClownZombieNameEn        ; CLOWN_ZOMBIE
	dw PumpkingTheKingNameEn    ; PUMPKING_THE_KING
	dw BattleWarriorNameEn      ; BATTLE_WARRIOR
	dw WingsOfFlameNameEn       ; WINGS_OF_FLAME
	dw MaskOfDarknessNameEn     ; MASK_OF_DARKNESS
	dw JobChangeMirrorNameEn    ; JOB_CHANGE_MIRROR
	dw CurtainOfDarkNameEn      ; CURTAIN_OF_DARK
	dw TomozaurusNameEn         ; TOMOZAURUS
	dw SpiritOfTheWindNameEn    ; SPIRIT_OF_THE_WIND
	dw KageningenNameEn         ; KAGENINGEN
	dw GraveyardAndHandNameEn   ; GRAVEYARD_AND_HAND
	dw GoddessThirdEyeNameEn    ; GODDESS_THIRD_EYE
	dw HeroOfTheEastNameEn      ; HERO_OF_THE_EAST
	dw DomaTheAngelNameEn       ; DOMA_THE_ANGEL
	dw ThatWhichFeedsNameEn     ; THAT_WHICH_FEEDS
	dw DarkGrayNameEn           ; DARK_GRAY
	dw WhiteMagicalHatNameEn    ; WHITE_MAGICAL_HAT
	dw KamionwizardNameEn       ; KAMIONWIZARD
	dw NightmareScorpionNameEn  ; NIGHTMARE_SCORPION
	dw SpiritOfTheBookNameEn    ; SPIRIT_OF_THE_BOOK
	dw SupporterShadowsNameEn   ; SUPPORTER_SHADOWS
	dw TrialOfNightmareNameEn   ; TRIAL_OF_NIGHTMARE
	dw DreamClownNameEn         ; DREAM_CLOWN
	dw SleepingLionNameEn       ; SLEEPING_LION
	dw YamatanoScrollNameEn     ; YAMATANO_SCROLL
	dw DarkPlantNameEn          ; DARK_PLANT
	dw AncientToolNameEn        ; ANCIENT_TOOL
	dw FaithBirdNameEn          ; FAITH_BIRD
	dw OrionTheBattleNameEn     ; ORION_THE_BATTLE
	dw AnsatsuNameEn            ; ANSATSU
	dw LamoonNameEn             ; LAMOON
	dw NemurikoNameEn           ; NEMURIKO
	dw WeatherControlNameEn     ; WEATHER_CONTROL
	dw OctoberserNameEn         ; OCTOBERSER
	dw The13thGraveNameEn       ; THE_13TH_GRAVE
	dw CharubinTheFireNameEn    ; CHARUBIN_THE_FIRE
	dw MysticalCaptureNameEn    ; MYSTICAL_CAPTURE
	dw FiendsHandNameEn         ; FIENDS_HAND
	dw WittyPhantomNameEn       ; WITTY_PHANTOM
	dw MysteryHandNameEn        ; MYSTERY_HAND
	dw DragonStatueNameEn       ; DRAGON_STATUE
	dw BEyedSilZombieNameEn     ; B_EYED_SIL_ZOMBIE
	dw ToadMasterNameEn         ; TOAD_MASTER
	dw SpikedSnailNameEn        ; SPIKED_SNAIL
	dw FlameManipulatorNameEn   ; FLAME_MANIPULATOR
	dw NecrolancerNameEn        ; NECROLANCER
	dw DjinnTheWatcherNameEn    ; DJINN_THE_WATCHER
	dw BewitchingPhantomNameEn  ; BEWITCHING_PHANTOM
	dw TempleOfSkullsNameEn     ; TEMPLE_OF_SKULLS
	dw MonsterEggNameEn         ; MONSTER_EGG
	dw ShadowWhoControlNameEn   ; SHADOW_WHO_CONTROL
	dw LordOfTheLampNameEn      ; LORD_OF_THE_LAMP
	dw AkihironNameEn           ; AKIHIRON
	dw RhaimundosRedNameEn      ; RHAIMUNDOS_RED
	dw MeltingRedShadowNameEn   ; MELTING_RED_SHADOW
	dw DokuroizoTheGrimNameEn   ; DOKUROIZO_THE_GRIM
	dw FireReaperNameEn         ; FIRE_REAPER
	dw LarvasNameEn             ; LARVAS
	dw HardArmorNameEn          ; HARD_ARMOR
	dw FiregrassNameEn          ; FIREGRASS
	dw ManEaterNameEn           ; MAN_EATER
	dw DigBeakNameEn            ; DIG_BEAK
	dw MWarrior1NameEn          ; M_WARRIOR_1
	dw MWarrior2NameEn          ; M_WARRIOR_2
	dw TaintedWisdomNameEn      ; TAINTED_WISDOM
	dw LisarkNameEn             ; LISARK
	dw LordOfZemiaNameEn        ; LORD_OF_ZEMIA
	dw TheJudgementHandNameEn   ; THE_JUDGEMENT_HAND
	dw MysteriousPuppetNameEn   ; MYSTERIOUS_PUPPET
	dw AncientJarNameEn         ; ANCIENT_JAR
	dw DarkfireDragonNameEn     ; DARKFIRE_DRAGON
	dw DarkKingAbyssNameEn      ; DARK_KING_ABYSS
	dw SpiritOfTheHarpNameEn    ; SPIRIT_OF_THE_HARP
	dw BigEyeNameEn             ; BIG_EYE
	dw ArmaillNameEn            ; ARMAILL
	dw DarkPrisonerNameEn       ; DARK_PRISONER
	dw HurricailNameEn          ; HURRICAIL
	dw AncientBrainNameEn       ; ANCIENT_BRAIN
	dw FireEyeNameEn            ; FIRE_EYE
	dw MonsturtleNameEn         ; MONSTURTLE
	dw ClawReacherNameEn        ; CLAW_REACHER
	dw PhantomDewanNameEn       ; PHANTOM_DEWAN
	dw ArlownayNameEn           ; ARLOWNAY
	dw DarkShadeNameEn          ; DARK_SHADE
	dw MaskedClownNameEn        ; MASKED_CLOWN
	dw LuckyTrinketNameEn       ; LUCKY_TRINKET
	dw GeninNameEn              ; GENIN
	dw EyearmorNameEn           ; EYEARMOR
	dw FiendReflection2NameEn   ; FIEND_REFLECTION2
	dw GateDeegNameEn           ; GATE_DEEG
	dw SyncharNameEn            ; SYNCHAR
	dw FusionistNameEn          ; FUSIONIST
	dw AkakieisuNameEn          ; AKAKIEISU
	dw LalaLiOonNameEn          ; LALA_LI_OON
	dw KeyMaceNameEn            ; KEY_MACE
	dw TurtleTigerNameEn        ; TURTLE_TIGER
	dw TerraTheTerribleNameEn   ; TERRA_THE_TERRIBLE
	dw DoronNameEn              ; DORON
	dw ArmaKnightNameEn         ; ARMA_KNIGHT
	dw MechMoleZombieNameEn     ; MECH_MOLE_ZOMBIE
	dw HappyLoverNameEn         ; HAPPY_LOVER
	dw PenguinKnightNameEn      ; PENGUIN_KNIGHT
	dw PetitDragonNameEn        ; PETIT_DRAGON
	dw FrenziedPandaNameEn      ; FRENZIED_PANDA
	dw ArchfiendMarmotNameEn    ; ARCHFIEND_MARMOT
	dw PhantomGhostNameEn       ; PHANTOM_GHOST
	dw MabarrelNameEn           ; MABARREL
	dw DoroverNameEn            ; DOROVER
	dw TwinLongRods1NameEn      ; TWIN_LONG_RODS_1
	dw DrollBirdNameEn          ; DROLL_BIRD
	dw PetitAngelNameEn         ; PETIT_ANGEL
	dw WingedCleaverNameEn      ; WINGED_CLEAVER
	dw HinotamaSoulNameEn       ; HINOTAMA_SOUL
	dw ThunderKidNameEn         ; THUNDER_KID
	dw MeotokoNameEn            ; MEOTOKO
	dw AquaMadoorNameEn         ; AQUA_MADOOR
	dw KagemushaBlueNameEn      ; KAGEMUSHA_BLUE
	dw FlameGhostNameEn         ; FLAME_GHOST
	dw DryadNameEn              ; DRYAD
	dw BSkullDragonNameEn       ; B_SKULL_DRAGON
	dw TwoMouthDarkrulerNameEn  ; TWO_MOUTH_DARKRULER
	dw SolitudeNameEn           ; SOLITUDE
	dw MaskedSorcererNameEn     ; MASKED_SORCERER
	dw KumootokoNameEn          ; KUMOOTOKO
	dw MidnightFiendNameEn      ; MIDNIGHT_FIEND
	dw RoarOceanSnakeNameEn     ; ROAR_OCEAN_SNAKE
	dw TrapMasterNameEn         ; TRAP_MASTER
	dw FiendSwordNameEn         ; FIEND_SWORD
	dw SkullStalkerNameEn       ; SKULL_STALKER
	dw HitodenchakNameEn        ; HITODENCHAK
	dw WoodRemainsNameEn        ; WOOD_REMAINS
	dw HourglassOfLifeNameEn    ; HOURGLASS_OF_LIFE
	dw RareFishNameEn           ; RARE_FISH
	dw WoodClownNameEn          ; WOOD_CLOWN
	dw MadjinnGunnNameEn        ; MADJINN_GUNN
	dw DarkTitanTerrorNameEn    ; DARK_TITAN_TERROR
	dw BeautifulHeadhuntNameEn  ; BEAUTIFUL_HEADHUNT
	dw WodanTheResidentNameEn   ; WODAN_THE_RESIDENT
	dw GuardianLabyrinthNameEn  ; GUARDIAN_LABYRINTH
	dw HaniwaNameEn             ; HANIWA
	dw YashinokiNameEn          ; YASHINOKI
	dw VishwarRandiNameEn       ; VISHWAR_RANDI
	dw TheDrdekNameEn           ; THE_DRDEK
	dw DAssailantNameEn         ; D_ASSAILANT
	dw CandleOfFateNameEn       ; CANDLE_OF_FATE
	dw WaterElementNameEn       ; WATER_ELEMENT
	dw DissolverockNameEn       ; DISSOLVEROCK
	dw MedaBatNameEn            ; MEDA_BAT
	dw OneWhoHuntsSoulNameEn    ; ONE_WHO_HUNTS_SOUL
	dw RootWaterNameEn          ; ROOT_WATER
	dw MasterAndExpertNameEn    ; MASTER_AND_EXPERT
	dw WaterOmoticsNameEn       ; WATER_OMOTICS
	dw HyoNameEn                ; HYO
	dw EnchantingMermaidNameEn  ; ENCHANTING_MERMAID
	dw Nekogal1NameEn           ; NEKOGAL_1
	dw AngelwitchNameEn         ; ANGELWITCH
	dw EmbryonicBeastNameEn     ; EMBRYONIC_BEAST
	dw PreventRatNameEn         ; PREVENT_RAT
	dw DdWarriorNameEn          ; DD_WARRIOR
	dw StoneArmadillerNameEn    ; STONE_ARMADILLER
	dw BeastkingOfSwampNameEn   ; BEASTKING_OF_SWAMP
	dw AncientSorcererNameEn    ; ANCIENT_SORCERER
	dw LunarQueenElzaimNameEn   ; LUNAR_QUEEN_ELZAIM
	dw ArchfiendMirrorNameEn    ; ARCHFIEND_MIRROR
	dw SwordsmanOfAileNameEn    ; SWORDSMAN_OF_AILE
	dw RockOgreGrotto2NameEn    ; ROCK_OGRE_GROTTO2
	dw WingEggElfNameEn         ; WING_EGG_ELF
	dw FuriousSeaKingNameEn     ; FURIOUS_SEA_KING
	dw PrincessTsurugiNameEn    ; PRINCESS_TSURUGI
	dw UnknownWarriorNameEn     ; UNKNOWN_WARRIOR
	dw SectarianSecretNameEn    ; SECTARIAN_SECRET
	dw VersagoDestroyerNameEn   ; VERSAGO_DESTROYER
	dw WethaNameEn              ; WETHA
	dw MegirusLightNameEn       ; MEGIRUS_LIGHT
	dw MavelusNameEn            ; MAVELUS
	dw AncientTreeNameEn        ; ANCIENT_TREE
	dw GreenPhantomKingNameEn   ; GREEN_PHANTOM_KING
	dw GroundAttackerNameEn     ; GROUND_ATTACKER
	dw RayAndTemperatureNameEn  ; RAY_AND_TEMPERATURE
	dw GorgonEggNameEn          ; GORGON_EGG
	dw PetitMothNameEn          ; PETIT_MOTH
	dw KingFogNameEn            ; KING_FOG
	dw ProtectorThroneNameEn    ; PROTECTOR_THRONE
	dw MysticClownNameEn        ; MYSTIC_CLOWN
	dw MysticalSheep2NameEn     ; MYSTICAL_SHEEP_2
	dw HolograhNameEn           ; HOLOGRAH
	dw TaoTheChanterNameEn      ; TAO_THE_CHANTER
	dw SerpentMarauderNameEn    ; SERPENT_MARAUDER
	dw GatekeeperNameEn         ; GATEKEEPER
	dw OgreOfTheBlackNameEn     ; OGRE_OF_THE_BLACK
	dw DarkArtistNameEn         ; DARK_ARTIST
	dw ChangeSlimeNameEn        ; CHANGE_SLIME
	dw MoonEnvoyNameEn          ; MOON_ENVOY
	dw FireyarouNameEn          ; FIREYAROU
	dw PsychicKappaNameEn       ; PSYCHIC_KAPPA
	dw MasakiTheLegendNameEn    ; MASAKI_THE_LEGEND
	dw DragonessWickedNameEn    ; DRAGONESS_WICKED
	dw BioPlantNameEn           ; BIO_PLANT
	dw OneEyedShieldNameEn      ; ONE_EYED_SHIELD
	dw CyberSoldierDarkNameEn   ; CYBER_SOLDIER_DARK
	dw DragonErsatzHeadNameEn   ; DRAGON_ERSATZ_HEAD
	dw SonicMaidNameEn          ; SONIC_MAID
	dw KuramaNameEn             ; KURAMA
	dw LegendarySwordNameEn     ; LEGENDARY_SWORD
	dw SwordOfDarkNameEn        ; SWORD_OF_DARK
	dw DarkEnergyNameEn         ; DARK_ENERGY
	dw AxeOfDespairNameEn       ; AXE_OF_DESPAIR
	dw LazerCannonArmorNameEn   ; LAZER_CANNON_ARMOR
	dw InsectArmorLaserNameEn   ; INSECT_ARMOR_LASER
	dw ElfsLightNameEn          ; ELFS_LIGHT
	dw BeastFangsNameEn         ; BEAST_FANGS
	dw SteelShellNameEn         ; STEEL_SHELL
	dw VileGermsNameEn          ; VILE_GERMS
	dw BlackPendantNameEn       ; BLACK_PENDANT
	dw SilverBowAndArrowNameEn  ; SILVER_BOW_AND_ARROW
	dw HornOfLightNameEn        ; HORN_OF_LIGHT
	dw HornOfUnicornNameEn      ; HORN_OF_UNICORN
	dw DragonTreasureNameEn     ; DRAGON_TREASURE
	dw ElectroWhipNameEn        ; ELECTRO_WHIP
	dw CyberShieldNameEn        ; CYBER_SHIELD
	dw ElegantEgotistNameEn     ; ELEGANT_EGOTIST
	dw MysticalMoonNameEn       ; MYSTICAL_MOON
	dw StopDefenseNameEn        ; STOP_DEFENSE
	dw MalevolentNuzzlerNameEn  ; MALEVOLENT_NUZZLER
	dw VioletCrystalNameEn      ; VIOLET_CRYSTAL
	dw BookOfSecretArtNameEn    ; BOOK_OF_SECRET_ART
	dw InvigorationNameEn       ; INVIGORATION
	dw MachineConversionNameEn  ; MACHINE_CONVERSION
	dw RaiseBodyHeatNameEn      ; RAISE_BODY_HEAT
	dw FollowWindNameEn         ; FOLLOW_WIND
	dw PowerOfKaishinNameEn     ; POWER_OF_KAISHIN
	dw DragonCaptureJarNameEn   ; DRAGON_CAPTURE_JAR
	dw ForestNameEn             ; FOREST
	dw WastelandNameEn          ; WASTELAND
	dw MountainNameEn           ; MOUNTAIN
	dw SogenNameEn              ; SOGEN
	dw UmiNameEn                ; UMI
	dw YamiNameEn               ; YAMI
	dw DarkHoleNameEn           ; DARK_HOLE
	dw RaigekiNameEn            ; RAIGEKI
	dw MooyanCurryNameEn        ; MOOYAN_CURRY
	dw RedMedicineNameEn        ; RED_MEDICINE
	dw GoblinsRemedyNameEn      ; GOBLINS_REMEDY
	dw SoulOfThePureNameEn      ; SOUL_OF_THE_PURE
	dw DianKetoTheCureNameEn    ; DIAN_KETO_THE_CURE
	dw SparksNameEn             ; SPARKS
	dw HinotamaNameEn           ; HINOTAMA
	dw FinalFlameNameEn         ; FINAL_FLAME
	dw OokaziNameEn             ; OOKAZI
	dw TremendousFireNameEn     ; TREMENDOUS_FIRE
	dw SwordsRevealingNameEn    ; SWORDS_REVEALING
	dw SpellbindCircleNameEn    ; SPELLBIND_CIRCLE
	dw DarkPierceLightNameEn    ; DARK_PIERCE_LIGHT
	dw YaranzoNameEn            ; YARANZO
	dw KananTheSwordNameEn      ; KANAN_THE_SWORD
	dw TakriminosNameEn         ; TAKRIMINOS
	dw StuffedAnimalNameEn      ; STUFFED_ANIMAL
	dw MegasonicEyeNameEn       ; MEGASONIC_EYE
	dw SuperWarLionNameEn       ; SUPER_WAR_LION
	dw YamadronNameEn           ; YAMADRON
	dw SeiyaryuNameEn           ; SEIYARYU
	dw ThreeLeggedZombiesNameEn ; THREE_LEGGED_ZOMBIES
	dw ZeraTheMantNameEn        ; ZERA_THE_MANT
	dw FlyingPenguinNameEn      ; FLYING_PENGUIN
	dw MillenniumShieldNameEn   ; MILLENNIUM_SHIELD
	dw FairysGiftNameEn         ; FAIRYS_GIFT
	dw BLusterSoldierNameEn     ; B_LUSTER_SOLDIER
	dw FiendsMirrorNameEn       ; FIENDS_MIRROR
	dw InvalidCardNameEn        ; INVALID_CARD
	assert_table_length NUM_CARDS + 1
