Credits:
	text "Original Character &"
	text "   Monster Design   "
	text "  KAZUKI TAKAHASHI  "
	text "                    "
	text "                    "
	text "    Game Design     "
	text "  NOBUHIRO YAMADA   "
	text "                    "
	text "                    "
	text "     Programmer     "
	text "  NOBUHIRO YAMADA   "
	text "    TAKURI CHIDA    "
	text "                    "
	text "                    "
	text " Graphics Direction "
	text "                    "
	text "  KANAKO HASHIMOTO  "
	text "                    "
	text "                    "
	text "       Sound        "
	text "                    "
	text "   KENICHI KAMIO    "
	text "                    "
	text "                    "
	text "   Monster Design   "
	text "                    "
	text "        •••         "
	text "    ISSUN BOSHI     "
	text "                    "
	text "   NAYU ITSUMORI    "
	text "       EVA 14       "
	text "                    "
	text "        S•A         "
	text "                    "
	text "         F          "
	text "   KUSARE GEDOJIN   "
	text "                    "
	text "     SAIKO-KUN      "
	text "                    "
	text "        CIEL        "
	text "       PIMAN        "
	text "      PIGUMON       "
	text "    RYUKA HIJIRI    "
	text "      FURINJI       "
	text "   PONPOKO TANUKI   "
	text "  KOTEN MIKAGEYAMA  "
	text "                    "
	text "      MURAKAMI      "
	text "      YUGI JR.      "
	text "                    "
	text "    TAKAHIRO AOI    "
	text "                    "
	text "   TAKAYUKI AOKI    "
	text "  MISAKI AKABOSHI   "
	text "                    "
	text "    YUSUKE ASANO    "
	text "   TOSHIRO ADACHI   "
	text "    HIROYUKI ABE    "
	text "    AKIRA ANZAI     "
	text "     SHIN ANZAI     "
	text "   KYOJI IKEGAMI    "
	text "    YOICHI IKEDA    "
	text "                    "
	text "   ATSUSHI ISHII    "
	text "   KEITA ISHIZAKA   "
	text "   MASATAKA IZUTA   "
	text "                    "
	text " HIROYUKI ICHIKAWA  "
	text "                    "
	text "     YUICHI ITO     "
	text "    RYO INAGAKI     "
	text "    KOJI IMAMURA    "
	text "                    "
	text "  TAKESHI IWAKOSHI  "
	text "   MANABU IWASAKA   "
	text "                    "
	text "   REINA IWASAKI    "
	text "    KENTARO UEDA    "
	text "    HIROSHI UEDA    "
	text "    MIHO EDOTANI    "
	text "                    "
	text "    HOTAKE OISHI    "
	text "                    "
	text "   MIWAKO OSHIRO    "
	text "                    "
	text "    TOMOMI OOYA     "
	text "   SEIJYU OKAMURA   "
	text "   KAZUYA OKUMURA   "
	text "   HIDEKAZU OZAKI   "
	text "  HIRONOBU OCHIAI   "
	text "  MASASHI ONODERA   "
	text "                    "
	text "  TETSUYA KATAOKA   "
	text "  HAJIME KATAGIRI   "
	text "                    "
	text "   SHUNSUKE KATO    "
	text "     YUJI KATO      "
	text "   GAKUSHI KADOTA   "
	text "    KOJI KANAIWA    "
	text "   HIDEKI KANEKO    "
	text "                    "
	text " HIROTAKE KAMIKOUSU "
	text "                    "
	text " RYOSUKE KAMIKOUSU  "
	text "                    "
	text "   KOHEI KAWASAKI   "
	text "                    "
	text " TOMOHISA KAWAHARA  "
	text "                    "
	text "    MASAKI KITAI    "
	text "    SHUHEI KIDO     "
	text "  SHIGEHIRO KIMURA  "
	text "   GOKI KUSAMICHI   "
	text "      KUNIGATA      "
	text "     JUNKO KUBO     "
	text "    MARI KUBOTA     "
	text "  MORITAKA KUMAGAI  "
	text "                    "
	text "   MASATO KURANO    "
	text "  KAZUYA KURAMOTO   "
	text "                    "
	text "   OSAMU KUWAHARA   "
	text "    NAO KOUGAKU     "
	text "   MAMORU KOUDAKI   "
	text "    SHIN KOJIMA     "
	text "  YOSHINORI KOJIMA  "
	text "                    "
	text "   MAKOTO KOTAKE    "
	text "                    "
	text "  TAKAYUKI KONISHI  "
	text "  SHINSUKE KOMABA   "
	text "                    "
	text "  TAKANAO KOMINAMI  "
	text "    MIYUKI KONDO    "
	text "                    "
	text "     YUKI SAIKI     "
	text "     JUN SAITO      "
	text "                    "
	text "    CHIEMI SAITO    "
	text "                    "
	text "   TSUKASA SAITO    "
	text "                    "
	text "  TETSUNARI SAITO   "
	text "                    "
	text "                    "
	text "   KAZUMI SASAKI    "
	text "                    "
	text "   TOMOHIKO SASOU   "
	text "                    "
	text "     KAORI SATO     "
	text "                    "
	text "    KEISUKE SATO    "
	text "      GOU SATO      "
	text "   HIROKAZU SATO    "
	text "                    "
	text " TAKUMI SARUWATARI  "
	text "                    "
	text "  KATSUYUKI SHINA   "
	text "   RYOTA SHIOZAKI   "
	text " TOSHIAKI SHIGEHISA "
	text "SATOHIRO SHIGEMATSU "
	text "                    "
	text "   RYOSUKE SHIMO    "
	text "  TAKESHI SHIMODA   "
	text "   KENJI SHINNABE   "
	text "   ATSUSHI SUGAI    "
	text "     NAOTO SUGI     "
	text "    OOKA SUGITA     "
	text "   KAZUHO SUZUKI    "
	text "   KAZUYA SUZUKI    "
	text "  KAZUYUKI SUZUKI   "
	text "                    "
	text "    AKIRA SEKINE    "
	text "                    "
	text "    HITOSHI SOMA    "
	text "  KAZUKI SOTOKADO   "
	text "   JUN TAKAHASHI    "
	text "                    "
	text " FUMIHITO TAKAHASHI "
	text "                    "
	text " NARITOMO TAKAHAMA  "
	text "                    "
	text "    YUKO TASHIRO    "
	text "   KOTARO TADANO    "
	text "   KENJI TATEYAMA   "
	text "                    "
	text "  KENSHIRO TANAKA   "
	text "    YUJI TANABE     "
	text "                    "
	text "  YUICHIRO TAMURA   "
	text "                    "
	text "  KENTA TARUSHITA   "
	text "   KOHEI TSUKADA    "
	text "                    "
	text "  AKIHIRO TSUCHIYA  "
	text "                    "
	text "  TOMOKO TSUTSUMI   "
	text "                    "
	text "  TOMOHIRO TSURUMI  "
	text "   MASAYASU TODA    "
	text "    TAKESHI TOBA    "
	text "                    "
	text "   KEISUKE TOMITA   "
	text "  DAICHI TOMIYAMA   "
	text "                    "
	text "  TOMOTAKA TOYAMA   "
	text "                    "
	text "   ATSUSHI NAKAO    "
	text "                    "
	text "     YUTA NAKAO     "
	text "    RYOTA NAGAO     "
	text "  TAKUMI NAKAJIMA   "
	text "   MASAKI NAGATA    "
	text "                    "
	text "   MAYU NAKATSURU   "
	text "                    "
	text "  YOICHI NAKANISHI  "
	text "                    "
	text "   AKIKO NAKAMOTO   "
	text "                    "
	text "    SHUKA NAKAYA    "
	text "   HIROSHI NAGAYA   "
	text "                    "
	text "   MIKI NISHISATO   "
	text "                    "
	text "  AKIKO NISHIMURA   "
	text "                    "
	text "  TAKURO NISHIMURA  "
	text "                    "
	text "    MARIKO NITTA    "
	text "                    "
	text "SHUNICHIRO NINOMIYA "
	text "    RURI NOGUCHI    "
	text " MASAKAZU NONOMURA  "
	text "                    "
	text "  HIRONORI HATANO   "
	text "                    "
	text "   TAKUYA HAMANO    "
	text "                    "
	text "   KIICHI HAYASHI   "
	text "   YUJI HAYATAKE    "
	text "   HIDEAKI HARADA   "
	text "    JUN HISAKAWA    "
	text "     YUYA HIDA      "
	text "                    "
	text "   TOSHIAKI HIRA    "
	text "                    "
	text "   MASAKI HIRONO    "
	text "   YAYOI FUKUNAGA   "
	text "   TAKESHI FUJII    "
	text "   KENICHI FUJITA   "
	text "    CHIE FUJITA     "
	text "  MASATOSHI FUJITA  "
	text "  MITSUMASA FUJITA  "
	text " KATSUHITO FUJIHARA "
	text "   EIJI FUJIYOSHI   "
	text "  TOSHIKAZU FUTAMI  "
	text "                    "
	text "   ASAMI FURUKAWA   "
	text "                    "
	text "  SATOSHI FURUKAWA  "
	text "   YUKI FURUDAKA    "
	text "                    "
	text "   SHOTARO HOKARI   "
	text "                    "
	text "   KEISUKE HOSOME   "
	text "    GOU HONZAWA     "
	text " HIDEFUMI MAESHIMA  "
	text "     KAYO MAEDA     "
	text "    KENTA MASUDA    "
	text "                    "
	text "    NAO MATSUURA    "
	text " KEISUKE MATSUZAWA  "
	text "   AYUMI MATSUDA    "
	text " MASAHIRO MITSUNAGA "
	text "                    "
	text "   KAIRI MIYASATO   "
	text "                    "
	text "    SAORI MUKAI     "
	text "    KYOJI MURAI     "
	text "                    "
	text "  MASAYUKI MURANO   "
	text "   YUMA MOCHIZUKI   "
	text "                    "
	text "  SEIICHI MOTOYAMA  "
	text "                    "
	text "  SHUNICHI MORITA   "
	text "    SEIJI MONMA     "
	text "   SHOTO YAMAZAKI   "
	text "  HIROSHI YAMAZAKI  "
	text "   KEISUKE YAMADA   "
	text "   TAISHI YAMADA    "
	text "  YUKIHISA YAMADA   "
	text "                    "
	text "   IKUO YAMAMOTO    "
	text "   KENJI YAMAMOTO   "
	text "                    "
	text "  HIROKI YAMAMOTO   "
	text "                    "
	text " MASAHIRO YAMAMOTO  "
	text "  YASUSHI YUBIYADO  "
	text "  YUKIO YOSHIZAKI   "
	text "  MIYUKI YOSHIZAWA  "
	text "   KAZUYA YOSHIDA   "
	text "   TAKUMI YOSHIDA   "
	text " YOSHIHIRO YOSHIDA  "
	text "     TARO YODA      "
	text " TAKAYUKI WATANABE  "
	text "                    "
	text "                    "
	text "                    "
	text "   Monster Notes    "
	text "                    "
	text "  KEITA SHIMOMURA   "
	text "                    "
	text "                    "
	text "   Special Thanks   "
	text " KAZUHIKO TORISHIMA "
	text "                    "
	text "TOSHIMASA TAKAHASHI "
	text "                    "
	text "  YOSHIHISA HEISHI  "
	text "   FUYUTO TAKEDA    "
	text "                    "
	text "   TOMOYUKI SHIMA   "
	text "                    "
	text "                    "
	text "  HIDEO YOSHIKURA   "
	text "   TAKESHI NOMURA   "
	text "  MUNEHARU MACHIDA  "
	text "   JUNJI YAMAMOTO   "
	text "                    "
	text "                    "
	text "  LIGHT LINK MUSIC  "
	text "                    "
	text "       I•T•L        "
	text "                    "
	text "                    "
	text "                    "
	text "   MICHIKO TOKORO   "
	text "                    "
	text "   HIROYUKI FUKUI   "
	text "  TSUTOMU WATANABE  "
	text "  HIRATA HIDEHIRO   "
	text "                    "
	text "                    "
	text "                    "
	text " KATSUHIRO NAKAYAMA "
	text "                    "
	text "    MASATO SAKAI    "
	text "    YOSHIKO YAGI    "
	text "   SEKIGUCHI YOKO   "
	text "                    "
	text "                    "
	text "      Producer      "
	text "                    "
	text " SATOSHI SHIMOMURA  "
	text "                    "
	text "                    "
	text " Executive Producer "
	text "   KAZUMI KITAUE    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "      THE END       "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	db $ff ; end

	; vestigial japanese text
PUSHC credits
	text " ひろの まさき            "
	text "    ゛               "
	text " ふくなか やよい           "
	text "  ゛                 "
	text " ふしい たけし            "
	text "  ゛                 "
	text " ふした けんいち           "
	text "  ゛                 "
	text " ふした ちえ             "
	text "  ゛                 "
	text " ふした まさとし           "
	text "  ゛                 "
	text " ふした みつまさ           "
	text "  ゛                 "
	text " ふしはら かつひと          "
	text "  ゛     ゛           "
	text " ふしよし えいし           "
	text "        ゛           "
	text " ふたみ としかす           "
	text "                    "
	text " ふるかわ あさみ           "
	text "                    "
	text " ふるかわ さとし           "
	text "   ゛                "
	text " ふるたか ゆうき           "
	text "                    "
	text " ほかり しょうたろう         "
	text "                    "
	text " ほそめ けいすけ           "
	text "   ゛  ゛             "
	text " ほんさわ こう            "
	text "       ゛            "
	text " まえしま ひてふみ          "
	text "   ゛                "
	text " まえた かよ             "
	text "   ゛                "
	text " ますた けんた            "
	text "                    "
	text " まつうら なお            "
	text "   ゛                "
	text " まつさわ けいすけ          "
	text "   ゛                "
	text " まつた あゆみ            "
	text "    ゛               "
	text " みつなか まさひろ          "
	text "                    "
	text " みやさと かいり           "
	text "                    "
	text " むかい さおり            "
	text "        ゛           "
	text " むらい きょうし           "
	text "                    "
	text " むらの まさゆき           "
	text "   ゛                "
	text " もちつき ゆうま           "
	text "                    "
	text " もとやま せいいち          "
	text "                    "
	text " もりた しゅんいち          "
	text "       ゛            "
	text " もんま せいし            "
	text "   ゛                "
	text " やまさき しょうた          "
	text "   ゛                "
	text " やまさき ひろし           "
	text "   ゛                "
	text " やまた けいすけ           "
	text "   ゛                "
	text " やまた たいし            "
	text "   ゛                "
	text " やまた ゆきひさ           "
	text "                    "
	text " やまもと いくお           "
	text "        ゛           "
	text " やまもと けんし           "
	text "                    "
	text " やまもと ひろき           "
	text "                    "
	text " やまもと まさひろ          "
	text "  ゛ ゛               "
	text " ゆひやと やすし           "
	text "   ゛                "
	text " よしさき ゆきお           "
	text "   ゛                "
	text " よしさわ みゆき           "
	text "   ゛  ゛             "
	text " よした かすや            "
	text "   ゛                "
	text " よした たくみ            "
	text "   ゛                "
	text " よした よしひろ           "
	text "  ゛                 "
	text " よた たろう             "
	text "    ゛               "
	text " わたなへ たかゆき          "
	text "                    "
	text "                    "
	text "                 モンス"
	text "タ-ノ-ツ               "
	text "                    "
	text " シモムラ ケイタ           "
	text "                    "
	text "                  ゜ "
	text "                 スへシ"
	text "ャルサンクス              "
	text "       ゛            "
	text " とりしま かすひこ          "
	text "                    "
	text " たかはし としまさ          "
	text "                    "
	text " へいし よしひさ           "
	text "   ゛                "
	text " たけた ふゆと            "
	text "                    "
	text " しま ともゆき            "
	text "                    "
	text "                    "
	text "       ゛            "
	text " よしくら ひてお           "
	text "   ゛                "
	text " こんとう ゆう            "
	text "   ゛                "
	text " まちた むねはる           "
	text "      ゛  ゛          "
	text " やまもと しゅんし          "
	text "                    "
	text "                    "
	text "          ゛         "
	text " ライトりンクミュ-シック       "
	text "                    "
	text " アイ·ティ-·エル          "
	text "                    "
	text "                    "
	text "                    "
	text " ところ みちこ            "
	text "                    "
	text " ふくい ひろゆき           "
	text "    ゛               "
	text " わたなへ つとむ           "
	text "      ゛             "
	text " ひらた ひてひろ           "
	text "                    "
	text "                    "
	text "                    "
	text " なかやま かつひろ          "
	text "                    "
	text " さかい まさと            "
	text "  ゛                 "
	text " やき よしこ             "
	text "   ゛                "
	text " せきくち ようこ           "
	text "                    "
	text "                 ゜ ゛"
	text "                 フロテ"
	text "ュ-サ-                "
	text "                    "
	text " しもむら さとし           "
	text "                    "
	text "                  ゛゛"
	text "   ゛゜ ゛          エクセ"
	text "クティフフロテュ-サ-         "
	text "       ゛            "
	text " きたうえ かすみ           "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "   おわり              "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "               "
	db $ff ; end
POPC
