CardNamePointers:
	dw BEyeWhiteDragonName    ; B_EYE_WHITE_DRAGON
	dw MysticalElfName        ; MYSTICAL_ELF
	dw HitotsuMeGiantName     ; HITOTSU_ME_GIANT
	dw BabyDragonName         ; BABY_DRAGON
	dw RyuKishinName          ; RYU_KISHIN
	dw FeralImpName           ; FERAL_IMP
	dw WingedDragon1Name      ; WINGED_DRAGON_1
	dw MushroomManName        ; MUSHROOM_MAN
	dw ShadowSpecterName      ; SHADOW_SPECTER
	dw BlacklandDragonName    ; BLACKLAND_DRAGON
	dw SwordArmDragonName     ; SWORD_ARM_DRAGON
	dw SwampBattleguardName   ; SWAMP_BATTLEGUARD
	dw TyhoneName             ; TYHONE
	dw BattleSteerName        ; BATTLE_STEER
	dw FlameSwordsmanName     ; FLAME_SWORDSMAN
	dw TimeWizardName         ; TIME_WIZARD
	dw RLegOfForbiddenName    ; R_LEG_OF_FORBIDDEN
	dw LLegOfForbiddenName    ; L_LEG_OF_FORBIDDEN
	dw RArmOfForbiddenName    ; R_ARM_OF_FORBIDDEN
	dw LArmOfForbiddenName    ; L_ARM_OF_FORBIDDEN
	dw ExodiaForbiddenName    ; EXODIA_FORBIDDEN
	dw SummonedSkullName      ; SUMMONED_SKULL
	dw WickedWormBeastName    ; WICKED_WORM_BEAST
	dw SkullServantName       ; SKULL_SERVANT
	dw HornImpName            ; HORN_IMP
	dw BattleOxName           ; BATTLE_OX
	dw BeaverWarriorName      ; BEAVER_WARRIOR
	dw RockOgreGrotto1Name    ; ROCK_OGRE_GROTTO1
	dw MountainWarriorName    ; MOUNTAIN_WARRIOR
	dw ZombieWarriorName      ; ZOMBIE_WARRIOR
	dw KoumoriDragonName      ; KOUMORI_DRAGON
	dw TwoHeadedKingRexName   ; TWO_HEADED_KING_REX
	dw JudgeManName           ; JUDGE_MAN
	dw SaggiTheClownName      ; SAGGI_THE_CLOWN
	dw DarkMagicianName       ; DARK_MAGICIAN
	dw TheSnakeHairName       ; THE_SNAKE_HAIR
	dw GaiaDragonChampName    ; GAIA_DRAGON_CHAMP
	dw GaiaFierceKnightName   ; GAIA_FIERCE_KNIGHT
	dw CurseOfDragonName      ; CURSE_OF_DRAGON
	dw DragonPiperName        ; DRAGON_PIPER
	dw CelticGuardianName     ; CELTIC_GUARDIAN
	dw IllusionFacelessName   ; ILLUSION_FACELESS
	dw KarbonalaWarriorName   ; KARBONALA_WARRIOR
	dw RogueDollName          ; ROGUE_DOLL
	dw WattkidName            ; WATTKID
	dw GrifforeName           ; GRIFFORE
	dw TorikeName             ; TORIKE
	dw SanganName             ; SANGAN
	dw BigInsectName          ; BIG_INSECT
	dw BasicInsectName        ; BASIC_INSECT
	dw ArmoredLizardName      ; ARMORED_LIZARD
	dw HerculesBeetleName     ; HERCULES_BEETLE
	dw KillerNeedleName       ; KILLER_NEEDLE
	dw GokiboreName           ; GOKIBORE
	dw GiantFleaName          ; GIANT_FLEA
	dw LarvaeMothName         ; LARVAE_MOTH
	dw GreatMothName          ; GREAT_MOTH
	dw KuribohName            ; KURIBOH
	dw MammothGraveyardName   ; MAMMOTH_GRAVEYARD
	dw GreatWhiteName         ; GREAT_WHITE
	dw WolfName               ; WOLF
	dw HarpieLadyName         ; HARPIE_LADY
	dw HarpieLadySisterName   ; HARPIE_LADY_SISTER
	dw TigerAxeName           ; TIGER_AXE
	dw SilverFangName         ; SILVER_FANG
	dw KojikocyName           ; KOJIKOCY
	dw PerfectGreatMothName   ; PERFECT_GREAT_MOTH
	dw GaroozisName           ; GAROOZIS
	dw ThousandDragonName     ; THOUSAND_DRAGON
	dw FiendKrakenName        ; FIEND_KRAKEN
	dw JellyfishName          ; JELLYFISH
	dw CocoonEvolutionName    ; COCOON_EVOLUTION
	dw KairyuShinName         ; KAIRYU_SHIN
	dw SoldierOfStoneName     ; SOLDIER_OF_STONE
	dw ManEatingPlantName     ; MAN_EATING_PLANT
	dw KrokodilusName         ; KROKODILUS
	dw GrapplerName           ; GRAPPLER
	dw AxeRaiderName          ; AXE_RAIDER
	dw MegazowlerName         ; MEGAZOWLER
	dw UrabyName              ; URABY
	dw CrawlingDragon2Name    ; CRAWLING_DRAGON_2
	dw RedEyesBDragonName     ; RED_EYES_B_DRAGON
	dw CastleOfDarkName       ; CASTLE_OF_DARK
	dw ReaperOfTheCardName    ; REAPER_OF_THE_CARD
	dw KingOfYamimakaiName    ; KING_OF_YAMIMAKAI
	dw BaroxName              ; BAROX
	dw DarkChimeraName        ; DARK_CHIMERA
	dw MetalGuardianName      ; METAL_GUARDIAN
	dw CatapultTurtleName     ; CATAPULT_TURTLE
	dw GyakutennoMegamiName   ; GYAKUTENNO_MEGAMI
	dw MysticHorsemanName     ; MYSTIC_HORSEMAN
	dw RabidHorsemanName      ; RABID_HORSEMAN
	dw ZankiName              ; ZANKI
	dw CrawlingDragonName     ; CRAWLING_DRAGON
	dw CrassClownName         ; CRASS_CLOWN
	dw ArmoredZombieName      ; ARMORED_ZOMBIE
	dw DragonZombieName       ; DRAGON_ZOMBIE
	dw ClownZombieName        ; CLOWN_ZOMBIE
	dw PumpkingTheKingName    ; PUMPKING_THE_KING
	dw BattleWarriorName      ; BATTLE_WARRIOR
	dw WingsOfFlameName       ; WINGS_OF_FLAME
	dw MaskOfDarknessName     ; MASK_OF_DARKNESS
	dw JobChangeMirrorName    ; JOB_CHANGE_MIRROR
	dw CurtainOfDarkName      ; CURTAIN_OF_DARK
	dw TomozaurusName         ; TOMOZAURUS
	dw SpiritOfTheWindName    ; SPIRIT_OF_THE_WIND
	dw KageningenName         ; KAGENINGEN
	dw GraveyardAndHandName   ; GRAVEYARD_AND_HAND
	dw GoddessThirdEyeName    ; GODDESS_THIRD_EYE
	dw HeroOfTheEastName      ; HERO_OF_THE_EAST
	dw DomaTheAngelName       ; DOMA_THE_ANGEL
	dw ThatWhichFeedsName     ; THAT_WHICH_FEEDS
	dw DarkGrayName           ; DARK_GRAY
	dw WhiteMagicalHatName    ; WHITE_MAGICAL_HAT
	dw KamionwizardName       ; KAMIONWIZARD
	dw NightmareScorpionName  ; NIGHTMARE_SCORPION
	dw SpiritOfTheBookName    ; SPIRIT_OF_THE_BOOK
	dw SupporterShadowsName   ; SUPPORTER_SHADOWS
	dw TrialOfNightmareName   ; TRIAL_OF_NIGHTMARE
	dw DreamClownName         ; DREAM_CLOWN
	dw SleepingLionName       ; SLEEPING_LION
	dw YamatanoScrollName     ; YAMATANO_SCROLL
	dw DarkPlantName          ; DARK_PLANT
	dw AncientToolName        ; ANCIENT_TOOL
	dw FaithBirdName          ; FAITH_BIRD
	dw OrionTheBattleName     ; ORION_THE_BATTLE
	dw AnsatsuName            ; ANSATSU
	dw LamoonName             ; LAMOON
	dw NemurikoName           ; NEMURIKO
	dw WeatherControlName     ; WEATHER_CONTROL
	dw OctoberserName         ; OCTOBERSER
	dw The13thGraveName       ; THE_13TH_GRAVE
	dw CharubinTheFireName    ; CHARUBIN_THE_FIRE
	dw MysticalCaptureName    ; MYSTICAL_CAPTURE
	dw FiendsHandName         ; FIENDS_HAND
	dw WittyPhantomName       ; WITTY_PHANTOM
	dw MysteryHandName        ; MYSTERY_HAND
	dw DragonStatueName       ; DRAGON_STATUE
	dw BEyedSilZombieName     ; B_EYED_SIL_ZOMBIE
	dw ToadMasterName         ; TOAD_MASTER
	dw SpikedSnailName        ; SPIKED_SNAIL
	dw FlameManipulatorName   ; FLAME_MANIPULATOR
	dw NecrolancerName        ; NECROLANCER
	dw DjinnTheWatcherName    ; DJINN_THE_WATCHER
	dw BewitchingPhantomName  ; BEWITCHING_PHANTOM
	dw TempleOfSkullsName     ; TEMPLE_OF_SKULLS
	dw MonsterEggName         ; MONSTER_EGG
	dw ShadowWhoControlName   ; SHADOW_WHO_CONTROL
	dw LordOfTheLampName      ; LORD_OF_THE_LAMP
	dw AkihironName           ; AKIHIRON
	dw RhaimundosRedName      ; RHAIMUNDOS_RED
	dw MeltingRedShadowName   ; MELTING_RED_SHADOW
	dw DokuroizoTheGrimName   ; DOKUROIZO_THE_GRIM
	dw FireReaperName         ; FIRE_REAPER
	dw LarvasName             ; LARVAS
	dw HardArmorName          ; HARD_ARMOR
	dw FiregrassName          ; FIREGRASS
	dw ManEaterName           ; MAN_EATER
	dw DigBeakName            ; DIG_BEAK
	dw MWarrior1Name          ; M_WARRIOR_1
	dw MWarrior2Name          ; M_WARRIOR_2
	dw TaintedWisdomName      ; TAINTED_WISDOM
	dw LisarkName             ; LISARK
	dw LordOfZemiaName        ; LORD_OF_ZEMIA
	dw TheJudgementHandName   ; THE_JUDGEMENT_HAND
	dw MysteriousPuppetName   ; MYSTERIOUS_PUPPET
	dw AncientJarName         ; ANCIENT_JAR
	dw DarkfireDragonName     ; DARKFIRE_DRAGON
	dw DarkKingAbyssName      ; DARK_KING_ABYSS
	dw SpiritOfTheHarpName    ; SPIRIT_OF_THE_HARP
	dw BigEyeName             ; BIG_EYE
	dw ArmaillName            ; ARMAILL
	dw DarkPrisonerName       ; DARK_PRISONER
	dw HurricailName          ; HURRICAIL
	dw AncientBrainName       ; ANCIENT_BRAIN
	dw FireEyeName            ; FIRE_EYE
	dw MonsturtleName         ; MONSTURTLE
	dw ClawReacherName        ; CLAW_REACHER
	dw PhantomDewanName       ; PHANTOM_DEWAN
	dw ArlownayName           ; ARLOWNAY
	dw DarkShadeName          ; DARK_SHADE
	dw MaskedClownName        ; MASKED_CLOWN
	dw LuckyTrinketName       ; LUCKY_TRINKET
	dw GeninName              ; GENIN
	dw EyearmorName           ; EYEARMOR
	dw FiendReflection2Name   ; FIEND_REFLECTION2
	dw GateDeegName           ; GATE_DEEG
	dw SyncharName            ; SYNCHAR
	dw FusionistName          ; FUSIONIST
	dw AkakieisuName          ; AKAKIEISU
	dw LalaLiOonName          ; LALA_LI_OON
	dw KeyMaceName            ; KEY_MACE
	dw TurtleTigerName        ; TURTLE_TIGER
	dw TerraTheTerribleName   ; TERRA_THE_TERRIBLE
	dw DoronName              ; DORON
	dw ArmaKnightName         ; ARMA_KNIGHT
	dw MechMoleZombieName     ; MECH_MOLE_ZOMBIE
	dw HappyLoverName         ; HAPPY_LOVER
	dw PenguinKnightName      ; PENGUIN_KNIGHT
	dw PetitDragonName        ; PETIT_DRAGON
	dw FrenziedPandaName      ; FRENZIED_PANDA
	dw ArchfiendMarmotName    ; ARCHFIEND_MARMOT
	dw PhantomGhostName       ; PHANTOM_GHOST
	dw MabarrelName           ; MABARREL
	dw DoroverName            ; DOROVER
	dw TwinLongRods1Name      ; TWIN_LONG_RODS_1
	dw DrollBirdName          ; DROLL_BIRD
	dw PetitAngelName         ; PETIT_ANGEL
	dw WingedCleaverName      ; WINGED_CLEAVER
	dw HinotamaSoulName       ; HINOTAMA_SOUL
	dw ThunderKidName         ; THUNDER_KID
	dw MeotokoName            ; MEOTOKO
	dw AquaMadoorName         ; AQUA_MADOOR
	dw KagemushaBlueName      ; KAGEMUSHA_BLUE
	dw FlameGhostName         ; FLAME_GHOST
	dw DryadName              ; DRYAD
	dw BSkullDragonName       ; B_SKULL_DRAGON
	dw TwoMouthDarkrulerName  ; TWO_MOUTH_DARKRULER
	dw SolitudeName           ; SOLITUDE
	dw MaskedSorcererName     ; MASKED_SORCERER
	dw KumootokoName          ; KUMOOTOKO
	dw MidnightFiendName      ; MIDNIGHT_FIEND
	dw RoarOceanSnakeName     ; ROAR_OCEAN_SNAKE
	dw TrapMasterName         ; TRAP_MASTER
	dw FiendSwordName         ; FIEND_SWORD
	dw SkullStalkerName       ; SKULL_STALKER
	dw HitodenchakName        ; HITODENCHAK
	dw WoodRemainsName        ; WOOD_REMAINS
	dw HourglassOfLifeName    ; HOURGLASS_OF_LIFE
	dw RareFishName           ; RARE_FISH
	dw WoodClownName          ; WOOD_CLOWN
	dw MadjinnGunnName        ; MADJINN_GUNN
	dw DarkTitanTerrorName    ; DARK_TITAN_TERROR
	dw BeautifulHeadhuntName  ; BEAUTIFUL_HEADHUNT
	dw WodanTheResidentName   ; WODAN_THE_RESIDENT
	dw GuardianLabyrinthName  ; GUARDIAN_LABYRINTH
	dw HaniwaName             ; HANIWA
	dw YashinokiName          ; YASHINOKI
	dw VishwarRandiName       ; VISHWAR_RANDI
	dw TheDrdekName           ; THE_DRDEK
	dw DAssailantName         ; D_ASSAILANT
	dw CandleOfFateName       ; CANDLE_OF_FATE
	dw WaterElementName       ; WATER_ELEMENT
	dw DissolverockName       ; DISSOLVEROCK
	dw MedaBatName            ; MEDA_BAT
	dw OneWhoHuntsSoulName    ; ONE_WHO_HUNTS_SOUL
	dw RootWaterName          ; ROOT_WATER
	dw MasterAndExpertName    ; MASTER_AND_EXPERT
	dw WaterOmoticsName       ; WATER_OMOTICS
	dw HyoName                ; HYO
	dw EnchantingMermaidName  ; ENCHANTING_MERMAID
	dw Nekogal1Name           ; NEKOGAL_1
	dw AngelwitchName         ; ANGELWITCH
	dw EmbryonicBeastName     ; EMBRYONIC_BEAST
	dw PreventRatName         ; PREVENT_RAT
	dw DdWarriorName          ; DD_WARRIOR
	dw StoneArmadillerName    ; STONE_ARMADILLER
	dw BeastkingOfSwampName   ; BEASTKING_OF_SWAMP
	dw AncientSorcererName    ; ANCIENT_SORCERER
	dw LunarQueenElzaimName   ; LUNAR_QUEEN_ELZAIM
	dw ArchfiendMirrorName    ; ARCHFIEND_MIRROR
	dw SwordsmanOfAileName    ; SWORDSMAN_OF_AILE
	dw RockOgreGrotto2Name    ; ROCK_OGRE_GROTTO2
	dw WingEggElfName         ; WING_EGG_ELF
	dw FuriousSeaKingName     ; FURIOUS_SEA_KING
	dw PrincessTsurugiName    ; PRINCESS_TSURUGI
	dw UnknownWarriorName     ; UNKNOWN_WARRIOR
	dw SectarianSecretName    ; SECTARIAN_SECRET
	dw VersagoDestroyerName   ; VERSAGO_DESTROYER
	dw WethaName              ; WETHA
	dw MegirusLightName       ; MEGIRUS_LIGHT
	dw MavelusName            ; MAVELUS
	dw AncientTreeName        ; ANCIENT_TREE
	dw GreenPhantomKingName   ; GREEN_PHANTOM_KING
	dw GroundAttackerName     ; GROUND_ATTACKER
	dw RayAndTemperatureName  ; RAY_AND_TEMPERATURE
	dw GorgonEggName          ; GORGON_EGG
	dw PetitMothName          ; PETIT_MOTH
	dw KingFogName            ; KING_FOG
	dw ProtectorThroneName    ; PROTECTOR_THRONE
	dw MysticClownName        ; MYSTIC_CLOWN
	dw MysticalSheep2Name     ; MYSTICAL_SHEEP_2
	dw HolograhName           ; HOLOGRAH
	dw TaoTheChanterName      ; TAO_THE_CHANTER
	dw SerpentMarauderName    ; SERPENT_MARAUDER
	dw GatekeeperName         ; GATEKEEPER
	dw OgreOfTheBlackName     ; OGRE_OF_THE_BLACK
	dw DarkArtistName         ; DARK_ARTIST
	dw ChangeSlimeName        ; CHANGE_SLIME
	dw MoonEnvoyName          ; MOON_ENVOY
	dw FireyarouName          ; FIREYAROU
	dw PsychicKappaName       ; PSYCHIC_KAPPA
	dw MasakiTheLegendName    ; MASAKI_THE_LEGEND
	dw DragonessWickedName    ; DRAGONESS_WICKED
	dw BioPlantName           ; BIO_PLANT
	dw OneEyedShieldName      ; ONE_EYED_SHIELD
	dw CyberSoldierDarkName   ; CYBER_SOLDIER_DARK
	dw DragonErsatzHeadName   ; DRAGON_ERSATZ_HEAD
	dw SonicMaidName          ; SONIC_MAID
	dw KuramaName             ; KURAMA
	dw LegendarySwordName     ; LEGENDARY_SWORD
	dw SwordOfDarkName        ; SWORD_OF_DARK
	dw DarkEnergyName         ; DARK_ENERGY
	dw AxeOfDespairName       ; AXE_OF_DESPAIR
	dw LazerCannonArmorName   ; LAZER_CANNON_ARMOR
	dw InsectArmorLaserName   ; INSECT_ARMOR_LASER
	dw ElfsLightName          ; ELFS_LIGHT
	dw BeastFangsName         ; BEAST_FANGS
	dw SteelShellName         ; STEEL_SHELL
	dw VileGermsName          ; VILE_GERMS
	dw BlackPendantName       ; BLACK_PENDANT
	dw SilverBowAndArrowName  ; SILVER_BOW_AND_ARROW
	dw HornOfLightName        ; HORN_OF_LIGHT
	dw HornOfUnicornName      ; HORN_OF_UNICORN
	dw DragonTreasureName     ; DRAGON_TREASURE
	dw ElectroWhipName        ; ELECTRO_WHIP
	dw CyberShieldName        ; CYBER_SHIELD
	dw ElegantEgotistName     ; ELEGANT_EGOTIST
	dw MysticalMoonName       ; MYSTICAL_MOON
	dw StopDefenseName        ; STOP_DEFENSE
	dw MalevolentNuzzlerName  ; MALEVOLENT_NUZZLER
	dw VioletCrystalName      ; VIOLET_CRYSTAL
	dw BookOfSecretArtName    ; BOOK_OF_SECRET_ART
	dw InvigorationName       ; INVIGORATION
	dw MachineConversionName  ; MACHINE_CONVERSION
	dw RaiseBodyHeatName      ; RAISE_BODY_HEAT
	dw FollowWindName         ; FOLLOW_WIND
	dw PowerOfKaishinName     ; POWER_OF_KAISHIN
	dw DragonCaptureJarName   ; DRAGON_CAPTURE_JAR
	dw ForestName             ; FOREST
	dw WastelandName          ; WASTELAND
	dw MountainName           ; MOUNTAIN
	dw SogenName              ; SOGEN
	dw UmiName                ; UMI
	dw YamiName               ; YAMI
	dw DarkHoleName           ; DARK_HOLE
	dw RaigekiName            ; RAIGEKI
	dw MooyanCurryName        ; MOOYAN_CURRY
	dw RedMedicineName        ; RED_MEDICINE
	dw GoblinsRemedyName      ; GOBLINS_REMEDY
	dw SoulOfThePureName      ; SOUL_OF_THE_PURE
	dw DianKetoTheCureName    ; DIAN_KETO_THE_CURE
	dw SparksName             ; SPARKS
	dw HinotamaName           ; HINOTAMA
	dw FinalFlameName         ; FINAL_FLAME
	dw OokaziName             ; OOKAZI
	dw TremendousFireName     ; TREMENDOUS_FIRE
	dw SwordsRevealingName    ; SWORDS_REVEALING
	dw SpellbindCircleName    ; SPELLBIND_CIRCLE
	dw DarkPierceLightName    ; DARK_PIERCE_LIGHT
	dw YaranzoName            ; YARANZO
	dw KananTheSwordName      ; KANAN_THE_SWORD
	dw TakriminosName         ; TAKRIMINOS
	dw StuffedAnimalName      ; STUFFED_ANIMAL
	dw MegasonicEyeName       ; MEGASONIC_EYE
	dw SuperWarLionName       ; SUPER_WAR_LION
	dw YamadronName           ; YAMADRON
	dw SeiyaryuName           ; SEIYARYU
	dw ThreeLeggedZombiesName ; THREE_LEGGED_ZOMBIES
	dw ZeraTheMantName        ; ZERA_THE_MANT
	dw FlyingPenguinName      ; FLYING_PENGUIN
	dw MillenniumShieldName   ; MILLENNIUM_SHIELD
	dw FairysGiftName         ; FAIRYS_GIFT
	dw BLusterSoldierName     ; B_LUSTER_SOLDIER
	dw FiendsMirrorName       ; FIENDS_MIRROR
	dw InvalidCardName        ; INVALID_CARD
	dw InvalidCardName + (InvalidCardName.end - InvalidCardName)
