CardDescriptions::
	table_width 2
	dw BEyeWhiteDragonDescription    ; B_EYE_WHITE_DRAGON
	dw MysticalElfDescription        ; MYSTICAL_ELF
	dw HitotsuMeGiantDescription     ; HITOTSU_ME_GIANT
	dw BabyDragonDescription         ; BABY_DRAGON
	dw RyuKishinDescription          ; RYU_KISHIN
	dw FeralImpDescription           ; FERAL_IMP
	dw WingedDragon1Description      ; WINGED_DRAGON_1
	dw MushroomManDescription        ; MUSHROOM_MAN
	dw ShadowSpecterDescription      ; SHADOW_SPECTER
	dw BlacklandDragonDescription    ; BLACKLAND_DRAGON
	dw SwordArmDragonDescription     ; SWORD_ARM_DRAGON
	dw SwampBattleguardDescription   ; SWAMP_BATTLEGUARD
	dw TyhoneDescription             ; TYHONE
	dw BattleSteerDescription        ; BATTLE_STEER
	dw FlameSwordsmanDescription     ; FLAME_SWORDSMAN
	dw TimeWizardDescription         ; TIME_WIZARD
	dw RLegOfForbiddenDescription    ; R_LEG_OF_FORBIDDEN
	dw LLegOfForbiddenDescription    ; L_LEG_OF_FORBIDDEN
	dw RArmOfForbiddenDescription    ; R_ARM_OF_FORBIDDEN
	dw LArmOfForbiddenDescription    ; L_ARM_OF_FORBIDDEN
	dw ExodiaForbiddenDescription    ; EXODIA_FORBIDDEN
	dw SummonedSkullDescription      ; SUMMONED_SKULL
	dw WickedWormBeastDescription    ; WICKED_WORM_BEAST
	dw SkullServantDescription       ; SKULL_SERVANT
	dw HornImpDescription            ; HORN_IMP
	dw BattleOxDescription           ; BATTLE_OX
	dw BeaverWarriorDescription      ; BEAVER_WARRIOR
	dw RockOgreGrotto1Description    ; ROCK_OGRE_GROTTO1
	dw MountainWarriorDescription    ; MOUNTAIN_WARRIOR
	dw ZombieWarriorDescription      ; ZOMBIE_WARRIOR
	dw KoumoriDragonDescription      ; KOUMORI_DRAGON
	dw TwoHeadedKingRexDescription   ; TWO_HEADED_KING_REX
	dw JudgeManDescription           ; JUDGE_MAN
	dw SaggiTheClownDescription      ; SAGGI_THE_CLOWN
	dw DarkMagicianDescription       ; DARK_MAGICIAN
	dw TheSnakeHairDescription       ; THE_SNAKE_HAIR
	dw GaiaDragonChampDescription    ; GAIA_DRAGON_CHAMP
	dw GaiaFierceKnightDescription   ; GAIA_FIERCE_KNIGHT
	dw CurseOfDragonDescription      ; CURSE_OF_DRAGON
	dw DragonPiperDescription        ; DRAGON_PIPER
	dw CelticGuardianDescription     ; CELTIC_GUARDIAN
	dw IllusionFacelessDescription   ; ILLUSION_FACELESS
	dw KarbonalaWarriorDescription   ; KARBONALA_WARRIOR
	dw RogueDollDescription          ; ROGUE_DOLL
	dw WattkidDescription            ; WATTKID
	dw GrifforeDescription           ; GRIFFORE
	dw TorikeDescription             ; TORIKE
	dw SanganDescription             ; SANGAN
	dw BigInsectDescription          ; BIG_INSECT
	dw BasicInsectDescription        ; BASIC_INSECT
	dw ArmoredLizardDescription      ; ARMORED_LIZARD
	dw HerculesBeetleDescription     ; HERCULES_BEETLE
	dw KillerNeedleDescription       ; KILLER_NEEDLE
	dw GokiboreDescription           ; GOKIBORE
	dw GiantFleaDescription          ; GIANT_FLEA
	dw LarvaeMothDescription         ; LARVAE_MOTH
	dw GreatMothDescription          ; GREAT_MOTH
	dw KuribohDescription            ; KURIBOH
	dw MammothGraveyardDescription   ; MAMMOTH_GRAVEYARD
	dw GreatWhiteDescription         ; GREAT_WHITE
	dw WolfDescription               ; WOLF
	dw HarpieLadyDescription         ; HARPIE_LADY
	dw HarpieLadySisterDescription   ; HARPIE_LADY_SISTER
	dw TigerAxeDescription           ; TIGER_AXE
	dw SilverFangDescription         ; SILVER_FANG
	dw KojikocyDescription           ; KOJIKOCY
	dw PerfectGreatMothDescription   ; PERFECT_GREAT_MOTH
	dw GaroozisDescription           ; GAROOZIS
	dw ThousandDragonDescription     ; THOUSAND_DRAGON
	dw FiendKrakenDescription        ; FIEND_KRAKEN
	dw JellyfishDescription          ; JELLYFISH
	dw CocoonEvolutionDescription    ; COCOON_EVOLUTION
	dw KairyuShinDescription         ; KAIRYU_SHIN
	dw SoldierOfStoneDescription     ; SOLDIER_OF_STONE
	dw ManEatingPlantDescription     ; MAN_EATING_PLANT
	dw KrokodilusDescription         ; KROKODILUS
	dw GrapplerDescription           ; GRAPPLER
	dw AxeRaiderDescription          ; AXE_RAIDER
	dw MegazowlerDescription         ; MEGAZOWLER
	dw UrabyDescription              ; URABY
	dw CrawlingDragon2Description    ; CRAWLING_DRAGON_2
	dw RedEyesBDragonDescription     ; RED_EYES_B_DRAGON
	dw CastleOfDarkDescription       ; CASTLE_OF_DARK
	dw ReaperOfTheCardDescription    ; REAPER_OF_THE_CARD
	dw KingOfYamimakaiDescription    ; KING_OF_YAMIMAKAI
	dw BaroxDescription              ; BAROX
	dw DarkChimeraDescription        ; DARK_CHIMERA
	dw MetalGuardianDescription      ; METAL_GUARDIAN
	dw CatapultTurtleDescription     ; CATAPULT_TURTLE
	dw GyakutennoMegamiDescription   ; GYAKUTENNO_MEGAMI
	dw MysticHorsemanDescription     ; MYSTIC_HORSEMAN
	dw RabidHorsemanDescription      ; RABID_HORSEMAN
	dw ZankiDescription              ; ZANKI
	dw CrawlingDragonDescription     ; CRAWLING_DRAGON
	dw CrassClownDescription         ; CRASS_CLOWN
	dw ArmoredZombieDescription      ; ARMORED_ZOMBIE
	dw DragonZombieDescription       ; DRAGON_ZOMBIE
	dw ClownZombieDescription        ; CLOWN_ZOMBIE
	dw PumpkingTheKingDescription    ; PUMPKING_THE_KING
	dw BattleWarriorDescription      ; BATTLE_WARRIOR
	dw WingsOfFlameDescription       ; WINGS_OF_FLAME
	dw MaskOfDarknessDescription     ; MASK_OF_DARKNESS
	dw JobChangeMirrorDescription    ; JOB_CHANGE_MIRROR
	dw CurtainOfDarkDescription      ; CURTAIN_OF_DARK
	dw TomozaurusDescription         ; TOMOZAURUS
	dw SpiritOfTheWindDescription    ; SPIRIT_OF_THE_WIND
	dw KageningenDescription         ; KAGENINGEN
	dw GraveyardAndHandDescription   ; GRAVEYARD_AND_HAND
	dw GoddessThirdEyeDescription    ; GODDESS_THIRD_EYE
	dw HeroOfTheEastDescription      ; HERO_OF_THE_EAST
	dw DomaTheAngelDescription       ; DOMA_THE_ANGEL
	dw ThatWhichFeedsDescription     ; THAT_WHICH_FEEDS
	dw DarkGrayDescription           ; DARK_GRAY
	dw WhiteMagicalHatDescription    ; WHITE_MAGICAL_HAT
	dw KamionwizardDescription       ; KAMIONWIZARD
	dw NightmareScorpionDescription  ; NIGHTMARE_SCORPION
	dw SpiritOfTheBookDescription    ; SPIRIT_OF_THE_BOOK
	dw SupporterShadowsDescription   ; SUPPORTER_SHADOWS
	dw TrialOfNightmareDescription   ; TRIAL_OF_NIGHTMARE
	dw DreamClownDescription         ; DREAM_CLOWN
	dw SleepingLionDescription       ; SLEEPING_LION
	dw YamatanoScrollDescription     ; YAMATANO_SCROLL
	dw DarkPlantDescription          ; DARK_PLANT
	dw AncientToolDescription        ; ANCIENT_TOOL
	dw FaithBirdDescription          ; FAITH_BIRD
	dw OrionTheBattleDescription     ; ORION_THE_BATTLE
	dw AnsatsuDescription            ; ANSATSU
	dw LamoonDescription             ; LAMOON
	dw NemurikoDescription           ; NEMURIKO
	dw WeatherControlDescription     ; WEATHER_CONTROL
	dw OctoberserDescription         ; OCTOBERSER
	dw The13thGraveDescription       ; THE_13TH_GRAVE
	dw CharubinTheFireDescription    ; CHARUBIN_THE_FIRE
	dw MysticalCaptureDescription    ; MYSTICAL_CAPTURE
	dw FiendsHandDescription         ; FIENDS_HAND
	dw WittyPhantomDescription       ; WITTY_PHANTOM
	dw MysteryHandDescription        ; MYSTERY_HAND
	dw DragonStatueDescription       ; DRAGON_STATUE
	dw BEyedSilZombieDescription     ; B_EYED_SIL_ZOMBIE
	dw ToadMasterDescription         ; TOAD_MASTER
	dw SpikedSnailDescription        ; SPIKED_SNAIL
	dw FlameManipulatorDescription   ; FLAME_MANIPULATOR
	dw NecrolancerDescription        ; NECROLANCER
	dw DjinnTheWatcherDescription    ; DJINN_THE_WATCHER
	dw BewitchingPhantomDescription  ; BEWITCHING_PHANTOM
	dw TempleOfSkullsDescription     ; TEMPLE_OF_SKULLS
	dw MonsterEggDescription         ; MONSTER_EGG
	dw ShadowWhoControlDescription   ; SHADOW_WHO_CONTROL
	dw LordOfTheLampDescription      ; LORD_OF_THE_LAMP
	dw AkihironDescription           ; AKIHIRON
	dw RhaimundosRedDescription      ; RHAIMUNDOS_RED
	dw MeltingRedShadowDescription   ; MELTING_RED_SHADOW
	dw DokuroizoTheGrimDescription   ; DOKUROIZO_THE_GRIM
	dw FireReaperDescription         ; FIRE_REAPER
	dw LarvasDescription             ; LARVAS
	dw HardArmorDescription          ; HARD_ARMOR
	dw FiregrassDescription          ; FIREGRASS
	dw ManEaterDescription           ; MAN_EATER
	dw DigBeakDescription            ; DIG_BEAK
	dw MWarrior1Description          ; M_WARRIOR_1
	dw MWarrior2Description          ; M_WARRIOR_2
	dw TaintedWisdomDescription      ; TAINTED_WISDOM
	dw LisarkDescription             ; LISARK
	dw LordOfZemiaDescription        ; LORD_OF_ZEMIA
	dw TheJudgementHandDescription   ; THE_JUDGEMENT_HAND
	dw MysteriousPuppetDescription   ; MYSTERIOUS_PUPPET
	dw AncientJarDescription         ; ANCIENT_JAR
	dw DarkfireDragonDescription     ; DARKFIRE_DRAGON
	dw DarkKingAbyssDescription      ; DARK_KING_ABYSS
	dw SpiritOfTheHarpDescription    ; SPIRIT_OF_THE_HARP
	dw BigEyeDescription             ; BIG_EYE
	dw ArmaillDescription            ; ARMAILL
	dw DarkPrisonerDescription       ; DARK_PRISONER
	dw HurricailDescription          ; HURRICAIL
	dw AncientBrainDescription       ; ANCIENT_BRAIN
	dw FireEyeDescription            ; FIRE_EYE
	dw MonsturtleDescription         ; MONSTURTLE
	dw ClawReacherDescription        ; CLAW_REACHER
	dw PhantomDewanDescription       ; PHANTOM_DEWAN
	dw ArlownayDescription           ; ARLOWNAY
	dw DarkShadeDescription          ; DARK_SHADE
	dw MaskedClownDescription        ; MASKED_CLOWN
	dw LuckyTrinketDescription       ; LUCKY_TRINKET
	dw GeninDescription              ; GENIN
	dw EyearmorDescription           ; EYEARMOR
	dw FiendReflection2Description   ; FIEND_REFLECTION2
	dw GateDeegDescription           ; GATE_DEEG
	dw SyncharDescription            ; SYNCHAR
	dw FusionistDescription          ; FUSIONIST
	dw AkakieisuDescription          ; AKAKIEISU
	dw LalaLiOonDescription          ; LALA_LI_OON
	dw KeyMaceDescription            ; KEY_MACE
	dw TurtleTigerDescription        ; TURTLE_TIGER
	dw TerraTheTerribleDescription   ; TERRA_THE_TERRIBLE
	dw DoronDescription              ; DORON
	dw ArmaKnightDescription         ; ARMA_KNIGHT
	dw MechMoleZombieDescription     ; MECH_MOLE_ZOMBIE
	dw HappyLoverDescription         ; HAPPY_LOVER
	dw PenguinKnightDescription      ; PENGUIN_KNIGHT
	dw PetitDragonDescription        ; PETIT_DRAGON
	dw FrenziedPandaDescription      ; FRENZIED_PANDA
	dw ArchfiendMarmotDescription    ; ARCHFIEND_MARMOT
	dw PhantomGhostDescription       ; PHANTOM_GHOST
	dw MabarrelDescription           ; MABARREL
	dw DoroverDescription            ; DOROVER
	dw TwinLongRods1Description      ; TWIN_LONG_RODS_1
	dw DrollBirdDescription          ; DROLL_BIRD
	dw PetitAngelDescription         ; PETIT_ANGEL
	dw WingedCleaverDescription      ; WINGED_CLEAVER
	dw HinotamaSoulDescription       ; HINOTAMA_SOUL
	dw ThunderKidDescription         ; THUNDER_KID
	dw MeotokoDescription            ; MEOTOKO
	dw AquaMadoorDescription         ; AQUA_MADOOR
	dw KagemushaBlueDescription      ; KAGEMUSHA_BLUE
	dw FlameGhostDescription         ; FLAME_GHOST
	dw DryadDescription              ; DRYAD
	dw BSkullDragonDescription       ; B_SKULL_DRAGON
	dw TwoMouthDarkrulerDescription  ; TWO_MOUTH_DARKRULER
	dw SolitudeDescription           ; SOLITUDE
	dw MaskedSorcererDescription     ; MASKED_SORCERER
	dw KumootokoDescription          ; KUMOOTOKO
	dw MidnightFiendDescription      ; MIDNIGHT_FIEND
	dw RoarOceanSnakeDescription     ; ROAR_OCEAN_SNAKE
	dw TrapMasterDescription         ; TRAP_MASTER
	dw FiendSwordDescription         ; FIEND_SWORD
	dw SkullStalkerDescription       ; SKULL_STALKER
	dw HitodenchakDescription        ; HITODENCHAK
	dw WoodRemainsDescription        ; WOOD_REMAINS
	dw HourglassOfLifeDescription    ; HOURGLASS_OF_LIFE
	dw RareFishDescription           ; RARE_FISH
	dw WoodClownDescription          ; WOOD_CLOWN
	dw MadjinnGunnDescription        ; MADJINN_GUNN
	dw DarkTitanTerrorDescription    ; DARK_TITAN_TERROR
	dw BeautifulHeadhuntDescription  ; BEAUTIFUL_HEADHUNT
	dw WodanTheResidentDescription   ; WODAN_THE_RESIDENT
	dw GuardianLabyrinthDescription  ; GUARDIAN_LABYRINTH
	dw HaniwaDescription             ; HANIWA
	dw YashinokiDescription          ; YASHINOKI
	dw VishwarRandiDescription       ; VISHWAR_RANDI
	dw TheDrdekDescription           ; THE_DRDEK
	dw DAssailantDescription         ; D_ASSAILANT
	dw CandleOfFateDescription       ; CANDLE_OF_FATE
	dw WaterElementDescription       ; WATER_ELEMENT
	dw DissolverockDescription       ; DISSOLVEROCK
	dw MedaBatDescription            ; MEDA_BAT
	dw OneWhoHuntsSoulDescription    ; ONE_WHO_HUNTS_SOUL
	dw RootWaterDescription          ; ROOT_WATER
	dw MasterAndExpertDescription    ; MASTER_AND_EXPERT
	dw WaterOmoticsDescription       ; WATER_OMOTICS
	dw HyoDescription                ; HYO
	dw EnchantingMermaidDescription  ; ENCHANTING_MERMAID
	dw Nekogal1Description           ; NEKOGAL_1
	dw AngelwitchDescription         ; ANGELWITCH
	dw EmbryonicBeastDescription     ; EMBRYONIC_BEAST
	dw PreventRatDescription         ; PREVENT_RAT
	dw DdWarriorDescription          ; DD_WARRIOR
	dw StoneArmadillerDescription    ; STONE_ARMADILLER
	dw BeastkingOfSwampDescription   ; BEASTKING_OF_SWAMP
	dw AncientSorcererDescription    ; ANCIENT_SORCERER
	dw LunarQueenElzaimDescription   ; LUNAR_QUEEN_ELZAIM
	dw ArchfiendMirrorDescription    ; ARCHFIEND_MIRROR
	dw SwordsmanOfAileDescription    ; SWORDSMAN_OF_AILE
	dw RockOgreGrotto2Description    ; ROCK_OGRE_GROTTO2
	dw WingEggElfDescription         ; WING_EGG_ELF
	dw FuriousSeaKingDescription     ; FURIOUS_SEA_KING
	dw PrincessTsurugiDescription    ; PRINCESS_TSURUGI
	dw UnknownWarriorDescription     ; UNKNOWN_WARRIOR
	dw SectarianSecretDescription    ; SECTARIAN_SECRET
	dw VersagoDestroyerDescription   ; VERSAGO_DESTROYER
	dw WethaDescription              ; WETHA
	dw MegirusLightDescription       ; MEGIRUS_LIGHT
	dw MavelusDescription            ; MAVELUS
	dw AncientTreeDescription        ; ANCIENT_TREE
	dw GreenPhantomKingDescription   ; GREEN_PHANTOM_KING
	dw GroundAttackerDescription     ; GROUND_ATTACKER
	dw RayAndTemperatureDescription  ; RAY_AND_TEMPERATURE
	dw GorgonEggDescription          ; GORGON_EGG
	dw PetitMothDescription          ; PETIT_MOTH
	dw KingFogDescription            ; KING_FOG
	dw ProtectorThroneDescription    ; PROTECTOR_THRONE
	dw MysticClownDescription        ; MYSTIC_CLOWN
	dw MysticalSheep2Description     ; MYSTICAL_SHEEP_2
	dw HolograhDescription           ; HOLOGRAH
	dw TaoTheChanterDescription      ; TAO_THE_CHANTER
	dw SerpentMarauderDescription    ; SERPENT_MARAUDER
	dw GatekeeperDescription         ; GATEKEEPER
	dw OgreOfTheBlackDescription     ; OGRE_OF_THE_BLACK
	dw DarkArtistDescription         ; DARK_ARTIST
	dw ChangeSlimeDescription        ; CHANGE_SLIME
	dw MoonEnvoyDescription          ; MOON_ENVOY
	dw FireyarouDescription          ; FIREYAROU
	dw PsychicKappaDescription       ; PSYCHIC_KAPPA
	dw MasakiTheLegendDescription    ; MASAKI_THE_LEGEND
	dw DragonessWickedDescription    ; DRAGONESS_WICKED
	dw BioPlantDescription           ; BIO_PLANT
	dw OneEyedShieldDescription      ; ONE_EYED_SHIELD
	dw CyberSoldierDarkDescription   ; CYBER_SOLDIER_DARK
	dw DragonErsatzHeadDescription   ; DRAGON_ERSATZ_HEAD
	dw SonicMaidDescription          ; SONIC_MAID
	dw KuramaDescription             ; KURAMA
	dw LegendarySwordDescription     ; LEGENDARY_SWORD
	dw SwordOfDarkDescription        ; SWORD_OF_DARK
	dw DarkEnergyDescription         ; DARK_ENERGY
	dw AxeOfDespairDescription       ; AXE_OF_DESPAIR
	dw LazerCannonArmorDescription   ; LAZER_CANNON_ARMOR
	dw InsectArmorLaserDescription   ; INSECT_ARMOR_LASER
	dw ElfsLightDescription          ; ELFS_LIGHT
	dw BeastFangsDescription         ; BEAST_FANGS
	dw SteelShellDescription         ; STEEL_SHELL
	dw VileGermsDescription          ; VILE_GERMS
	dw BlackPendantDescription       ; BLACK_PENDANT
	dw SilverBowAndArrowDescription  ; SILVER_BOW_AND_ARROW
	dw HornOfLightDescription        ; HORN_OF_LIGHT
	dw HornOfUnicornDescription      ; HORN_OF_UNICORN
	dw DragonTreasureDescription     ; DRAGON_TREASURE
	dw ElectroWhipDescription        ; ELECTRO_WHIP
	dw CyberShieldDescription        ; CYBER_SHIELD
	dw ElegantEgotistDescription     ; ELEGANT_EGOTIST
	dw MysticalMoonDescription       ; MYSTICAL_MOON
	dw StopDefenseDescription        ; STOP_DEFENSE
	dw MalevolentNuzzlerDescription  ; MALEVOLENT_NUZZLER
	dw VioletCrystalDescription      ; VIOLET_CRYSTAL
	dw BookOfSecretArtDescription    ; BOOK_OF_SECRET_ART
	dw InvigorationDescription       ; INVIGORATION
	dw MachineConversionDescription  ; MACHINE_CONVERSION
	dw RaiseBodyHeatDescription      ; RAISE_BODY_HEAT
	dw FollowWindDescription         ; FOLLOW_WIND
	dw PowerOfKaishinDescription     ; POWER_OF_KAISHIN
	dw DragonCaptureJarDescription   ; DRAGON_CAPTURE_JAR
	dw ForestDescription             ; FOREST
	dw WastelandDescription          ; WASTELAND
	dw MountainDescription           ; MOUNTAIN
	dw SogenDescription              ; SOGEN
	dw UmiDescription                ; UMI
	dw YamiDescription               ; YAMI
	dw DarkHoleDescription           ; DARK_HOLE
	dw RaigekiDescription            ; RAIGEKI
	dw MooyanCurryDescription        ; MOOYAN_CURRY
	dw RedMedicineDescription        ; RED_MEDICINE
	dw GoblinsRemedyDescription      ; GOBLINS_REMEDY
	dw SoulOfThePureDescription      ; SOUL_OF_THE_PURE
	dw DianKetoTheCureDescription    ; DIAN_KETO_THE_CURE
	dw SparksDescription             ; SPARKS
	dw HinotamaDescription           ; HINOTAMA
	dw FinalFlameDescription         ; FINAL_FLAME
	dw OokaziDescription             ; OOKAZI
	dw TremendousFireDescription     ; TREMENDOUS_FIRE
	dw SwordsRevealingDescription    ; SWORDS_REVEALING
	dw SpellbindCircleDescription    ; SPELLBIND_CIRCLE
	dw DarkPierceLightDescription    ; DARK_PIERCE_LIGHT
	dw YaranzoDescription            ; YARANZO
	dw KananTheSwordDescription      ; KANAN_THE_SWORD
	dw TakriminosDescription         ; TAKRIMINOS
	dw StuffedAnimalDescription      ; STUFFED_ANIMAL
	dw MegasonicEyeDescription       ; MEGASONIC_EYE
	dw SuperWarLionDescription       ; SUPER_WAR_LION
	dw YamadronDescription           ; YAMADRON
	dw SeiyaryuDescription           ; SEIYARYU
	dw ThreeLeggedZombiesDescription ; THREE_LEGGED_ZOMBIES
	dw ZeraTheMantDescription        ; ZERA_THE_MANT
	dw FlyingPenguinDescription      ; FLYING_PENGUIN
	dw MillenniumShieldDescription   ; MILLENNIUM_SHIELD
	dw FairysGiftDescription         ; FAIRYS_GIFT
	dw BLusterSoldierDescription     ; B_LUSTER_SOLDIER
	dw FiendsMirrorDescription       ; FIENDS_MIRROR
	assert_table_length NUM_CARDS
