	const_def
	const B_EYE_WHITE_DRAGON   ; $000
	const MYSTICAL_ELF         ; $001
	const HITOTSU_ME_GIANT     ; $002
	const BABY_DRAGON          ; $003
	const RYU_KISHIN           ; $004
	const FERAL_IMP            ; $005
	const WINGED_DRAGON_1      ; $006
	const MUSHROOM_MAN         ; $007
	const SHADOW_SPECTER       ; $008
	const BLACKLAND_DRAGON     ; $009
	const SWORD_ARM_DRAGON     ; $00a
	const SWAMP_BATTLEGUARD    ; $00b
	const TYHONE               ; $00c
	const BATTLE_STEER         ; $00d
	const FLAME_SWORDSMAN      ; $00e
	const TIME_WIZARD          ; $00f
	const R_LEG_OF_FORBIDDEN   ; $010
	const L_LEG_OF_FORBIDDEN   ; $011
	const R_ARM_OF_FORBIDDEN   ; $012
	const L_ARM_OF_FORBIDDEN   ; $013
	const EXODIA_FORBIDDEN     ; $014
	const SUMMONED_SKULL       ; $015
	const WICKED_WORM_BEAST    ; $016
	const SKULL_SERVANT        ; $017
	const HORN_IMP             ; $018
	const BATTLE_OX            ; $019
	const BEAVER_WARRIOR       ; $01a
	const ROCK_OGRE_GROTTO1    ; $01b
	const MOUNTAIN_WARRIOR     ; $01c
	const ZOMBIE_WARRIOR       ; $01d
	const KOUMORI_DRAGON       ; $01e
	const TWO_HEADED_KING_REX  ; $01f
	const JUDGE_MAN            ; $020
	const SAGGI_THE_CLOWN      ; $021
	const DARK_MAGICIAN        ; $022
	const THE_SNAKE_HAIR       ; $023
	const GAIA_DRAGON_CHAMP    ; $024
	const GAIA_FIERCE_KNIGHT   ; $025
	const CURSE_OF_DRAGON      ; $026
	const DRAGON_PIPER         ; $027
	const CELTIC_GUARDIAN      ; $028
	const ILLUSION_FACELESS    ; $029
	const KARBONALA_WARRIOR    ; $02a
	const ROGUE_DOLL           ; $02b
	const WATTKID              ; $02c
	const GRIFFORE             ; $02d
	const TORIKE               ; $02e
	const SANGAN               ; $02f
	const BIG_INSECT           ; $030
	const BASIC_INSECT         ; $031
	const ARMORED_LIZARD       ; $032
	const HERCULES_BEETLE      ; $033
	const KILLER_NEEDLE        ; $034
	const GOKIBORE             ; $035
	const GIANT_FLEA           ; $036
	const LARVAE_MOTH          ; $037
	const GREAT_MOTH           ; $038
	const KURIBOH              ; $039
	const MAMMOTH_GRAVEYARD    ; $03a
	const GREAT_WHITE          ; $03b
	const WOLF                 ; $03c
	const HARPIE_LADY          ; $03d
	const HARPIE_LADY_SISTER   ; $03e
	const TIGER_AXE            ; $03f
	const SILVER_FANG          ; $040
	const KOJIKOCY             ; $041
	const PERFECT_GREAT_MOTH   ; $042
	const GAROOZIS             ; $043
	const THOUSAND_DRAGON      ; $044
	const FIEND_KRAKEN         ; $045
	const JELLYFISH            ; $046
	const COCOON_EVOLUTION     ; $047
	const KAIRYU_SHIN          ; $048
	const SOLDIER_OF_STONE     ; $049
	const MAN_EATING_PLANT     ; $04a
	const KROKODILUS           ; $04b
	const GRAPPLER             ; $04c
	const AXE_RAIDER           ; $04d
	const MEGAZOWLER           ; $04e
	const URABY                ; $04f
	const CRAWLING_DRAGON_2    ; $050
	const RED_EYES_B_DRAGON    ; $051
	const CASTLE_OF_DARK       ; $052
	const REAPER_OF_THE_CARD   ; $053
	const KING_OF_YAMIMAKAI    ; $054
	const BAROX                ; $055
	const DARK_CHIMERA         ; $056
	const METAL_GUARDIAN       ; $057
	const CATAPULT_TURTLE      ; $058
	const GYAKUTENNO_MEGAMI    ; $059
	const MYSTIC_HORSEMAN      ; $05a
	const RABID_HORSEMAN       ; $05b
	const ZANKI                ; $05c
	const CRAWLING_DRAGON      ; $05d
	const CRASS_CLOWN          ; $05e
	const ARMORED_ZOMBIE       ; $05f
	const DRAGON_ZOMBIE        ; $060
	const CLOWN_ZOMBIE         ; $061
	const PUMPKING_THE_KING    ; $062
	const BATTLE_WARRIOR       ; $063
	const WINGS_OF_FLAME       ; $064
	const MASK_OF_DARKNESS     ; $065
	const JOB_CHANGE_MIRROR    ; $066
	const CURTAIN_OF_DARK      ; $067
	const TOMOZAURUS           ; $068
	const SPIRIT_OF_THE_WIND   ; $069
	const KAGENINGEN           ; $06a
	const GRAVEYARD_AND_HAND   ; $06b
	const GODDESS_THIRD_EYE    ; $06c
	const HERO_OF_THE_EAST     ; $06d
	const DOMA_THE_ANGEL       ; $06e
	const THAT_WHICH_FEEDS     ; $06f
	const DARK_GRAY            ; $070
	const WHITE_MAGICAL_HAT    ; $071
	const KAMIONWIZARD         ; $072
	const NIGHTMARE_SCORPION   ; $073
	const SPIRIT_OF_THE_BOOK   ; $074
	const SUPPORTER_SHADOWS    ; $075
	const TRIAL_OF_NIGHTMARE   ; $076
	const DREAM_CLOWN          ; $077
	const SLEEPING_LION        ; $078
	const YAMATANO_SCROLL      ; $079
	const DARK_PLANT           ; $07a
	const ANCIENT_TOOL         ; $07b
	const FAITH_BIRD           ; $07c
	const ORION_THE_BATTLE     ; $07d
	const ANSATSU              ; $07e
	const LAMOON               ; $07f
	const NEMURIKO             ; $080
	const WEATHER_CONTROL      ; $081
	const OCTOBERSER           ; $082
	const THE_13TH_GRAVE       ; $083
	const CHARUBIN_THE_FIRE    ; $084
	const MYSTICAL_CAPTURE     ; $085
	const FIENDS_HAND          ; $086
	const WITTY_PHANTOM        ; $087
	const MYSTERY_HAND         ; $088
	const DRAGON_STATUE        ; $089
	const B_EYED_SIL_ZOMBIE    ; $08a
	const TOAD_MASTER          ; $08b
	const SPIKED_SNAIL         ; $08c
	const FLAME_MANIPULATOR    ; $08d
	const NECROLANCER          ; $08e
	const DJINN_THE_WATCHER    ; $08f
	const BEWITCHING_PHANTOM   ; $090
	const TEMPLE_OF_SKULLS     ; $091
	const MONSTER_EGG          ; $092
	const SHADOW_WHO_CONTROL   ; $093
	const LORD_OF_THE_LAMP     ; $094
	const AKIHIRON             ; $095
	const RHAIMUNDOS_RED       ; $096
	const MELTING_RED_SHADOW   ; $097
	const DOKUROIZO_THE_GRIM   ; $098
	const FIRE_REAPER          ; $099
	const LARVAS               ; $09a
	const HARD_ARMOR           ; $09b
	const FIREGRASS            ; $09c
	const MAN_EATER            ; $09d
	const DIG_BEAK             ; $09e
	const M_WARRIOR_1          ; $09f
	const M_WARRIOR_2          ; $0a0
	const TAINTED_WISDOM       ; $0a1
	const LISARK               ; $0a2
	const LORD_OF_ZEMIA        ; $0a3
	const THE_JUDGEMENT_HAND   ; $0a4
	const MYSTERIOUS_PUPPET    ; $0a5
	const ANCIENT_JAR          ; $0a6
	const DARKFIRE_DRAGON      ; $0a7
	const DARK_KING_ABYSS      ; $0a8
	const SPIRIT_OF_THE_HARP   ; $0a9
	const BIG_EYE              ; $0aa
	const ARMAILL              ; $0ab
	const DARK_PRISONER        ; $0ac
	const HURRICAIL            ; $0ad
	const ANCIENT_BRAIN        ; $0ae
	const FIRE_EYE             ; $0af
	const MONSTURTLE           ; $0b0
	const CLAW_REACHER         ; $0b1
	const PHANTOM_DEWAN        ; $0b2
	const ARLOWNAY             ; $0b3
	const DARK_SHADE           ; $0b4
	const MASKED_CLOWN         ; $0b5
	const LUCKY_TRINKET        ; $0b6
	const GENIN                ; $0b7
	const EYEARMOR             ; $0b8
	const FIEND_REFLECTION2    ; $0b9
	const GATE_DEEG            ; $0ba
	const SYNCHAR              ; $0bb
	const FUSIONIST            ; $0bc
	const AKAKIEISU            ; $0bd
	const LALA_LI_OON          ; $0be
	const KEY_MACE             ; $0bf
	const TURTLE_TIGER         ; $0c0
	const TERRA_THE_TERRIBLE   ; $0c1
	const DORON                ; $0c2
	const ARMA_KNIGHT          ; $0c3
	const MECH_MOLE_ZOMBIE     ; $0c4
	const HAPPY_LOVER          ; $0c5
	const PENGUIN_KNIGHT       ; $0c6
	const PETIT_DRAGON         ; $0c7
	const FRENZIED_PANDA       ; $0c8
	const ARCHFIEND_MARMOT     ; $0c9
	const PHANTOM_GHOST        ; $0ca
	const MABARREL             ; $0cb
	const DOROVER              ; $0cc
	const TWIN_LONG_RODS_1     ; $0cd
	const DROLL_BIRD           ; $0ce
	const PETIT_ANGEL          ; $0cf
	const WINGED_CLEAVER       ; $0d0
	const HINOTAMA_SOUL        ; $0d1
	const THUNDER_KID          ; $0d2
	const MEOTOKO              ; $0d3
	const AQUA_MADOOR          ; $0d4
	const KAGEMUSHA_BLUE       ; $0d5
	const FLAME_GHOST          ; $0d6
	const DRYAD                ; $0d7
	const B_SKULL_DRAGON       ; $0d8
	const TWO_MOUTH_DARKRULER  ; $0d9
	const SOLITUDE             ; $0da
	const MASKED_SORCERER      ; $0db
	const KUMOOTOKO            ; $0dc
	const MIDNIGHT_FIEND       ; $0dd
	const ROAR_OCEAN_SNAKE     ; $0de
	const TRAP_MASTER          ; $0df
	const FIEND_SWORD          ; $0e0
	const SKULL_STALKER        ; $0e1
	const HITODENCHAK          ; $0e2
	const WOOD_REMAINS         ; $0e3
	const HOURGLASS_OF_LIFE    ; $0e4
	const RARE_FISH            ; $0e5
	const WOOD_CLOWN           ; $0e6
	const MADJINN_GUNN         ; $0e7
	const DARK_TITAN_TERROR    ; $0e8
	const BEAUTIFUL_HEADHUNT   ; $0e9
	const WODAN_THE_RESIDENT   ; $0ea
	const GUARDIAN_LABYRINTH   ; $0eb
	const HANIWA               ; $0ec
	const YASHINOKI            ; $0ed
	const VISHWAR_RANDI        ; $0ee
	const THE_DRDEK            ; $0ef
	const D_ASSAILANT          ; $0f0
	const CANDLE_OF_FATE       ; $0f1
	const WATER_ELEMENT        ; $0f2
	const DISSOLVEROCK         ; $0f3
	const MEDA_BAT             ; $0f4
	const ONE_WHO_HUNTS_SOUL   ; $0f5
	const ROOT_WATER           ; $0f6
	const MASTER_AND_EXPERT    ; $0f7
	const WATER_OMOTICS        ; $0f8
	const HYO                  ; $0f9
	const ENCHANTING_MERMAID   ; $0fa
	const NEKOGAL_1            ; $0fb
	const ANGELWITCH           ; $0fc
	const EMBRYONIC_BEAST      ; $0fd
	const PREVENT_RAT          ; $0fe
	const DD_WARRIOR           ; $0ff
	const STONE_ARMADILLER     ; $100
	const BEASTKING_OF_SWAMP   ; $101
	const ANCIENT_SORCERER     ; $102
	const LUNAR_QUEEN_ELZAIM   ; $103
	const ARCHFIEND_MIRROR     ; $104
	const SWORDSMAN_OF_AILE    ; $105
	const ROCK_OGRE_GROTTO2    ; $106
	const WING_EGG_ELF         ; $107
	const FURIOUS_SEA_KING     ; $108
	const PRINCESS_TSURUGI     ; $109
	const UNKNOWN_WARRIOR      ; $10a
	const SECTARIAN_SECRET     ; $10b
	const VERSAGO_DESTROYER    ; $10c
	const WETHA                ; $10d
	const MEGIRUS_LIGHT        ; $10e
	const MAVELUS              ; $10f
	const ANCIENT_TREE         ; $110
	const GREEN_PHANTOM_KING   ; $111
	const GROUND_ATTACKER      ; $112
	const RAY_AND_TEMPERATURE  ; $113
	const GORGON_EGG           ; $114
	const PETIT_MOTH           ; $115
	const KING_FOG             ; $116
	const PROTECTOR_THRONE     ; $117
	const MYSTIC_CLOWN         ; $118
	const MYSTICAL_SHEEP_2     ; $119
	const HOLOGRAH             ; $11a
	const TAO_THE_CHANTER      ; $11b
	const SERPENT_MARAUDER     ; $11c
	const GATEKEEPER           ; $11d
	const OGRE_OF_THE_BLACK    ; $11e
	const DARK_ARTIST          ; $11f
	const CHANGE_SLIME         ; $120
	const MOON_ENVOY           ; $121
	const FIREYAROU            ; $122
	const PSYCHIC_KAPPA        ; $123
	const MASAKI_THE_LEGEND    ; $124
	const DRAGONESS_WICKED     ; $125
	const BIO_PLANT            ; $126
	const ONE_EYED_SHIELD      ; $127
	const CYBER_SOLDIER_DARK   ; $128
	const DRAGON_ERSATZ_HEAD   ; $129
	const SONIC_MAID           ; $12a
	const KURAMA               ; $12b
	const LEGENDARY_SWORD      ; $12c
	const SWORD_OF_DARK        ; $12d
	const DARK_ENERGY          ; $12e
	const AXE_OF_DESPAIR       ; $12f
	const LAZER_CANNON_ARMOR   ; $130
	const INSECT_ARMOR_LASER   ; $131
	const ELFS_LIGHT           ; $132
	const BEAST_FANGS          ; $133
	const STEEL_SHELL          ; $134
	const VILE_GERMS           ; $135
	const BLACK_PENDANT        ; $136
	const SILVER_BOW_AND_ARROW ; $137
	const HORN_OF_LIGHT        ; $138
	const HORN_OF_UNICORN      ; $139
	const DRAGON_TREASURE      ; $13a
	const ELECTRO_WHIP         ; $13b
	const CYBER_SHIELD         ; $13c
	const ELEGANT_EGOTIST      ; $13d
	const MYSTICAL_MOON        ; $13e
	const STOP_DEFENSE         ; $13f
	const MALEVOLENT_NUZZLER   ; $140
	const VIOLET_CRYSTAL       ; $141
	const BOOK_OF_SECRET_ART   ; $142
	const INVIGORATION         ; $143
	const MACHINE_CONVERSION   ; $144
	const RAISE_BODY_HEAT      ; $145
	const FOLLOW_WIND          ; $146
	const POWER_OF_KAISHIN     ; $147
	const DRAGON_CAPTURE_JAR   ; $148
	const FOREST               ; $149
	const WASTELAND            ; $14a
	const MOUNTAIN             ; $14b
	const SOGEN                ; $14c
	const UMI                  ; $14d
	const YAMI                 ; $14e
	const DARK_HOLE            ; $14f
	const RAIGEKI              ; $150
	const MOOYAN_CURRY         ; $151
	const RED_MEDICINE         ; $152
	const GOBLINS_REMEDY       ; $153
	const SOUL_OF_THE_PURE     ; $154
	const DIAN_KETO_THE_CURE   ; $155
	const SPARKS               ; $156
	const HINOTAMA             ; $157
	const FINAL_FLAME          ; $158
	const OOKAZI               ; $159
	const TREMENDOUS_FIRE      ; $15a
	const SWORDS_REVEALING     ; $15b
	const SPELLBIND_CIRCLE     ; $15c
	const DARK_PIERCE_LIGHT    ; $15d
	const YARANZO              ; $15e
	const KANAN_THE_SWORD      ; $15f
	const TAKRIMINOS           ; $160
	const STUFFED_ANIMAL       ; $161
	const MEGASONIC_EYE        ; $162
	const SUPER_WAR_LION       ; $163
	const YAMADRON             ; $164
	const SEIYARYU             ; $165
	const THREE_LEGGED_ZOMBIES ; $166
	const ZERA_THE_MANT        ; $167
	const FLYING_PENGUIN       ; $168
	const MILLENNIUM_SHIELD    ; $169
	const FAIRYS_GIFT          ; $16a
	const B_LUSTER_SOLDIER     ; $16b
	const FIENDS_MIRROR        ; $16c
DEF NUM_CARDS EQU const_value

	const INVALID_CARD         ; $16d
