	const_def
	const WEEVIL      ; $00
	const MAI         ; $01
	const REX         ; $02
	const MAKO        ; $03
	const YAMI_YUGI   ; $04
	const YUGI   ; $05
	const TEA         ; $06
	const JOEY        ; $07
	const SETO        ; $08
	const MOKUBA      ; $09
	const TRISTAN     ; $0a
	const BAKURA      ; $0b
	const PUPPETEER   ; $0c
	const PANIK       ; $0d
	const BANDIT      ; $0e
	const MAXIMILLION ; $0f
	const SIMON       ; $10
	const EXODIA      ; $11
