DEF DECK_SIZE EQU 40
DEF HAND_SIZE EQU  5

	const_def
	const CARD_LOCATION_0    ; $0
	const CARD_LOCATION_1    ; $1
	const CARD_LOCATION_2    ; $2
	const CARD_LOCATION_HAND ; $3

; Exodia flags
DEF HAS_R_LEG_OF_FORBIDDEN EQU 1 << 0
DEF HAS_L_LEG_OF_FORBIDDEN EQU 1 << 1
DEF HAS_R_ARM_OF_FORBIDDEN EQU 1 << 2
DEF HAS_L_ARM_OF_FORBIDDEN EQU 1 << 3
DEF HAS_EXODIA_FORBIDDEN   EQU 1 << 4


