	const_def
	const EFFECT_00                   ; $00
	const EFFECT_01                   ; $01
	const EFFECT_02                   ; $02
	const EFFECT_FOREST               ; $03
	const EFFECT_WASTELAND            ; $04
	const EFFECT_MOUNTAIN             ; $05
	const EFFECT_SOGEN                ; $06
	const EFFECT_UMI                  ; $07
	const EFFECT_YAMI                 ; $08
	const EFFECT_MOOYAN_CURRY         ; $09
	const EFFECT_RED_MEDICINE         ; $0a
	const EFFECT_GOBLINS_REMEDY       ; $0b
	const EFFECT_SOUL_OF_THE_PURE     ; $0c
	const EFFECT_DIAN_KETO_THE_CURE   ; $0d
	const EFFECT_SPARKS               ; $0e
	const EFFECT_HINOTAMA             ; $0f
	const EFFECT_FINAL_FLAME          ; $10
	const EFFECT_OOKAZI               ; $11
	const EFFECT_TREMENDOUS_FIRE      ; $12
	const EFFECT_DARK_HOLE            ; $13
	const EFFECT_RAIGEKI              ; $14
	const EFFECT_LEGENDARY_SWORD      ; $15
	const EFFECT_SWORD_OF_DARK        ; $16
	const EFFECT_DARK_ENERGY          ; $17
	const EFFECT_AXE_OF_DESPAIR       ; $18
	const EFFECT_LAZER_CANNON_ARMOR   ; $19
	const EFFECT_INSECT_ARMOR_LASER   ; $1a
	const EFFECT_ELFS_LIGHT           ; $1b
	const EFFECT_BEAST_FANGS          ; $1c
	const EFFECT_STEEL_SHELL          ; $1d
	const EFFECT_VILE_GERMS           ; $1e
	const EFFECT_BLACK_PENDANT        ; $1f
	const EFFECT_SILVER_BOW_AND_ARROW ; $20
	const EFFECT_HORN_OF_LIGHT        ; $21
	const EFFECT_HORN_OF_UNICORN      ; $22
	const EFFECT_DRAGON_TREASURE      ; $23
	const EFFECT_ELECTRO_WHIP         ; $24
	const EFFECT_CYBER_SHIELD         ; $25
	const EFFECT_MYSTICAL_MOON        ; $26
	const EFFECT_MALEVOLENT_NUZZLER   ; $27
	const EFFECT_VIOLET_CRYSTAL       ; $28
	const EFFECT_BOOK_OF_SECRET_ART   ; $29
	const EFFECT_INVIGORATION         ; $2a
	const EFFECT_MACHINE_CONVERSION   ; $2b
	const EFFECT_RAISE_BODY_HEAT      ; $2c
	const EFFECT_FOLLOW_WIND          ; $2d
	const EFFECT_POWER_OF_KAISHIN     ; $2e
	const EFFECT_STOP_DEFENSE         ; $2f
	const EFFECT_30                   ; $30
	const EFFECT_DRAGON_CAPTURE_JAR   ; $31
	const EFFECT_32                   ; $32
	const EFFECT_33                   ; $33
	const EFFECT_34                   ; $34
	const EFFECT_ELEGANT_EGOTIST      ; $35
