	dw BANK(@)

	farcall_table_start
	farfunc LoadCardData
	farfunc Func_24024
	farfunc Func_26b89

SECTION "Bank 9@4024", ROMX[$4024], BANK[$9]

Func_24024::
	push af
	push bc
	ld a, [wTempCardID + 0]
	ld c, a
	ld a, [wTempCardID + 1]
	ld b, a
	call LoadCardData
	call GetCardLocationAndIndex
	call Func_24058
	call ApplyFieldBoost
	call ApplyCardLevelBoost
	pop bc
	pop af
	ret

ApplyFieldBoost:
	push af
	ld a, [wActiveField]
	call _ApplyFieldBoost
	pop af
	ret
; 0x24049

SECTION "Bank 9@4058", ROMX[$4058], BANK[$9]

Func_24058:
	push af
	ld a, b
	ld [wLoadedCardLocationIndex], a
	ld a, c
	ld [wLoadedCardLocation], a
	pop af
	ret

LoadCardData:
	push af
	push bc
	push de
	push hl
	ld a, c
	ld [wLoadedCardID + 0], a
	ld a, b
	ld [wLoadedCardID + 1], a
	ld hl, CardTypes
	add hl, bc
	ld a, [hl]
	ld [wLoadedCardType], a
	sla c
	rl b
	ld hl, CardAttacks
	add hl, bc
	ld a, [hli]
	ld d, [hl]
	ld e, a
	ld a, e
	ld [wLoadedCardAtk + 0], a
	ld a, d
	ld [wLoadedCardAtk + 1], a
	ld hl, CardDefenses
	add hl, bc
	ld a, [hli]
	ld d, [hl]
	ld e, a
	ld a, e
	ld [wLoadedCardDef + 0], a
	ld a, d
	ld [wLoadedCardDef + 1], a
	pop hl
	pop de
	pop bc
	pop af
	ret

CardTypes:
	db DRAGON        ; B_EYE_WHITE_DRAGON
	db SPELLCASTER   ; MYSTICAL_ELF
	db BEAST_WARRIOR ; HITOTSU_ME_GIANT
	db DRAGON        ; BABY_DRAGON
	db FIEND         ; RYU_KISHIN
	db FIEND         ; FERAL_IMP
	db DRAGON        ; WINGED_DRAGON_1
	db PLANT         ; MUSHROOM_MAN
	db ZOMBIE        ; SHADOW_SPECTER
	db DRAGON        ; BLACKLAND_DRAGON
	db DINOSAUR      ; SWORD_ARM_DRAGON
	db WARRIOR       ; SWAMP_BATTLEGUARD
	db WINGED_BEAST  ; TYHONE
	db BEAST_WARRIOR ; BATTLE_STEER
	db WARRIOR       ; FLAME_SWORDSMAN
	db SPELLCASTER   ; TIME_WIZARD
	db SPELLCASTER   ; R_LEG_OF_FORBIDDEN
	db SPELLCASTER   ; L_LEG_OF_FORBIDDEN
	db SPELLCASTER   ; R_ARM_OF_FORBIDDEN
	db SPELLCASTER   ; L_ARM_OF_FORBIDDEN
	db SPELLCASTER   ; EXODIA_FORBIDDEN
	db FIEND         ; SUMMONED_SKULL
	db BEAST         ; WICKED_WORM_BEAST
	db ZOMBIE        ; SKULL_SERVANT
	db FIEND         ; HORN_IMP
	db BEAST_WARRIOR ; BATTLE_OX
	db BEAST_WARRIOR ; BEAVER_WARRIOR
	db ROCK          ; ROCK_OGRE_GROTTO1
	db BEAST_WARRIOR ; MOUNTAIN_WARRIOR
	db ZOMBIE        ; ZOMBIE_WARRIOR
	db DRAGON        ; KOUMORI_DRAGON
	db DINOSAUR      ; TWO_HEADED_KING_REX
	db WARRIOR       ; JUDGE_MAN
	db SPELLCASTER   ; SAGGI_THE_CLOWN
	db SPELLCASTER   ; DARK_MAGICIAN
	db ZOMBIE        ; THE_SNAKE_HAIR
	db DRAGON        ; GAIA_DRAGON_CHAMP
	db WARRIOR       ; GAIA_FIERCE_KNIGHT
	db DRAGON        ; CURSE_OF_DRAGON
	db PYRO          ; DRAGON_PIPER
	db WARRIOR       ; CELTIC_GUARDIAN
	db SPELLCASTER   ; ILLUSION_FACELESS
	db WARRIOR       ; KARBONALA_WARRIOR
	db SPELLCASTER   ; ROGUE_DOLL
	db THUNDER       ; WATTKID
	db BEAST         ; GRIFFORE
	db BEAST         ; TORIKE
	db FIEND         ; SANGAN
	db INSECT        ; BIG_INSECT
	db INSECT        ; BASIC_INSECT
	db REPTILE       ; ARMORED_LIZARD
	db INSECT        ; HERCULES_BEETLE
	db INSECT        ; KILLER_NEEDLE
	db INSECT        ; GOKIBORE
	db INSECT        ; GIANT_FLEA
	db INSECT        ; LARVAE_MOTH
	db INSECT        ; GREAT_MOTH
	db FIEND         ; KURIBOH
	db DINOSAUR      ; MAMMOTH_GRAVEYARD
	db FISH          ; GREAT_WHITE
	db BEAST         ; WOLF
	db WINGED_BEAST  ; HARPIE_LADY
	db WINGED_BEAST  ; HARPIE_LADY_SISTER
	db BEAST_WARRIOR ; TIGER_AXE
	db BEAST         ; SILVER_FANG
	db WARRIOR       ; KOJIKOCY
	db INSECT        ; PERFECT_GREAT_MOTH
	db BEAST_WARRIOR ; GAROOZIS
	db DRAGON        ; THOUSAND_DRAGON
	db AQUA          ; FIEND_KRAKEN
	db AQUA          ; JELLYFISH
	db INSECT        ; COCOON_EVOLUTION
	db SEA_SERPENT   ; KAIRYU_SHIN
	db ROCK          ; SOLDIER_OF_STONE
	db PLANT         ; MAN_EATING_PLANT
	db REPTILE       ; KROKODILUS
	db REPTILE       ; GRAPPLER
	db WARRIOR       ; AXE_RAIDER
	db DINOSAUR      ; MEGAZOWLER
	db DINOSAUR      ; URABY
	db DINOSAUR      ; CRAWLING_DRAGON_2
	db DRAGON        ; RED_EYES_B_DRAGON
	db FIEND         ; CASTLE_OF_DARK
	db FIEND         ; REAPER_OF_THE_CARD
	db FIEND         ; KING_OF_YAMIMAKAI
	db FIEND         ; BAROX
	db FIEND         ; DARK_CHIMERA
	db FIEND         ; METAL_GUARDIAN
	db AQUA          ; CATAPULT_TURTLE
	db FAIRY         ; GYAKUTENNO_MEGAMI
	db BEAST         ; MYSTIC_HORSEMAN
	db BEAST_WARRIOR ; RABID_HORSEMAN
	db WARRIOR       ; ZANKI
	db DRAGON        ; CRAWLING_DRAGON
	db FIEND         ; CRASS_CLOWN
	db ZOMBIE        ; ARMORED_ZOMBIE
	db ZOMBIE        ; DRAGON_ZOMBIE
	db ZOMBIE        ; CLOWN_ZOMBIE
	db ZOMBIE        ; PUMPKING_THE_KING
	db WARRIOR       ; BATTLE_WARRIOR
	db PYRO          ; WINGS_OF_FLAME
	db FIEND         ; MASK_OF_DARKNESS
	db FIEND         ; JOB_CHANGE_MIRROR
	db SPELLCASTER   ; CURTAIN_OF_DARK
	db DINOSAUR      ; TOMOZAURUS
	db SPELLCASTER   ; SPIRIT_OF_THE_WIND
	db WARRIOR       ; KAGENINGEN
	db ZOMBIE        ; GRAVEYARD_AND_HAND
	db FAIRY         ; GODDESS_THIRD_EYE
	db WARRIOR       ; HERO_OF_THE_EAST
	db FAIRY         ; DOMA_THE_ANGEL
	db FIEND         ; THAT_WHICH_FEEDS
	db BEAST         ; DARK_GRAY
	db SPELLCASTER   ; WHITE_MAGICAL_HAT
	db SPELLCASTER   ; KAMIONWIZARD
	db INSECT        ; NIGHTMARE_SCORPION
	db WINGED_BEAST  ; SPIRIT_OF_THE_BOOK
	db WARRIOR       ; SUPPORTER_SHADOWS
	db FIEND         ; TRIAL_OF_NIGHTMARE
	db WARRIOR       ; DREAM_CLOWN
	db BEAST         ; SLEEPING_LION
	db DRAGON        ; YAMATANO_SCROLL
	db PLANT         ; DARK_PLANT
	db MACHINE       ; ANCIENT_TOOL
	db WINGED_BEAST  ; FAITH_BIRD
	db FAIRY         ; ORION_THE_BATTLE
	db WARRIOR       ; ANSATSU
	db SPELLCASTER   ; LAMOON
	db SPELLCASTER   ; NEMURIKO
	db FAIRY         ; WEATHER_CONTROL
	db AQUA          ; OCTOBERSER
	db ZOMBIE        ; THE_13TH_GRAVE
	db PYRO          ; CHARUBIN_THE_FIRE
	db FAIRY         ; MYSTICAL_CAPTURE
	db ZOMBIE        ; FIENDS_HAND
	db FIEND         ; WITTY_PHANTOM
	db FIEND         ; MYSTERY_HAND
	db WARRIOR       ; DRAGON_STATUE
	db ZOMBIE        ; B_EYED_SIL_ZOMBIE
	db AQUA          ; TOAD_MASTER
	db INSECT        ; SPIKED_SNAIL
	db SPELLCASTER   ; FLAME_MANIPULATOR
	db SPELLCASTER   ; NECROLANCER
	db SPELLCASTER   ; DJINN_THE_WATCHER
	db SPELLCASTER   ; BEWITCHING_PHANTOM
	db ZOMBIE        ; TEMPLE_OF_SKULLS
	db WARRIOR       ; MONSTER_EGG
	db FIEND         ; SHADOW_WHO_CONTROL
	db FIEND         ; LORD_OF_THE_LAMP
	db AQUA          ; AKIHIRON
	db WARRIOR       ; RHAIMUNDOS_RED
	db AQUA          ; MELTING_RED_SHADOW
	db ZOMBIE        ; DOKUROIZO_THE_GRIM
	db ZOMBIE        ; FIRE_REAPER
	db BEAST         ; LARVAS
	db WARRIOR       ; HARD_ARMOR
	db PLANT         ; FIREGRASS
	db PLANT         ; MAN_EATER
	db BEAST         ; DIG_BEAK
	db WARRIOR       ; M_WARRIOR_1
	db WARRIOR       ; M_WARRIOR_2
	db FIEND         ; TAINTED_WISDOM
	db BEAST         ; LISARK
	db FIEND         ; LORD_OF_ZEMIA
	db WARRIOR       ; THE_JUDGEMENT_HAND
	db WARRIOR       ; MYSTERIOUS_PUPPET
	db ROCK          ; ANCIENT_JAR
	db DRAGON        ; DARKFIRE_DRAGON
	db FIEND         ; DARK_KING_ABYSS
	db FAIRY         ; SPIRIT_OF_THE_HARP
	db FIEND         ; BIG_EYE
	db WARRIOR       ; ARMAILL
	db FIEND         ; DARK_PRISONER
	db SPELLCASTER   ; HURRICAIL
	db FIEND         ; ANCIENT_BRAIN
	db PYRO          ; FIRE_EYE
	db AQUA          ; MONSTURTLE
	db FIEND         ; CLAW_REACHER
	db SPELLCASTER   ; PHANTOM_DEWAN
	db PLANT         ; ARLOWNAY
	db FIEND         ; DARK_SHADE
	db WARRIOR       ; MASKED_CLOWN
	db SPELLCASTER   ; LUCKY_TRINKET
	db SPELLCASTER   ; GENIN
	db WARRIOR       ; EYEARMOR
	db WINGED_BEAST  ; FIEND_REFLECTION2
	db BEAST         ; GATE_DEEG
	db BEAST         ; SYNCHAR
	db BEAST         ; FUSIONIST
	db SPELLCASTER   ; AKAKIEISU
	db THUNDER       ; LALA_LI_OON
	db FAIRY         ; KEY_MACE
	db AQUA          ; TURTLE_TIGER
	db FIEND         ; TERRA_THE_TERRIBLE
	db WARRIOR       ; DORON
	db AQUA          ; ARMA_KNIGHT
	db ZOMBIE        ; MECH_MOLE_ZOMBIE
	db FAIRY         ; HAPPY_LOVER
	db AQUA          ; PENGUIN_KNIGHT
	db DRAGON        ; PETIT_DRAGON
	db BEAST         ; FRENZIED_PANDA
	db BEAST         ; ARCHFIEND_MARMOT
	db ZOMBIE        ; PHANTOM_GHOST
	db FIEND         ; MABARREL
	db AQUA          ; DOROVER
	db AQUA          ; TWIN_LONG_RODS_1
	db WINGED_BEAST  ; DROLL_BIRD
	db FAIRY         ; PETIT_ANGEL
	db INSECT        ; WINGED_CLEAVER
	db PYRO          ; HINOTAMA_SOUL
	db THUNDER       ; THUNDER_KID
	db BEAST         ; MEOTOKO
	db SPELLCASTER   ; AQUA_MADOOR
	db WARRIOR       ; KAGEMUSHA_BLUE
	db ZOMBIE        ; FLAME_GHOST
	db SPELLCASTER   ; DRYAD
	db DRAGON        ; B_SKULL_DRAGON
	db DINOSAUR      ; TWO_MOUTH_DARKRULER
	db BEAST_WARRIOR ; SOLITUDE
	db SPELLCASTER   ; MASKED_SORCERER
	db INSECT        ; KUMOOTOKO
	db FIEND         ; MIDNIGHT_FIEND
	db AQUA          ; ROAR_OCEAN_SNAKE
	db WARRIOR       ; TRAP_MASTER
	db WARRIOR       ; FIEND_SWORD
	db WARRIOR       ; SKULL_STALKER
	db AQUA          ; HITODENCHAK
	db ZOMBIE        ; WOOD_REMAINS
	db FAIRY         ; HOURGLASS_OF_LIFE
	db FISH          ; RARE_FISH
	db WARRIOR       ; WOOD_CLOWN
	db FIEND         ; MADJINN_GUNN
	db FIEND         ; DARK_TITAN_TERROR
	db WARRIOR       ; BEAUTIFUL_HEADHUNT
	db WARRIOR       ; WODAN_THE_RESIDENT
	db WARRIOR       ; GUARDIAN_LABYRINTH
	db ROCK          ; HANIWA
	db PLANT         ; YASHINOKI
	db WARRIOR       ; VISHWAR_RANDI
	db FIEND         ; THE_DRDEK
	db ZOMBIE        ; D_ASSAILANT
	db FIEND         ; CANDLE_OF_FATE
	db AQUA          ; WATER_ELEMENT
	db ROCK          ; DISSOLVEROCK
	db FIEND         ; MEDA_BAT
	db BEAST_WARRIOR ; ONE_WHO_HUNTS_SOUL
	db FISH          ; ROOT_WATER
	db BEAST         ; MASTER_AND_EXPERT
	db AQUA          ; WATER_OMOTICS
	db WARRIOR       ; HYO
	db FISH          ; ENCHANTING_MERMAID
	db BEAST         ; NEKOGAL_1
	db SPELLCASTER   ; ANGELWITCH
	db FIEND         ; EMBRYONIC_BEAST
	db BEAST         ; PREVENT_RAT
	db WARRIOR       ; DD_WARRIOR
	db ROCK          ; STONE_ARMADILLER
	db AQUA          ; BEASTKING_OF_SWAMP
	db SPELLCASTER   ; ANCIENT_SORCERER
	db FAIRY         ; LUNAR_QUEEN_ELZAIM
	db FIEND         ; ARCHFIEND_MIRROR
	db WARRIOR       ; SWORDSMAN_OF_AILE
	db ROCK          ; ROCK_OGRE_GROTTO2
	db FAIRY         ; WING_EGG_ELF
	db AQUA          ; FURIOUS_SEA_KING
	db WARRIOR       ; PRINCESS_TSURUGI
	db WARRIOR       ; UNKNOWN_WARRIOR
	db SPELLCASTER   ; SECTARIAN_SECRET
	db FIEND         ; VERSAGO_DESTROYER
	db AQUA          ; WETHA
	db FIEND         ; MEGIRUS_LIGHT
	db WINGED_BEAST  ; MAVELUS
	db PLANT         ; ANCIENT_TREE
	db PLANT         ; GREEN_PHANTOM_KING
	db MACHINE       ; GROUND_ATTACKER
	db FAIRY         ; RAY_AND_TEMPERATURE
	db FIEND         ; GORGON_EGG
	db INSECT        ; PETIT_MOTH
	db FIEND         ; KING_FOG
	db WARRIOR       ; PROTECTOR_THRONE
	db FIEND         ; MYSTIC_CLOWN
	db BEAST         ; MYSTICAL_SHEEP_2
	db MACHINE       ; HOLOGRAH
	db SPELLCASTER   ; TAO_THE_CHANTER
	db REPTILE       ; SERPENT_MARAUDER
	db MACHINE       ; GATEKEEPER
	db BEAST_WARRIOR ; OGRE_OF_THE_BLACK
	db FIEND         ; DARK_ARTIST
	db AQUA          ; CHANGE_SLIME
	db WARRIOR       ; MOON_ENVOY
	db PYRO          ; FIREYAROU
	db AQUA          ; PSYCHIC_KAPPA
	db WARRIOR       ; MASAKI_THE_LEGEND
	db WARRIOR       ; DRAGONESS_WICKED
	db FIEND         ; BIO_PLANT
	db DRAGON        ; ONE_EYED_SHIELD
	db MACHINE       ; CYBER_SOLDIER_DARK
	db DRAGON        ; DRAGON_ERSATZ_HEAD
	db WARRIOR       ; SONIC_MAID
	db WINGED_BEAST  ; KURAMA
	db MAGIC         ; LEGENDARY_SWORD
	db MAGIC         ; SWORD_OF_DARK
	db MAGIC         ; DARK_ENERGY
	db MAGIC         ; AXE_OF_DESPAIR
	db MAGIC         ; LAZER_CANNON_ARMOR
	db MAGIC         ; INSECT_ARMOR_LASER
	db MAGIC         ; ELFS_LIGHT
	db MAGIC         ; BEAST_FANGS
	db MAGIC         ; STEEL_SHELL
	db MAGIC         ; VILE_GERMS
	db MAGIC         ; BLACK_PENDANT
	db MAGIC         ; SILVER_BOW_AND_ARROW
	db MAGIC         ; HORN_OF_LIGHT
	db MAGIC         ; HORN_OF_UNICORN
	db MAGIC         ; DRAGON_TREASURE
	db MAGIC         ; ELECTRO_WHIP
	db MAGIC         ; CYBER_SHIELD
	db MAGIC         ; ELEGANT_EGOTIST
	db MAGIC         ; MYSTICAL_MOON
	db MAGIC         ; STOP_DEFENSE
	db MAGIC         ; MALEVOLENT_NUZZLER
	db MAGIC         ; VIOLET_CRYSTAL
	db MAGIC         ; BOOK_OF_SECRET_ART
	db MAGIC         ; INVIGORATION
	db MAGIC         ; MACHINE_CONVERSION
	db MAGIC         ; RAISE_BODY_HEAT
	db MAGIC         ; FOLLOW_WIND
	db MAGIC         ; POWER_OF_KAISHIN
	db MAGIC         ; DRAGON_CAPTURE_JAR
	db MAGIC         ; FOREST
	db MAGIC         ; WASTELAND
	db MAGIC         ; MOUNTAIN
	db MAGIC         ; SOGEN
	db MAGIC         ; UMI
	db MAGIC         ; YAMI
	db MAGIC         ; DARK_HOLE
	db MAGIC         ; RAIGEKI
	db MAGIC         ; MOOYAN_CURRY
	db MAGIC         ; RED_MEDICINE
	db MAGIC         ; GOBLINS_REMEDY
	db MAGIC         ; SOUL_OF_THE_PURE
	db MAGIC         ; DIAN_KETO_THE_CURE
	db MAGIC         ; SPARKS
	db MAGIC         ; HINOTAMA
	db MAGIC         ; FINAL_FLAME
	db MAGIC         ; OOKAZI
	db MAGIC         ; TREMENDOUS_FIRE
	db MAGIC         ; SWORDS_REVEALING
	db MAGIC         ; SPELLBIND_CIRCLE
	db MAGIC         ; DARK_PIERCE_LIGHT
	db ZOMBIE        ; YARANZO
	db WARRIOR       ; KANAN_THE_SWORD
	db SEA_SERPENT   ; TAKRIMINOS
	db WARRIOR       ; STUFFED_ANIMAL
	db MACHINE       ; MEGASONIC_EYE
	db BEAST         ; SUPER_WAR_LION
	db DRAGON        ; YAMADRON
	db DRAGON        ; SEIYARYU
	db ZOMBIE        ; THREE_LEGGED_ZOMBIES
	db FIEND         ; ZERA_THE_MANT
	db AQUA          ; FLYING_PENGUIN
	db WARRIOR       ; MILLENNIUM_SHIELD
	db SPELLCASTER   ; FAIRYS_GIFT
	db WARRIOR       ; B_LUSTER_SOLDIER
	db FIEND         ; FIENDS_MIRROR

; applies level boost/reduction to wLoadedCardAtk/Def
ApplyCardLevelBoost:
	push af
	push bc
	push hl
	call GetCardLevel
	ld b, $00
	ld c, a
	sla c
	ld hl, .Jumptable
	add hl, bc
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call_hl
	pop hl
	pop bc
	pop af
	ret

.Jumptable:
	dw .LevelMinus1
	dw .Default
	dw .LevelPlus1
	dw .LevelPlus2

.LevelMinus1:
	push af
	push bc
	ld a, [wLoadedCardAtk + 0]
	ld c, a
	ld a, [wLoadedCardAtk + 1]
	ld b, a
	call Apply60PercentReduction
	ld a, c
	ld [wLoadedCardAtk + 0], a
	ld a, b
	ld [wLoadedCardAtk + 1], a
	ld a, [wLoadedCardDef + 0]
	ld c, a
	ld a, [wLoadedCardDef + 1]
	ld b, a
	call Apply60PercentReduction
	ld a, c
	ld [wLoadedCardDef + 0], a
	ld a, b
	ld [wLoadedCardDef + 1], a
	pop bc
	pop af
	ret

.Default:
	ret

.LevelPlus1:
	push af
	push bc
	ld a, [wLoadedCardAtk + 0]
	ld c, a
	ld a, [wLoadedCardAtk + 1]
	ld b, a
	call Apply60PercentBoost
	ld a, c
	ld [wLoadedCardAtk + 0], a
	ld a, b
	ld [wLoadedCardAtk + 1], a
	ld a, [wLoadedCardDef + 0]
	ld c, a
	ld a, [wLoadedCardDef + 1]
	ld b, a
	call Apply60PercentBoost
	ld a, c
	ld [wLoadedCardDef + 0], a
	ld a, b
	ld [wLoadedCardDef + 1], a
	pop bc
	pop af
	ret

.LevelPlus2:
	push af
	push bc
	ld a, [wLoadedCardAtk + 0]
	ld c, a
	ld a, [wLoadedCardAtk + 1]
	ld b, a
	call Apply60PercentBoost
	call Apply60PercentBoost
	ld a, c
	ld [wLoadedCardAtk + 0], a
	ld a, b
	ld [wLoadedCardAtk + 1], a
	ld a, [wLoadedCardDef + 0]
	ld c, a
	ld a, [wLoadedCardDef + 1]
	ld b, a
	call Apply60PercentBoost
	call Apply60PercentBoost
	ld a, c
	ld [wLoadedCardDef + 0], a
	ld a, b
	ld [wLoadedCardDef + 1], a
	pop bc
	pop af
	ret

Apply60PercentBoost:
	push af
	push de
	push hl

	ld h, b
	ld l, c

	; bc /= 10
	ld e, 4
.loop_div
	srl b
	rr c
	dec e
	jr nz, .loop_div

	; bc *= 2
	ld a, c
	add c
	daa
	ld c, a
	ld a, b
	adc b
	daa
	ld b, a

	; bc *= 3
	ld a, c
	add c
	daa
	ld e, a
	ld a, b
	adc b
	daa
	ld d, a
	ld a, e
	add c
	daa
	ld c, a
	ld a, d
	adc b
	daa
	ld b, a

	; bc += hl
	ld a, l
	add c
	daa
	ld c, a
	ld a, h
	adc b
	daa
	ld b, a

	pop hl
	pop de
	pop af
	ret

Apply60PercentReduction:
	push af
	push de
	push hl

	; bc /= 10
	ld e, 4
.loop_div
	srl b
	rr c
	dec e
	jr nz, .loop_div

	; bc *= 3
	ld a, c
	add c
	daa
	ld e, a
	ld a, b
	adc b
	daa
	ld d, a
	ld a, e
	add c
	daa
	ld c, a
	ld a, d
	adc b
	daa
	ld b, a

	; bc *= 2
	ld h, b
	ld l, c
	ld a, l
	add c
	daa
	ld c, a
	ld a, h
	adc b
	daa
	ld b, a
	pop hl
	pop de
	pop af
	ret

_ApplyFieldBoost:
	push af
	push bc
	push de
	push hl
	push af
	ld b, $00
	ld c, a
	sla c
	ld hl, .AttackValues
	add hl, bc
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [wLoadedCardID + 0]
	ld c, a
	ld a, [wLoadedCardID + 1]
	ld b, a
	sla c
	rl b
	add hl, bc
	ld a, [hli]
	ld d, [hl]
	ld e, a
	ld a, e
	ld [wLoadedCardAtk + 0], a
	ld a, d
	ld [wLoadedCardAtk + 1], a
	pop af
	ld b, $00
	ld c, a
	sla c
	ld hl, .DefenseValues
	add hl, bc
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [wLoadedCardID + 0]
	ld c, a
	ld a, [wLoadedCardID + 1]
	ld b, a
	sla c
	rl b
	add hl, bc
	ld a, [hli]
	ld d, [hl]
	ld e, a
	ld a, e
	ld [wLoadedCardDef + 0], a
	ld a, d
	ld [wLoadedCardDef + 1], a
	pop hl
	pop de
	pop bc
	pop af
	ret

.AttackValues:
	dw CardAttacks ; NONE
	dw $4939 ; FIELD_FOREST
	dw $4ef1 ; FIELD_WASTELAND
	dw $54a9 ; FIELD_MOUNTAIN
	dw $5a61 ; FIELD_SOGEN
	dw $6019 ; FIELD_UMI
	dw $65d1 ; FIELD_YAMI

.DefenseValues:
	dw CardDefenses ; NONE
	dw $4c15 ; FIELD_FOREST
	dw $51cd ; FIELD_WASTELAND
	dw $5785 ; FIELD_MOUNTAIN
	dw $5d3d ; FIELD_SOGEN
	dw $62f5 ; FIELD_UMI
	dw $68ad ; FIELD_YAMI

CardAttacks:
	dw $3000 ; B_EYE_WHITE_DRAGON
	dw  $800 ; MYSTICAL_ELF
	dw $1200 ; HITOTSU_ME_GIANT
	dw $1200 ; BABY_DRAGON
	dw $1000 ; RYU_KISHIN
	dw $1300 ; FERAL_IMP
	dw $1400 ; WINGED_DRAGON_1
	dw  $800 ; MUSHROOM_MAN
	dw  $500 ; SHADOW_SPECTER
	dw $1500 ; BLACKLAND_DRAGON
	dw $1750 ; SWORD_ARM_DRAGON
	dw $1800 ; SWAMP_BATTLEGUARD
	dw $1200 ; TYHONE
	dw $1800 ; BATTLE_STEER
	dw $1800 ; FLAME_SWORDSMAN
	dw  $500 ; TIME_WIZARD
	dw  $200 ; R_LEG_OF_FORBIDDEN
	dw  $200 ; L_LEG_OF_FORBIDDEN
	dw  $200 ; R_ARM_OF_FORBIDDEN
	dw  $200 ; L_ARM_OF_FORBIDDEN
	dw $1000 ; EXODIA_FORBIDDEN
	dw $2500 ; SUMMONED_SKULL
	dw $1400 ; WICKED_WORM_BEAST
	dw  $300 ; SKULL_SERVANT
	dw $1300 ; HORN_IMP
	dw $1700 ; BATTLE_OX
	dw $1200 ; BEAVER_WARRIOR
	dw  $800 ; ROCK_OGRE_GROTTO1
	dw  $600 ; MOUNTAIN_WARRIOR
	dw $1200 ; ZOMBIE_WARRIOR
	dw $1500 ; KOUMORI_DRAGON
	dw $1600 ; TWO_HEADED_KING_REX
	dw $2200 ; JUDGE_MAN
	dw  $600 ; SAGGI_THE_CLOWN
	dw $2500 ; DARK_MAGICIAN
	dw $1500 ; THE_SNAKE_HAIR
	dw $2600 ; GAIA_DRAGON_CHAMP
	dw $2300 ; GAIA_FIERCE_KNIGHT
	dw $2000 ; CURSE_OF_DRAGON
	dw  $200 ; DRAGON_PIPER
	dw $1400 ; CELTIC_GUARDIAN
	dw $1200 ; ILLUSION_FACELESS
	dw $1500 ; KARBONALA_WARRIOR
	dw $1600 ; ROGUE_DOLL
	dw $1000 ; WATTKID
	dw $1200 ; GRIFFORE
	dw $1200 ; TORIKE
	dw $1000 ; SANGAN
	dw $1200 ; BIG_INSECT
	dw  $500 ; BASIC_INSECT
	dw $1500 ; ARMORED_LIZARD
	dw $1500 ; HERCULES_BEETLE
	dw $1200 ; KILLER_NEEDLE
	dw $1200 ; GOKIBORE
	dw $1500 ; GIANT_FLEA
	dw  $500 ; LARVAE_MOTH
	dw $2600 ; GREAT_MOTH
	dw  $300 ; KURIBOH
	dw $1200 ; MAMMOTH_GRAVEYARD
	dw $1600 ; GREAT_WHITE
	dw $1200 ; WOLF
	dw $1300 ; HARPIE_LADY
	dw $1950 ; HARPIE_LADY_SISTER
	dw $1300 ; TIGER_AXE
	dw $1200 ; SILVER_FANG
	dw $1500 ; KOJIKOCY
	dw $3500 ; PERFECT_GREAT_MOTH
	dw $1800 ; GAROOZIS
	dw $2400 ; THOUSAND_DRAGON
	dw $1200 ; FIEND_KRAKEN
	dw $1200 ; JELLYFISH
	dw    $0 ; COCOON_EVOLUTION
	dw $1800 ; KAIRYU_SHIN
	dw $1300 ; SOLDIER_OF_STONE
	dw  $800 ; MAN_EATING_PLANT
	dw $1100 ; KROKODILUS
	dw $1300 ; GRAPPLER
	dw $1700 ; AXE_RAIDER
	dw $1800 ; MEGAZOWLER
	dw $1500 ; URABY
	dw $1600 ; CRAWLING_DRAGON_2
	dw $2400 ; RED_EYES_B_DRAGON
	dw  $920 ; CASTLE_OF_DARK
	dw $1380 ; REAPER_OF_THE_CARD
	dw $2000 ; KING_OF_YAMIMAKAI
	dw $1380 ; BAROX
	dw $1610 ; DARK_CHIMERA
	dw $1150 ; METAL_GUARDIAN
	dw $1000 ; CATAPULT_TURTLE
	dw $1800 ; GYAKUTENNO_MEGAMI
	dw $1300 ; MYSTIC_HORSEMAN
	dw $2000 ; RABID_HORSEMAN
	dw $1500 ; ZANKI
	dw $1600 ; CRAWLING_DRAGON
	dw $1350 ; CRASS_CLOWN
	dw $1500 ; ARMORED_ZOMBIE
	dw $1600 ; DRAGON_ZOMBIE
	dw $1350 ; CLOWN_ZOMBIE
	dw $1800 ; PUMPKING_THE_KING
	dw  $700 ; BATTLE_WARRIOR
	dw  $700 ; WINGS_OF_FLAME
	dw  $900 ; MASK_OF_DARKNESS
	dw  $800 ; JOB_CHANGE_MIRROR
	dw  $600 ; CURTAIN_OF_DARK
	dw  $500 ; TOMOZAURUS
	dw $1700 ; SPIRIT_OF_THE_WIND
	dw  $800 ; KAGENINGEN
	dw  $700 ; GRAVEYARD_AND_HAND
	dw $1200 ; GODDESS_THIRD_EYE
	dw $1100 ; HERO_OF_THE_EAST
	dw $1600 ; DOMA_THE_ANGEL
	dw $1200 ; THAT_WHICH_FEEDS
	dw  $800 ; DARK_GRAY
	dw $1000 ; WHITE_MAGICAL_HAT
	dw $1300 ; KAMIONWIZARD
	dw  $900 ; NIGHTMARE_SCORPION
	dw $1400 ; SPIRIT_OF_THE_BOOK
	dw $1000 ; SUPPORTER_SHADOWS
	dw $1300 ; TRIAL_OF_NIGHTMARE
	dw $1200 ; DREAM_CLOWN
	dw  $700 ; SLEEPING_LION
	dw  $900 ; YAMATANO_SCROLL
	dw  $300 ; DARK_PLANT
	dw $1700 ; ANCIENT_TOOL
	dw $1500 ; FAITH_BIRD
	dw $1800 ; ORION_THE_BATTLE
	dw $1700 ; ANSATSU
	dw $1200 ; LAMOON
	dw  $800 ; NEMURIKO
	dw  $600 ; WEATHER_CONTROL
	dw $1600 ; OCTOBERSER
	dw $1200 ; THE_13TH_GRAVE
	dw $1100 ; CHARUBIN_THE_FIRE
	dw  $700 ; MYSTICAL_CAPTURE
	dw  $600 ; FIENDS_HAND
	dw $1400 ; WITTY_PHANTOM
	dw  $500 ; MYSTERY_HAND
	dw $1100 ; DRAGON_STATUE
	dw  $900 ; B_EYED_SIL_ZOMBIE
	dw $1000 ; TOAD_MASTER
	dw  $700 ; SPIKED_SNAIL
	dw  $900 ; FLAME_MANIPULATOR
	dw  $800 ; NECROLANCER
	dw  $700 ; DJINN_THE_WATCHER
	dw  $700 ; BEWITCHING_PHANTOM
	dw  $900 ; TEMPLE_OF_SKULLS
	dw  $600 ; MONSTER_EGG
	dw  $800 ; SHADOW_WHO_CONTROL
	dw $1400 ; LORD_OF_THE_LAMP
	dw $1700 ; AKIHIRON
	dw $1200 ; RHAIMUNDOS_RED
	dw  $500 ; MELTING_RED_SHADOW
	dw  $900 ; DOKUROIZO_THE_GRIM
	dw  $700 ; FIRE_REAPER
	dw  $800 ; LARVAS
	dw  $300 ; HARD_ARMOR
	dw  $700 ; FIREGRASS
	dw  $800 ; MAN_EATER
	dw  $500 ; DIG_BEAK
	dw $1000 ; M_WARRIOR_1
	dw  $500 ; M_WARRIOR_2
	dw $1250 ; TAINTED_WISDOM
	dw $1300 ; LISARK
	dw $1300 ; LORD_OF_ZEMIA
	dw $1400 ; THE_JUDGEMENT_HAND
	dw $1000 ; MYSTERIOUS_PUPPET
	dw  $400 ; ANCIENT_JAR
	dw $1500 ; DARKFIRE_DRAGON
	dw $1200 ; DARK_KING_ABYSS
	dw  $800 ; SPIRIT_OF_THE_HARP
	dw $1200 ; BIG_EYE
	dw  $700 ; ARMAILL
	dw  $600 ; DARK_PRISONER
	dw  $900 ; HURRICAIL
	dw $1000 ; ANCIENT_BRAIN
	dw  $800 ; FIRE_EYE
	dw  $800 ; MONSTURTLE
	dw $1000 ; CLAW_REACHER
	dw  $700 ; PHANTOM_DEWAN
	dw  $800 ; ARLOWNAY
	dw $1000 ; DARK_SHADE
	dw  $500 ; MASKED_CLOWN
	dw  $600 ; LUCKY_TRINKET
	dw  $600 ; GENIN
	dw  $600 ; EYEARMOR
	dw $1100 ; FIEND_REFLECTION2
	dw  $700 ; GATE_DEEG
	dw  $800 ; SYNCHAR
	dw  $900 ; FUSIONIST
	dw $1000 ; AKAKIEISU
	dw  $600 ; LALA_LI_OON
	dw  $400 ; KEY_MACE
	dw $1000 ; TURTLE_TIGER
	dw $1200 ; TERRA_THE_TERRIBLE
	dw  $900 ; DORON
	dw $1000 ; ARMA_KNIGHT
	dw  $500 ; MECH_MOLE_ZOMBIE
	dw  $800 ; HAPPY_LOVER
	dw  $900 ; PENGUIN_KNIGHT
	dw  $600 ; PETIT_DRAGON
	dw $1200 ; FRENZIED_PANDA
	dw  $400 ; ARCHFIEND_MARMOT
	dw  $600 ; PHANTOM_GHOST
	dw $1700 ; MABARREL
	dw  $900 ; DOROVER
	dw  $900 ; TWIN_LONG_RODS_1
	dw  $600 ; DROLL_BIRD
	dw  $600 ; PETIT_ANGEL
	dw  $700 ; WINGED_CLEAVER
	dw  $600 ; HINOTAMA_SOUL
	dw  $700 ; THUNDER_KID
	dw  $700 ; MEOTOKO
	dw $1200 ; AQUA_MADOOR
	dw  $800 ; KAGEMUSHA_BLUE
	dw $1000 ; FLAME_GHOST
	dw $1200 ; DRYAD
	dw $3200 ; B_SKULL_DRAGON
	dw  $900 ; TWO_MOUTH_DARKRULER
	dw $1050 ; SOLITUDE
	dw  $900 ; MASKED_SORCERER
	dw  $700 ; KUMOOTOKO
	dw  $800 ; MIDNIGHT_FIEND
	dw $2100 ; ROAR_OCEAN_SNAKE
	dw  $500 ; TRAP_MASTER
	dw $1400 ; FIEND_SWORD
	dw  $900 ; SKULL_STALKER
	dw  $600 ; HITODENCHAK
	dw $1000 ; WOOD_REMAINS
	dw  $700 ; HOURGLASS_OF_LIFE
	dw $1500 ; RARE_FISH
	dw  $800 ; WOOD_CLOWN
	dw  $600 ; MADJINN_GUNN
	dw $1300 ; DARK_TITAN_TERROR
	dw $1600 ; BEAUTIFUL_HEADHUNT
	dw  $900 ; WODAN_THE_RESIDENT
	dw $1000 ; GUARDIAN_LABYRINTH
	dw  $500 ; HANIWA
	dw  $800 ; YASHINOKI
	dw  $900 ; VISHWAR_RANDI
	dw  $700 ; THE_DRDEK
	dw $1200 ; D_ASSAILANT
	dw  $600 ; CANDLE_OF_FATE
	dw  $900 ; WATER_ELEMENT
	dw  $900 ; DISSOLVEROCK
	dw  $800 ; MEDA_BAT
	dw $1100 ; ONE_WHO_HUNTS_SOUL
	dw  $900 ; ROOT_WATER
	dw $1200 ; MASTER_AND_EXPERT
	dw $1400 ; WATER_OMOTICS
	dw  $800 ; HYO
	dw $1200 ; ENCHANTING_MERMAID
	dw $1100 ; NEKOGAL_1
	dw  $800 ; ANGELWITCH
	dw  $500 ; EMBRYONIC_BEAST
	dw  $500 ; PREVENT_RAT
	dw $1200 ; DD_WARRIOR
	dw  $800 ; STONE_ARMADILLER
	dw $1000 ; BEASTKING_OF_SWAMP
	dw $1000 ; ANCIENT_SORCERER
	dw  $750 ; LUNAR_QUEEN_ELZAIM
	dw  $700 ; ARCHFIEND_MIRROR
	dw  $800 ; SWORDSMAN_OF_AILE
	dw  $700 ; ROCK_OGRE_GROTTO2
	dw  $500 ; WING_EGG_ELF
	dw  $800 ; FURIOUS_SEA_KING
	dw  $900 ; PRINCESS_TSURUGI
	dw $1000 ; UNKNOWN_WARRIOR
	dw  $700 ; SECTARIAN_SECRET
	dw $1100 ; VERSAGO_DESTROYER
	dw $1000 ; WETHA
	dw  $900 ; MEGIRUS_LIGHT
	dw $1300 ; MAVELUS
	dw  $600 ; ANCIENT_TREE
	dw  $500 ; GREEN_PHANTOM_KING
	dw $1500 ; GROUND_ATTACKER
	dw $1000 ; RAY_AND_TEMPERATURE
	dw  $300 ; GORGON_EGG
	dw  $300 ; PETIT_MOTH
	dw $1000 ; KING_FOG
	dw  $800 ; PROTECTOR_THRONE
	dw $1500 ; MYSTIC_CLOWN
	dw  $800 ; MYSTICAL_SHEEP_2
	dw $1100 ; HOLOGRAH
	dw $1200 ; TAO_THE_CHANTER
	dw  $700 ; SERPENT_MARAUDER
	dw $1500 ; GATEKEEPER
	dw $1200 ; OGRE_OF_THE_BLACK
	dw  $600 ; DARK_ARTIST
	dw  $400 ; CHANGE_SLIME
	dw $1100 ; MOON_ENVOY
	dw $1300 ; FIREYAROU
	dw  $400 ; PSYCHIC_KAPPA
	dw $1100 ; MASAKI_THE_LEGEND
	dw $1200 ; DRAGONESS_WICKED
	dw  $600 ; BIO_PLANT
	dw  $700 ; ONE_EYED_SHIELD
	dw $1400 ; CYBER_SOLDIER_DARK
	dw  $900 ; DRAGON_ERSATZ_HEAD
	dw $1200 ; SONIC_MAID
	dw  $800 ; KURAMA
	dw    -1 ; LEGENDARY_SWORD
	dw    -1 ; SWORD_OF_DARK
	dw    -1 ; DARK_ENERGY
	dw    -1 ; AXE_OF_DESPAIR
	dw    -1 ; LAZER_CANNON_ARMOR
	dw    -1 ; INSECT_ARMOR_LASER
	dw    -1 ; ELFS_LIGHT
	dw    -1 ; BEAST_FANGS
	dw    -1 ; STEEL_SHELL
	dw    -1 ; VILE_GERMS
	dw    -1 ; BLACK_PENDANT
	dw    -1 ; SILVER_BOW_AND_ARROW
	dw    -1 ; HORN_OF_LIGHT
	dw    -1 ; HORN_OF_UNICORN
	dw    -1 ; DRAGON_TREASURE
	dw    -1 ; ELECTRO_WHIP
	dw    -1 ; CYBER_SHIELD
	dw    -1 ; ELEGANT_EGOTIST
	dw    -1 ; MYSTICAL_MOON
	dw    -1 ; STOP_DEFENSE
	dw    -1 ; MALEVOLENT_NUZZLER
	dw    -1 ; VIOLET_CRYSTAL
	dw    -1 ; BOOK_OF_SECRET_ART
	dw    -1 ; INVIGORATION
	dw    -1 ; MACHINE_CONVERSION
	dw    -1 ; RAISE_BODY_HEAT
	dw    -1 ; FOLLOW_WIND
	dw    -1 ; POWER_OF_KAISHIN
	dw    -1 ; DRAGON_CAPTURE_JAR
	dw    -1 ; FOREST
	dw    -1 ; WASTELAND
	dw    -1 ; MOUNTAIN
	dw    -1 ; SOGEN
	dw    -1 ; UMI
	dw    -1 ; YAMI
	dw    -1 ; DARK_HOLE
	dw    -1 ; RAIGEKI
	dw    -1 ; MOOYAN_CURRY
	dw    -1 ; RED_MEDICINE
	dw    -1 ; GOBLINS_REMEDY
	dw    -1 ; SOUL_OF_THE_PURE
	dw    -1 ; DIAN_KETO_THE_CURE
	dw    -1 ; SPARKS
	dw    -1 ; HINOTAMA
	dw    -1 ; FINAL_FLAME
	dw    -1 ; OOKAZI
	dw    -1 ; TREMENDOUS_FIRE
	dw    -1 ; SWORDS_REVEALING
	dw    -1 ; SPELLBIND_CIRCLE
	dw    -1 ; DARK_PIERCE_LIGHT
	dw $1300 ; YARANZO
	dw $1400 ; KANAN_THE_SWORD
	dw $1500 ; TAKRIMINOS
	dw $1200 ; STUFFED_ANIMAL
	dw $1500 ; MEGASONIC_EYE
	dw $2300 ; SUPER_WAR_LION
	dw $1600 ; YAMADRON
	dw $2500 ; SEIYARYU
	dw $1100 ; THREE_LEGGED_ZOMBIES
	dw $2800 ; ZERA_THE_MANT
	dw $1200 ; FLYING_PENGUIN
	dw    $0 ; MILLENNIUM_SHIELD
	dw $1400 ; FAIRYS_GIFT
	dw $3000 ; B_LUSTER_SOLDIER
	dw $2100 ; FIENDS_MIRROR
	dw    -1 ; INVALID_CARD

CardDefenses:
	dw $2500 ; B_EYE_WHITE_DRAGON
	dw $2000 ; MYSTICAL_ELF
	dw $1000 ; HITOTSU_ME_GIANT
	dw  $700 ; BABY_DRAGON
	dw  $500 ; RYU_KISHIN
	dw $1400 ; FERAL_IMP
	dw $1200 ; WINGED_DRAGON_1
	dw  $600 ; MUSHROOM_MAN
	dw  $200 ; SHADOW_SPECTER
	dw  $800 ; BLACKLAND_DRAGON
	dw $2030 ; SWORD_ARM_DRAGON
	dw $1500 ; SWAMP_BATTLEGUARD
	dw $1400 ; TYHONE
	dw $1300 ; BATTLE_STEER
	dw $1600 ; FLAME_SWORDSMAN
	dw  $400 ; TIME_WIZARD
	dw  $300 ; R_LEG_OF_FORBIDDEN
	dw  $300 ; L_LEG_OF_FORBIDDEN
	dw  $300 ; R_ARM_OF_FORBIDDEN
	dw  $300 ; L_ARM_OF_FORBIDDEN
	dw $1000 ; EXODIA_FORBIDDEN
	dw $1200 ; SUMMONED_SKULL
	dw  $700 ; WICKED_WORM_BEAST
	dw  $200 ; SKULL_SERVANT
	dw $1000 ; HORN_IMP
	dw $1000 ; BATTLE_OX
	dw $1500 ; BEAVER_WARRIOR
	dw $1200 ; ROCK_OGRE_GROTTO1
	dw $1000 ; MOUNTAIN_WARRIOR
	dw  $900 ; ZOMBIE_WARRIOR
	dw $1200 ; KOUMORI_DRAGON
	dw $1200 ; TWO_HEADED_KING_REX
	dw $1500 ; JUDGE_MAN
	dw $1500 ; SAGGI_THE_CLOWN
	dw $2100 ; DARK_MAGICIAN
	dw $1200 ; THE_SNAKE_HAIR
	dw $2100 ; GAIA_DRAGON_CHAMP
	dw $2100 ; GAIA_FIERCE_KNIGHT
	dw $1500 ; CURSE_OF_DRAGON
	dw $1800 ; DRAGON_PIPER
	dw $1200 ; CELTIC_GUARDIAN
	dw $2200 ; ILLUSION_FACELESS
	dw $1200 ; KARBONALA_WARRIOR
	dw $1000 ; ROGUE_DOLL
	dw  $500 ; WATTKID
	dw $1500 ; GRIFFORE
	dw  $600 ; TORIKE
	dw  $600 ; SANGAN
	dw $1500 ; BIG_INSECT
	dw  $700 ; BASIC_INSECT
	dw $1200 ; ARMORED_LIZARD
	dw $2000 ; HERCULES_BEETLE
	dw $1000 ; KILLER_NEEDLE
	dw $1400 ; GOKIBORE
	dw $1200 ; GIANT_FLEA
	dw  $400 ; LARVAE_MOTH
	dw $2500 ; GREAT_MOTH
	dw  $200 ; KURIBOH
	dw  $800 ; MAMMOTH_GRAVEYARD
	dw  $800 ; GREAT_WHITE
	dw  $800 ; WOLF
	dw $1400 ; HARPIE_LADY
	dw $2100 ; HARPIE_LADY_SISTER
	dw $1100 ; TIGER_AXE
	dw  $800 ; SILVER_FANG
	dw $1200 ; KOJIKOCY
	dw $3000 ; PERFECT_GREAT_MOTH
	dw $1500 ; GAROOZIS
	dw $2000 ; THOUSAND_DRAGON
	dw $1400 ; FIEND_KRAKEN
	dw $1500 ; JELLYFISH
	dw $2000 ; COCOON_EVOLUTION
	dw $1500 ; KAIRYU_SHIN
	dw $2000 ; SOLDIER_OF_STONE
	dw  $600 ; MAN_EATING_PLANT
	dw $1200 ; KROKODILUS
	dw $1200 ; GRAPPLER
	dw $1150 ; AXE_RAIDER
	dw $2000 ; MEGAZOWLER
	dw  $800 ; URABY
	dw $1200 ; CRAWLING_DRAGON_2
	dw $2000 ; RED_EYES_B_DRAGON
	dw $1930 ; CASTLE_OF_DARK
	dw $1930 ; REAPER_OF_THE_CARD
	dw $1530 ; KING_OF_YAMIMAKAI
	dw $1530 ; BAROX
	dw $1460 ; DARK_CHIMERA
	dw $2150 ; METAL_GUARDIAN
	dw $2000 ; CATAPULT_TURTLE
	dw $2000 ; GYAKUTENNO_MEGAMI
	dw $1550 ; MYSTIC_HORSEMAN
	dw $1700 ; RABID_HORSEMAN
	dw $1700 ; ZANKI
	dw $1400 ; CRAWLING_DRAGON
	dw $1400 ; CRASS_CLOWN
	dw    $0 ; ARMORED_ZOMBIE
	dw    $0 ; DRAGON_ZOMBIE
	dw    $0 ; CLOWN_ZOMBIE
	dw $2000 ; PUMPKING_THE_KING
	dw $1000 ; BATTLE_WARRIOR
	dw  $600 ; WINGS_OF_FLAME
	dw  $400 ; MASK_OF_DARKNESS
	dw $1300 ; JOB_CHANGE_MIRROR
	dw  $500 ; CURTAIN_OF_DARK
	dw  $400 ; TOMOZAURUS
	dw $1400 ; SPIRIT_OF_THE_WIND
	dw  $600 ; KAGENINGEN
	dw  $900 ; GRAVEYARD_AND_HAND
	dw $1000 ; GODDESS_THIRD_EYE
	dw $1000 ; HERO_OF_THE_EAST
	dw $1400 ; DOMA_THE_ANGEL
	dw $1000 ; THAT_WHICH_FEEDS
	dw  $900 ; DARK_GRAY
	dw  $700 ; WHITE_MAGICAL_HAT
	dw $1100 ; KAMIONWIZARD
	dw  $800 ; NIGHTMARE_SCORPION
	dw $1200 ; SPIRIT_OF_THE_BOOK
	dw $1000 ; SUPPORTER_SHADOWS
	dw  $900 ; TRIAL_OF_NIGHTMARE
	dw  $900 ; DREAM_CLOWN
	dw $1700 ; SLEEPING_LION
	dw  $300 ; YAMATANO_SCROLL
	dw  $400 ; DARK_PLANT
	dw $1400 ; ANCIENT_TOOL
	dw $1100 ; FAITH_BIRD
	dw $1500 ; ORION_THE_BATTLE
	dw $1200 ; ANSATSU
	dw $1700 ; LAMOON
	dw  $700 ; NEMURIKO
	dw  $400 ; WEATHER_CONTROL
	dw $1400 ; OCTOBERSER
	dw  $900 ; THE_13TH_GRAVE
	dw  $800 ; CHARUBIN_THE_FIRE
	dw  $700 ; MYSTICAL_CAPTURE
	dw  $600 ; FIENDS_HAND
	dw $1300 ; WITTY_PHANTOM
	dw  $500 ; MYSTERY_HAND
	dw  $900 ; DRAGON_STATUE
	dw  $700 ; B_EYED_SIL_ZOMBIE
	dw $1000 ; TOAD_MASTER
	dw $1300 ; SPIKED_SNAIL
	dw $1000 ; FLAME_MANIPULATOR
	dw  $900 ; NECROLANCER
	dw  $900 ; DJINN_THE_WATCHER
	dw  $700 ; BEWITCHING_PHANTOM
	dw $1300 ; TEMPLE_OF_SKULLS
	dw  $900 ; MONSTER_EGG
	dw  $700 ; SHADOW_WHO_CONTROL
	dw $1200 ; LORD_OF_THE_LAMP
	dw $1400 ; AKIHIRON
	dw $1300 ; RHAIMUNDOS_RED
	dw  $700 ; MELTING_RED_SHADOW
	dw $1200 ; DOKUROIZO_THE_GRIM
	dw  $500 ; FIRE_REAPER
	dw $1000 ; LARVAS
	dw $1200 ; HARD_ARMOR
	dw  $600 ; FIREGRASS
	dw  $600 ; MAN_EATER
	dw  $800 ; DIG_BEAK
	dw  $500 ; M_WARRIOR_1
	dw $1000 ; M_WARRIOR_2
	dw  $800 ; TAINTED_WISDOM
	dw $1300 ; LISARK
	dw $1000 ; LORD_OF_ZEMIA
	dw  $700 ; THE_JUDGEMENT_HAND
	dw $1500 ; MYSTERIOUS_PUPPET
	dw  $200 ; ANCIENT_JAR
	dw $1250 ; DARKFIRE_DRAGON
	dw  $800 ; DARK_KING_ABYSS
	dw $2000 ; SPIRIT_OF_THE_HARP
	dw $1000 ; BIG_EYE
	dw $1300 ; ARMAILL
	dw $1000 ; DARK_PRISONER
	dw  $200 ; HURRICAIL
	dw  $700 ; ANCIENT_BRAIN
	dw  $600 ; FIRE_EYE
	dw $1000 ; MONSTURTLE
	dw  $800 ; CLAW_REACHER
	dw  $600 ; PHANTOM_DEWAN
	dw $1000 ; ARLOWNAY
	dw $1000 ; DARK_SHADE
	dw  $700 ; MASKED_CLOWN
	dw  $800 ; LUCKY_TRINKET
	dw  $900 ; GENIN
	dw  $500 ; EYEARMOR
	dw $1400 ; FIEND_REFLECTION2
	dw  $800 ; GATE_DEEG
	dw  $900 ; SYNCHAR
	dw  $700 ; FUSIONIST
	dw  $800 ; AKAKIEISU
	dw  $600 ; LALA_LI_OON
	dw  $300 ; KEY_MACE
	dw $1500 ; TURTLE_TIGER
	dw $1300 ; TERRA_THE_TERRIBLE
	dw  $500 ; DORON
	dw $1200 ; ARMA_KNIGHT
	dw  $400 ; MECH_MOLE_ZOMBIE
	dw  $500 ; HAPPY_LOVER
	dw  $800 ; PENGUIN_KNIGHT
	dw  $700 ; PETIT_DRAGON
	dw $1000 ; FRENZIED_PANDA
	dw  $600 ; ARCHFIEND_MARMOT
	dw  $800 ; PHANTOM_GHOST
	dw $1400 ; MABARREL
	dw  $800 ; DOROVER
	dw  $700 ; TWIN_LONG_RODS_1
	dw  $500 ; DROLL_BIRD
	dw  $900 ; PETIT_ANGEL
	dw  $700 ; WINGED_CLEAVER
	dw  $500 ; HINOTAMA_SOUL
	dw  $600 ; THUNDER_KID
	dw  $600 ; MEOTOKO
	dw $2000 ; AQUA_MADOOR
	dw  $400 ; KAGEMUSHA_BLUE
	dw  $800 ; FLAME_GHOST
	dw $1400 ; DRYAD
	dw $2500 ; B_SKULL_DRAGON
	dw  $700 ; TWO_MOUTH_DARKRULER
	dw $1000 ; SOLITUDE
	dw $1400 ; MASKED_SORCERER
	dw $1400 ; KUMOOTOKO
	dw  $600 ; MIDNIGHT_FIEND
	dw $1800 ; ROAR_OCEAN_SNAKE
	dw $1100 ; TRAP_MASTER
	dw  $800 ; FIEND_SWORD
	dw  $800 ; SKULL_STALKER
	dw  $700 ; HITODENCHAK
	dw  $900 ; WOOD_REMAINS
	dw  $600 ; HOURGLASS_OF_LIFE
	dw $1200 ; RARE_FISH
	dw $1200 ; WOOD_CLOWN
	dw  $800 ; MADJINN_GUNN
	dw $1100 ; DARK_TITAN_TERROR
	dw  $800 ; BEAUTIFUL_HEADHUNT
	dw $1200 ; WODAN_THE_RESIDENT
	dw $1200 ; GUARDIAN_LABYRINTH
	dw  $500 ; HANIWA
	dw  $600 ; YASHINOKI
	dw  $700 ; VISHWAR_RANDI
	dw  $800 ; THE_DRDEK
	dw $1200 ; D_ASSAILANT
	dw  $600 ; CANDLE_OF_FATE
	dw  $700 ; WATER_ELEMENT
	dw $1000 ; DISSOLVEROCK
	dw  $400 ; MEDA_BAT
	dw $1000 ; ONE_WHO_HUNTS_SOUL
	dw  $800 ; ROOT_WATER
	dw $1000 ; MASTER_AND_EXPERT
	dw $1200 ; WATER_OMOTICS
	dw $1200 ; HYO
	dw  $900 ; ENCHANTING_MERMAID
	dw  $900 ; NEKOGAL_1
	dw $1000 ; ANGELWITCH
	dw  $750 ; EMBRYONIC_BEAST
	dw $2000 ; PREVENT_RAT
	dw $1000 ; DD_WARRIOR
	dw $1200 ; STONE_ARMADILLER
	dw $1100 ; BEASTKING_OF_SWAMP
	dw $1300 ; ANCIENT_SORCERER
	dw $1100 ; LUNAR_QUEEN_ELZAIM
	dw  $600 ; ARCHFIEND_MIRROR
	dw $1300 ; SWORDSMAN_OF_AILE
	dw $1400 ; ROCK_OGRE_GROTTO2
	dw $1300 ; WING_EGG_ELF
	dw  $700 ; FURIOUS_SEA_KING
	dw  $700 ; PRINCESS_TSURUGI
	dw  $500 ; UNKNOWN_WARRIOR
	dw  $500 ; SECTARIAN_SECRET
	dw  $900 ; VERSAGO_DESTROYER
	dw  $900 ; WETHA
	dw  $600 ; MEGIRUS_LIGHT
	dw  $900 ; MAVELUS
	dw $1500 ; ANCIENT_TREE
	dw $1600 ; GREEN_PHANTOM_KING
	dw $1000 ; GROUND_ATTACKER
	dw $1000 ; RAY_AND_TEMPERATURE
	dw $1300 ; GORGON_EGG
	dw  $200 ; PETIT_MOTH
	dw  $900 ; KING_FOG
	dw $1500 ; PROTECTOR_THRONE
	dw $1000 ; MYSTIC_CLOWN
	dw $1000 ; MYSTICAL_SHEEP_2
	dw  $700 ; HOLOGRAH
	dw  $900 ; TAO_THE_CHANTER
	dw  $600 ; SERPENT_MARAUDER
	dw $1800 ; GATEKEEPER
	dw $1400 ; OGRE_OF_THE_BLACK
	dw $1400 ; DARK_ARTIST
	dw  $300 ; CHANGE_SLIME
	dw $1000 ; MOON_ENVOY
	dw $1000 ; FIREYAROU
	dw $1000 ; PSYCHIC_KAPPA
	dw $1100 ; MASAKI_THE_LEGEND
	dw  $900 ; DRAGONESS_WICKED
	dw $1300 ; BIO_PLANT
	dw $1300 ; ONE_EYED_SHIELD
	dw $1200 ; CYBER_SOLDIER_DARK
	dw  $900 ; DRAGON_ERSATZ_HEAD
	dw  $900 ; SONIC_MAID
	dw  $800 ; KURAMA
	dw    -1 ; LEGENDARY_SWORD
	dw    -1 ; SWORD_OF_DARK
	dw    -1 ; DARK_ENERGY
	dw    -1 ; AXE_OF_DESPAIR
	dw    -1 ; LAZER_CANNON_ARMOR
	dw    -1 ; INSECT_ARMOR_LASER
	dw    -1 ; ELFS_LIGHT
	dw    -1 ; BEAST_FANGS
	dw    -1 ; STEEL_SHELL
	dw    -1 ; VILE_GERMS
	dw    -1 ; BLACK_PENDANT
	dw    -1 ; SILVER_BOW_AND_ARROW
	dw    -1 ; HORN_OF_LIGHT
	dw    -1 ; HORN_OF_UNICORN
	dw    -1 ; DRAGON_TREASURE
	dw    -1 ; ELECTRO_WHIP
	dw    -1 ; CYBER_SHIELD
	dw    -1 ; ELEGANT_EGOTIST
	dw    -1 ; MYSTICAL_MOON
	dw    -1 ; STOP_DEFENSE
	dw    -1 ; MALEVOLENT_NUZZLER
	dw    -1 ; VIOLET_CRYSTAL
	dw    -1 ; BOOK_OF_SECRET_ART
	dw    -1 ; INVIGORATION
	dw    -1 ; MACHINE_CONVERSION
	dw    -1 ; RAISE_BODY_HEAT
	dw    -1 ; FOLLOW_WIND
	dw    -1 ; POWER_OF_KAISHIN
	dw    -1 ; DRAGON_CAPTURE_JAR
	dw    -1 ; FOREST
	dw    -1 ; WASTELAND
	dw    -1 ; MOUNTAIN
	dw    -1 ; SOGEN
	dw    -1 ; UMI
	dw    -1 ; YAMI
	dw    -1 ; DARK_HOLE
	dw    -1 ; RAIGEKI
	dw    -1 ; MOOYAN_CURRY
	dw    -1 ; RED_MEDICINE
	dw    -1 ; GOBLINS_REMEDY
	dw    -1 ; SOUL_OF_THE_PURE
	dw    -1 ; DIAN_KETO_THE_CURE
	dw    -1 ; SPARKS
	dw    -1 ; HINOTAMA
	dw    -1 ; FINAL_FLAME
	dw    -1 ; OOKAZI
	dw    -1 ; TREMENDOUS_FIRE
	dw    -1 ; SWORDS_REVEALING
	dw    -1 ; SPELLBIND_CIRCLE
	dw    -1 ; DARK_PIERCE_LIGHT
	dw $1500 ; YARANZO
	dw $1400 ; KANAN_THE_SWORD
	dw $1200 ; TAKRIMINOS
	dw  $900 ; STUFFED_ANIMAL
	dw $1800 ; MEGASONIC_EYE
	dw $2100 ; SUPER_WAR_LION
	dw $1800 ; YAMADRON
	dw $2300 ; SEIYARYU
	dw  $800 ; THREE_LEGGED_ZOMBIES
	dw $2300 ; ZERA_THE_MANT
	dw $1000 ; FLYING_PENGUIN
	dw $3000 ; MILLENNIUM_SHIELD
	dw $1000 ; FAIRYS_GIFT
	dw $2500 ; B_LUSTER_SOLDIER
	dw $1800 ; FIENDS_MIRROR
	dw    -1 ; INVALID_CARD

SECTION "Bank 9@6b89", ROMX[$6b89], BANK[$9]

Func_26b89:
	push bc
	push de
	push hl
	ld e, d
	ld d, $00
	sla e
	ld hl, PtrTable_26bc8
	add hl, de
	ld a, [hli]
	ld h, [hl]
	ld l, a
	call Func_26b9f
	pop hl
	pop de
	pop bc
	ret

Func_26b9f:
	push bc
	push de
	push hl
.loop
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
	; end of list?
	push bc
	ld bc, -1
	call IsBCEqualToDE
	pop bc
	cp TRUE
	jr nz, .not_end
	ld e, TRUE
	jr .got_result
.not_end
	call IsBCEqualToDE
	cp TRUE
	jr nz, .next
	ld e, FALSE
	jr .got_result
.next
	jr .loop
.got_result
	ld a, e
	pop hl
	pop de
	pop bc
	ret

PtrTable_26bc8:
	dw CardList_26bfc
	dw CardList_26c62
	dw CardList_26cac
	dw CardList_26df2
	dw CardList_26e60
	dw CardList_26efa
	dw CardList_26f22
	dw CardList_26f64
	dw CardList_27030
	dw CardList_2703a
	dw CardList_27056
	dw CardList_270e0
	dw CardList_27110
	dw CardList_2713e
	dw CardList_27190
	dw CardList_271e4
	dw CardList_27262
	dw CardList_27290
	dw CardList_272fa
	dw CardList_27376
	dw CardList_273d2
	dw CardList_27436
	dw CardList_274d0
	dw CardList_274f0
	dw CardList_27576
	dw CardList_27600

CardList_26bfc:
	dw SWAMP_BATTLEGUARD
	dw FLAME_SWORDSMAN
	dw BATTLE_OX
	dw BEAVER_WARRIOR
	dw MOUNTAIN_WARRIOR
	dw JUDGE_MAN
	dw GAIA_FIERCE_KNIGHT
	dw CELTIC_GUARDIAN
	dw KARBONALA_WARRIOR
	dw TIGER_AXE
	dw KOJIKOCY
	dw AXE_RAIDER
	dw RABID_HORSEMAN
	dw ZANKI
	dw BATTLE_WARRIOR
	dw HERO_OF_THE_EAST
	dw SUPPORTER_SHADOWS
	dw DREAM_CLOWN
	dw OCTOBERSER
	dw CHARUBIN_THE_FIRE
	dw DRAGON_STATUE
	dw MONSTER_EGG
	dw RHAIMUNDOS_RED
	dw HARD_ARMOR
	dw M_WARRIOR_1
	dw M_WARRIOR_2
	dw THE_JUDGEMENT_HAND
	dw MYSTERIOUS_PUPPET
	dw ARMAILL
	dw EYEARMOR
	dw ARMA_KNIGHT
	dw PENGUIN_KNIGHT
	dw MEOTOKO
	dw TRAP_MASTER
	dw WOOD_CLOWN
	dw WODAN_THE_RESIDENT
	dw HYO
	dw NEKOGAL_1
	dw DD_WARRIOR
	dw SWORDSMAN_OF_AILE
	dw FURIOUS_SEA_KING
	dw PRINCESS_TSURUGI
	dw GATEKEEPER
	dw MOON_ENVOY
	dw FIREYAROU
	dw MASAKI_THE_LEGEND
	dw SONIC_MAID
	dw KANAN_THE_SWORD
	dw STUFFED_ANIMAL
	dw MILLENNIUM_SHIELD
	dw -1 ; end

CardList_26c62:
	dw SWAMP_BATTLEGUARD
	dw BATTLE_STEER
	dw SUMMONED_SKULL
	dw WICKED_WORM_BEAST
	dw HORN_IMP
	dw ZOMBIE_WARRIOR
	dw GAIA_FIERCE_KNIGHT
	dw KOJIKOCY
	dw GAROOZIS
	dw KAGENINGEN
	dw TRIAL_OF_NIGHTMARE
	dw ANCIENT_TOOL
	dw ANSATSU
	dw MASKED_CLOWN
	dw DORON
	dw KAGEMUSHA_BLUE
	dw SOLITUDE
	dw FIEND_SWORD
	dw SKULL_STALKER
	dw BEAUTIFUL_HEADHUNT
	dw GUARDIAN_LABYRINTH
	dw VISHWAR_RANDI
	dw D_ASSAILANT
	dw ONE_WHO_HUNTS_SOUL
	dw DD_WARRIOR
	dw UNKNOWN_WARRIOR
	dw VERSAGO_DESTROYER
	dw MYSTIC_CLOWN
	dw MASAKI_THE_LEGEND
	dw DRAGONESS_WICKED
	dw CYBER_SOLDIER_DARK
	dw MEGASONIC_EYE
	dw SUPER_WAR_LION
	dw THREE_LEGGED_ZOMBIES
	dw ZERA_THE_MANT
	dw B_LUSTER_SOLDIER
	dw -1 ; end

CardList_26cac:
	dw HITOTSU_ME_GIANT
	dw RYU_KISHIN
	dw FERAL_IMP
	dw SHADOW_SPECTER
	dw BLACKLAND_DRAGON
	dw SWAMP_BATTLEGUARD
	dw TIME_WIZARD
	dw R_LEG_OF_FORBIDDEN
	dw L_LEG_OF_FORBIDDEN
	dw R_ARM_OF_FORBIDDEN
	dw L_ARM_OF_FORBIDDEN
	dw EXODIA_FORBIDDEN
	dw SUMMONED_SKULL
	dw WICKED_WORM_BEAST
	dw SKULL_SERVANT
	dw HORN_IMP
	dw ZOMBIE_WARRIOR
	dw KOUMORI_DRAGON
	dw SAGGI_THE_CLOWN
	dw DARK_MAGICIAN
	dw GAIA_FIERCE_KNIGHT
	dw DRAGON_PIPER
	dw ILLUSION_FACELESS
	dw WATTKID
	dw SANGAN
	dw KURIBOH
	dw SILVER_FANG
	dw KOJIKOCY
	dw MAN_EATING_PLANT
	dw KROKODILUS
	dw CRAWLING_DRAGON_2
	dw CASTLE_OF_DARK
	dw REAPER_OF_THE_CARD
	dw KING_OF_YAMIMAKAI
	dw BAROX
	dw DARK_CHIMERA
	dw METAL_GUARDIAN
	dw CRASS_CLOWN
	dw ARMORED_ZOMBIE
	dw DRAGON_ZOMBIE
	dw CLOWN_ZOMBIE
	dw PUMPKING_THE_KING
	dw WINGS_OF_FLAME
	dw MASK_OF_DARKNESS
	dw JOB_CHANGE_MIRROR
	dw CURTAIN_OF_DARK
	dw TOMOZAURUS
	dw KAGENINGEN
	dw GRAVEYARD_AND_HAND
	dw DOMA_THE_ANGEL
	dw THAT_WHICH_FEEDS
	dw DARK_GRAY
	dw KAMIONWIZARD
	dw NIGHTMARE_SCORPION
	dw TRIAL_OF_NIGHTMARE
	dw DARK_PLANT
	dw ANCIENT_TOOL
	dw ANSATSU
	dw THE_13TH_GRAVE
	dw FIENDS_HAND
	dw WITTY_PHANTOM
	dw MYSTERY_HAND
	dw B_EYED_SIL_ZOMBIE
	dw SPIKED_SNAIL
	dw FLAME_MANIPULATOR
	dw NECROLANCER
	dw TEMPLE_OF_SKULLS
	dw SHADOW_WHO_CONTROL
	dw LORD_OF_THE_LAMP
	dw AKIHIRON
	dw MELTING_RED_SHADOW
	dw DOKUROIZO_THE_GRIM
	dw FIRE_REAPER
	dw LARVAS
	dw MAN_EATER
	dw TAINTED_WISDOM
	dw LORD_OF_ZEMIA
	dw ANCIENT_JAR
	dw DARKFIRE_DRAGON
	dw DARK_KING_ABYSS
	dw BIG_EYE
	dw DARK_PRISONER
	dw HURRICAIL
	dw ANCIENT_BRAIN
	dw FIRE_EYE
	dw CLAW_REACHER
	dw PHANTOM_DEWAN
	dw DARK_SHADE
	dw MASKED_CLOWN
	dw EYEARMOR
	dw GATE_DEEG
	dw SYNCHAR
	dw AKAKIEISU
	dw TERRA_THE_TERRIBLE
	dw DORON
	dw MECH_MOLE_ZOMBIE
	dw FRENZIED_PANDA
	dw ARCHFIEND_MARMOT
	dw PHANTOM_GHOST
	dw MABARREL
	dw DOROVER
	dw TWIN_LONG_RODS_1
	dw WINGED_CLEAVER
	dw HINOTAMA_SOUL
	dw MEOTOKO
	dw AQUA_MADOOR
	dw KAGEMUSHA_BLUE
	dw FLAME_GHOST
	dw TWO_MOUTH_DARKRULER
	dw SOLITUDE
	dw MASKED_SORCERER
	dw KUMOOTOKO
	dw MIDNIGHT_FIEND
	dw ROAR_OCEAN_SNAKE
	dw TRAP_MASTER
	dw FIEND_SWORD
	dw SKULL_STALKER
	dw WOOD_REMAINS
	dw WOOD_CLOWN
	dw MADJINN_GUNN
	dw DARK_TITAN_TERROR
	dw BEAUTIFUL_HEADHUNT
	dw GUARDIAN_LABYRINTH
	dw VISHWAR_RANDI
	dw THE_DRDEK
	dw D_ASSAILANT
	dw CANDLE_OF_FATE
	dw MEDA_BAT
	dw ONE_WHO_HUNTS_SOUL
	dw MASTER_AND_EXPERT
	dw ANGELWITCH
	dw EMBRYONIC_BEAST
	dw DD_WARRIOR
	dw BEASTKING_OF_SWAMP
	dw ANCIENT_SORCERER
	dw ARCHFIEND_MIRROR
	dw UNKNOWN_WARRIOR
	dw SECTARIAN_SECRET
	dw VERSAGO_DESTROYER
	dw MEGIRUS_LIGHT
	dw GORGON_EGG
	dw KING_FOG
	dw MYSTIC_CLOWN
	dw HOLOGRAH
	dw TAO_THE_CHANTER
	dw SERPENT_MARAUDER
	dw GATEKEEPER
	dw OGRE_OF_THE_BLACK
	dw DARK_ARTIST
	dw FIREYAROU
	dw MASAKI_THE_LEGEND
	dw DRAGONESS_WICKED
	dw BIO_PLANT
	dw CYBER_SOLDIER_DARK
	dw DRAGON_ERSATZ_HEAD
	dw YARANZO
	dw MEGASONIC_EYE
	dw THREE_LEGGED_ZOMBIES
	dw ZERA_THE_MANT
	dw MILLENNIUM_SHIELD
	dw B_LUSTER_SOLDIER
	dw FIENDS_MIRROR
	dw -1 ; end

CardList_26df2:
	dw HITOTSU_ME_GIANT
	dw RYU_KISHIN
	dw FERAL_IMP
	dw SWAMP_BATTLEGUARD
	dw BATTLE_STEER
	dw SUMMONED_SKULL
	dw WICKED_WORM_BEAST
	dw SKULL_SERVANT
	dw HORN_IMP
	dw BATTLE_OX
	dw BEAVER_WARRIOR
	dw MOUNTAIN_WARRIOR
	dw ZOMBIE_WARRIOR
	dw TIGER_AXE
	dw KOJIKOCY
	dw GAROOZIS
	dw KROKODILUS
	dw GRAPPLER
	dw AXE_RAIDER
	dw BAROX
	dw METAL_GUARDIAN
	dw MYSTIC_HORSEMAN
	dw RABID_HORSEMAN
	dw ARMORED_ZOMBIE
	dw KAGENINGEN
	dw TRIAL_OF_NIGHTMARE
	dw ANSATSU
	dw LORD_OF_THE_LAMP
	dw MELTING_RED_SHADOW
	dw DARK_KING_ABYSS
	dw BIG_EYE
	dw CLAW_REACHER
	dw MASKED_CLOWN
	dw EYEARMOR
	dw GATE_DEEG
	dw SYNCHAR
	dw TERRA_THE_TERRIBLE
	dw DORON
	dw ARCHFIEND_MARMOT
	dw TWIN_LONG_RODS_1
	dw SOLITUDE
	dw TRAP_MASTER
	dw SKULL_STALKER
	dw WOOD_CLOWN
	dw ONE_WHO_HUNTS_SOUL
	dw ROCK_OGRE_GROTTO2
	dw MEGIRUS_LIGHT
	dw MYSTIC_CLOWN
	dw GATEKEEPER
	dw OGRE_OF_THE_BLACK
	dw BIO_PLANT
	dw YARANZO
	dw SUPER_WAR_LION
	dw THREE_LEGGED_ZOMBIES
	dw -1 ; end

CardList_26e60:
	dw HITOTSU_ME_GIANT
	dw BABY_DRAGON
	dw RYU_KISHIN
	dw FERAL_IMP
	dw SWAMP_BATTLEGUARD
	dw TYHONE
	dw ROCK_OGRE_GROTTO1
	dw CURSE_OF_DRAGON
	dw WATTKID
	dw GRIFFORE
	dw BIG_INSECT
	dw BASIC_INSECT
	dw ARMORED_LIZARD
	dw HERCULES_BEETLE
	dw KILLER_NEEDLE
	dw GOKIBORE
	dw GIANT_FLEA
	dw LARVAE_MOTH
	dw GREAT_MOTH
	dw SILVER_FANG
	dw PERFECT_GREAT_MOTH
	dw GAROOZIS
	dw COCOON_EVOLUTION
	dw SOLDIER_OF_STONE
	dw KROKODILUS
	dw GRAPPLER
	dw MEGAZOWLER
	dw URABY
	dw CRAWLING_DRAGON_2
	dw KING_OF_YAMIMAKAI
	dw DARK_CHIMERA
	dw METAL_GUARDIAN
	dw CATAPULT_TURTLE
	dw MYSTIC_HORSEMAN
	dw RABID_HORSEMAN
	dw CRAWLING_DRAGON
	dw DRAGON_ZOMBIE
	dw TOMOZAURUS
	dw THAT_WHICH_FEEDS
	dw DARK_GRAY
	dw NIGHTMARE_SCORPION
	dw SLEEPING_LION
	dw FAITH_BIRD
	dw B_EYED_SIL_ZOMBIE
	dw SPIKED_SNAIL
	dw LARVAS
	dw DIG_BEAK
	dw BIG_EYE
	dw ANCIENT_BRAIN
	dw MONSTURTLE
	dw DARK_SHADE
	dw LUCKY_TRINKET
	dw TURTLE_TIGER
	dw MECH_MOLE_ZOMBIE
	dw ARCHFIEND_MARMOT
	dw MABARREL
	dw WINGED_CLEAVER
	dw KUMOOTOKO
	dw MIDNIGHT_FIEND
	dw SKULL_STALKER
	dw MADJINN_GUNN
	dw D_ASSAILANT
	dw WATER_ELEMENT
	dw MEDA_BAT
	dw PREVENT_RAT
	dw GROUND_ATTACKER
	dw PETIT_MOTH
	dw GATEKEEPER
	dw PSYCHIC_KAPPA
	dw ONE_EYED_SHIELD
	dw CYBER_SOLDIER_DARK
	dw KURAMA
	dw TAKRIMINOS
	dw MEGASONIC_EYE
	dw YAMADRON
	dw ZERA_THE_MANT
	dw -1 ; end

CardList_26efa:
	dw BIG_INSECT
	dw BASIC_INSECT
	dw ARMORED_LIZARD
	dw HERCULES_BEETLE
	dw KILLER_NEEDLE
	dw GOKIBORE
	dw GIANT_FLEA
	dw LARVAE_MOTH
	dw GREAT_MOTH
	dw PERFECT_GREAT_MOTH
	dw COCOON_EVOLUTION
	dw NIGHTMARE_SCORPION
	dw SPIKED_SNAIL
	dw WINGED_CLEAVER
	dw KUMOOTOKO
	dw GROUND_ATTACKER
	dw PETIT_MOTH
	dw SERPENT_MARAUDER
	dw MEGASONIC_EYE
	dw -1 ; end

CardList_26f22:
	dw MYSTICAL_ELF
	dw CELTIC_GUARDIAN
	dw ROGUE_DOLL
	dw WATTKID
	dw GYAKUTENNO_MEGAMI
	dw GODDESS_THIRD_EYE
	dw FAITH_BIRD
	dw ORION_THE_BATTLE
	dw LAMOON
	dw NEMURIKO
	dw WEATHER_CONTROL
	dw MONSTER_EGG
	dw SPIRIT_OF_THE_HARP
	dw LUCKY_TRINKET
	dw GENIN
	dw KEY_MACE
	dw HAPPY_LOVER
	dw PETIT_ANGEL
	dw DRYAD
	dw HOURGLASS_OF_LIFE
	dw WATER_ELEMENT
	dw WATER_OMOTICS
	dw NEKOGAL_1
	dw ANGELWITCH
	dw LUNAR_QUEEN_ELZAIM
	dw ANCIENT_TREE
	dw GREEN_PHANTOM_KING
	dw RAY_AND_TEMPERATURE
	dw MYSTICAL_SHEEP_2
	dw SONIC_MAID
	dw FLYING_PENGUIN
	dw FAIRYS_GIFT
	dw -1 ; end

CardList_26f64:
	dw HITOTSU_ME_GIANT
	dw BABY_DRAGON
	dw RYU_KISHIN
	dw FERAL_IMP
	dw WINGED_DRAGON_1
	dw SHADOW_SPECTER
	dw BLACKLAND_DRAGON
	dw SWORD_ARM_DRAGON
	dw BATTLE_STEER
	dw SUMMONED_SKULL
	dw WICKED_WORM_BEAST
	dw SKULL_SERVANT
	dw BEAVER_WARRIOR
	dw MOUNTAIN_WARRIOR
	dw ZOMBIE_WARRIOR
	dw KOUMORI_DRAGON
	dw TWO_HEADED_KING_REX
	dw THE_SNAKE_HAIR
	dw CURSE_OF_DRAGON
	dw GRIFFORE
	dw TORIKE
	dw SANGAN
	dw BIG_INSECT
	dw ARMORED_LIZARD
	dw HERCULES_BEETLE
	dw MAMMOTH_GRAVEYARD
	dw GREAT_WHITE
	dw WOLF
	dw TIGER_AXE
	dw SILVER_FANG
	dw GAROOZIS
	dw KAIRYU_SHIN
	dw KROKODILUS
	dw GRAPPLER
	dw MEGAZOWLER
	dw URABY
	dw CRAWLING_DRAGON_2
	dw KING_OF_YAMIMAKAI
	dw BAROX
	dw DARK_CHIMERA
	dw MYSTIC_HORSEMAN
	dw CRAWLING_DRAGON
	dw CRASS_CLOWN
	dw DRAGON_ZOMBIE
	dw CLOWN_ZOMBIE
	dw PUMPKING_THE_KING
	dw TOMOZAURUS
	dw DARK_GRAY
	dw SLEEPING_LION
	dw DARK_PLANT
	dw ORION_THE_BATTLE
	dw THE_13TH_GRAVE
	dw DRAGON_STATUE
	dw SPIKED_SNAIL
	dw NECROLANCER
	dw AKIHIRON
	dw RHAIMUNDOS_RED
	dw DOKUROIZO_THE_GRIM
	dw MAN_EATER
	dw DIG_BEAK
	dw LISARK
	dw ANCIENT_JAR
	dw DARKFIRE_DRAGON
	dw DARK_KING_ABYSS
	dw PHANTOM_DEWAN
	dw MASKED_CLOWN
	dw GATE_DEEG
	dw SYNCHAR
	dw FUSIONIST
	dw TURTLE_TIGER
	dw MECH_MOLE_ZOMBIE
	dw PETIT_DRAGON
	dw FRENZIED_PANDA
	dw ARCHFIEND_MARMOT
	dw TWIN_LONG_RODS_1
	dw THUNDER_KID
	dw MEOTOKO
	dw TWO_MOUTH_DARKRULER
	dw MIDNIGHT_FIEND
	dw ROAR_OCEAN_SNAKE
	dw SKULL_STALKER
	dw WOOD_REMAINS
	dw RARE_FISH
	dw ONE_WHO_HUNTS_SOUL
	dw MASTER_AND_EXPERT
	dw NEKOGAL_1
	dw PREVENT_RAT
	dw STONE_ARMADILLER
	dw BEASTKING_OF_SWAMP
	dw FURIOUS_SEA_KING
	dw MYSTICAL_SHEEP_2
	dw SERPENT_MARAUDER
	dw OGRE_OF_THE_BLACK
	dw DRAGON_ERSATZ_HEAD
	dw KURAMA
	dw YARANZO
	dw TAKRIMINOS
	dw STUFFED_ANIMAL
	dw SUPER_WAR_LION
	dw YAMADRON
	dw ZERA_THE_MANT
	dw -1 ; end

CardList_27030:
	dw CATAPULT_TURTLE
	dw MONSTURTLE
	dw TURTLE_TIGER
	dw PSYCHIC_KAPPA
	dw -1 ; end

CardList_2703a:
	dw MUSHROOM_MAN
	dw MAN_EATING_PLANT
	dw CLOWN_ZOMBIE
	dw DARK_PLANT
	dw FIREGRASS
	dw MAN_EATER
	dw ARLOWNAY
	dw DRYAD
	dw WOOD_REMAINS
	dw WODAN_THE_RESIDENT
	dw YASHINOKI
	dw ANCIENT_TREE
	dw GREEN_PHANTOM_KING
	dw -1 ; end

CardList_27056:
	dw SWAMP_BATTLEGUARD
	dw TIME_WIZARD
	dw R_LEG_OF_FORBIDDEN
	dw L_LEG_OF_FORBIDDEN
	dw R_ARM_OF_FORBIDDEN
	dw L_ARM_OF_FORBIDDEN
	dw EXODIA_FORBIDDEN
	dw SUMMONED_SKULL
	dw WICKED_WORM_BEAST
	dw SKULL_SERVANT
	dw HORN_IMP
	dw SAGGI_THE_CLOWN
	dw DARK_MAGICIAN
	dw THE_SNAKE_HAIR
	dw DRAGON_PIPER
	dw ILLUSION_FACELESS
	dw REAPER_OF_THE_CARD
	dw KING_OF_YAMIMAKAI
	dw CRASS_CLOWN
	dw CLOWN_ZOMBIE
	dw PUMPKING_THE_KING
	dw WINGS_OF_FLAME
	dw MASK_OF_DARKNESS
	dw JOB_CHANGE_MIRROR
	dw CURTAIN_OF_DARK
	dw GRAVEYARD_AND_HAND
	dw DOMA_THE_ANGEL
	dw THAT_WHICH_FEEDS
	dw KAMIONWIZARD
	dw THE_13TH_GRAVE
	dw TOAD_MASTER
	dw FLAME_MANIPULATOR
	dw NECROLANCER
	dw BEWITCHING_PHANTOM
	dw SHADOW_WHO_CONTROL
	dw LORD_OF_THE_LAMP
	dw DOKUROIZO_THE_GRIM
	dw FIRE_REAPER
	dw LORD_OF_ZEMIA
	dw MYSTERIOUS_PUPPET
	dw ANCIENT_JAR
	dw DARK_KING_ABYSS
	dw DARK_PRISONER
	dw ANCIENT_BRAIN
	dw FIRE_EYE
	dw PHANTOM_DEWAN
	dw DARK_SHADE
	dw MASKED_CLOWN
	dw AKAKIEISU
	dw THUNDER_KID
	dw AQUA_MADOOR
	dw SOLITUDE
	dw MASKED_SORCERER
	dw TRAP_MASTER
	dw WOOD_CLOWN
	dw DARK_TITAN_TERROR
	dw GUARDIAN_LABYRINTH
	dw ANGELWITCH
	dw ANCIENT_SORCERER
	dw ARCHFIEND_MIRROR
	dw SECTARIAN_SECRET
	dw VERSAGO_DESTROYER
	dw MEGIRUS_LIGHT
	dw GORGON_EGG
	dw HOLOGRAH
	dw TAO_THE_CHANTER
	dw YARANZO
	dw FIENDS_MIRROR
	dw -1 ; end

CardList_270e0:
	dw MYSTICAL_ELF
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw GYAKUTENNO_MEGAMI
	dw GODDESS_THIRD_EYE
	dw DOMA_THE_ANGEL
	dw YAMATANO_SCROLL
	dw ORION_THE_BATTLE
	dw LAMOON
	dw WEATHER_CONTROL
	dw MYSTICAL_CAPTURE
	dw SPIRIT_OF_THE_HARP
	dw ANCIENT_BRAIN
	dw FUSIONIST
	dw KEY_MACE
	dw HAPPY_LOVER
	dw PETIT_ANGEL
	dw DRYAD
	dw HOURGLASS_OF_LIFE
	dw ANGELWITCH
	dw LUNAR_QUEEN_ELZAIM
	dw WING_EGG_ELF
	dw RAY_AND_TEMPERATURE
	dw -1 ; end

CardList_27110:
	dw BABY_DRAGON
	dw WINGED_DRAGON_1
	dw BATTLE_OX
	dw BEAVER_WARRIOR
	dw ROCK_OGRE_GROTTO1
	dw MOUNTAIN_WARRIOR
	dw TWO_HEADED_KING_REX
	dw CURSE_OF_DRAGON
	dw WATTKID
	dw TORIKE
	dw HERCULES_BEETLE
	dw CATAPULT_TURTLE
	dw RABID_HORSEMAN
	dw HERO_OF_THE_EAST
	dw MONSTURTLE
	dw MEOTOKO
	dw MASTER_AND_EXPERT
	dw FURIOUS_SEA_KING
	dw MYSTICAL_SHEEP_2
	dw MOON_ENVOY
	dw DRAGONESS_WICKED
	dw YAMADRON
	dw -1 ; end

CardList_2713e:
	dw RYU_KISHIN
	dw FERAL_IMP
	dw BLACKLAND_DRAGON
	dw SWAMP_BATTLEGUARD
	dw BATTLE_STEER
	dw SUMMONED_SKULL
	dw HORN_IMP
	dw LARVAE_MOTH
	dw GREAT_MOTH
	dw MAMMOTH_GRAVEYARD
	dw PERFECT_GREAT_MOTH
	dw GAROOZIS
	dw MEGAZOWLER
	dw CRAWLING_DRAGON_2
	dw KING_OF_YAMIMAKAI
	dw BAROX
	dw DARK_CHIMERA
	dw ZANKI
	dw JOB_CHANGE_MIRROR
	dw DARK_GRAY
	dw DARK_PLANT
	dw NECROLANCER
	dw RHAIMUNDOS_RED
	dw LORD_OF_ZEMIA
	dw DARK_PRISONER
	dw ANCIENT_BRAIN
	dw CLAW_REACHER
	dw DARK_SHADE
	dw ARCHFIEND_MARMOT
	dw MABARREL
	dw SOLITUDE
	dw MASKED_SORCERER
	dw SKULL_STALKER
	dw WOOD_CLOWN
	dw GUARDIAN_LABYRINTH
	dw VISHWAR_RANDI
	dw MEDA_BAT
	dw UNKNOWN_WARRIOR
	dw MEGASONIC_EYE
	dw ZERA_THE_MANT
	dw -1 ; end

CardList_27190:
	dw B_EYE_WHITE_DRAGON
	dw BABY_DRAGON
	dw WINGED_DRAGON_1
	dw BLACKLAND_DRAGON
	dw SWORD_ARM_DRAGON
	dw KOUMORI_DRAGON
	dw TWO_HEADED_KING_REX
	dw GAIA_DRAGON_CHAMP
	dw CURSE_OF_DRAGON
	dw GRIFFORE
	dw TORIKE
	dw ARMORED_LIZARD
	dw GAROOZIS
	dw THOUSAND_DRAGON
	dw KAIRYU_SHIN
	dw KROKODILUS
	dw GRAPPLER
	dw MEGAZOWLER
	dw URABY
	dw CRAWLING_DRAGON_2
	dw RED_EYES_B_DRAGON
	dw DARK_CHIMERA
	dw CRAWLING_DRAGON
	dw DRAGON_ZOMBIE
	dw TOMOZAURUS
	dw YAMATANO_SCROLL
	dw DRAGON_STATUE
	dw DARKFIRE_DRAGON
	dw SYNCHAR
	dw PETIT_DRAGON
	dw B_SKULL_DRAGON
	dw MIDNIGHT_FIEND
	dw ROAR_OCEAN_SNAKE
	dw DRAGONESS_WICKED
	dw ONE_EYED_SHIELD
	dw DRAGON_ERSATZ_HEAD
	dw KURAMA
	dw TAKRIMINOS
	dw YAMADRON
	dw SEIYARYU
	dw ZERA_THE_MANT
	dw -1 ; end

CardList_271e4:
	dw MYSTICAL_ELF
	dw HITOTSU_ME_GIANT
	dw FERAL_IMP
	dw SWAMP_BATTLEGUARD
	dw HORN_IMP
	dw SAGGI_THE_CLOWN
	dw WATTKID
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw GYAKUTENNO_MEGAMI
	dw MYSTIC_HORSEMAN
	dw SPIRIT_OF_THE_WIND
	dw GODDESS_THIRD_EYE
	dw WHITE_MAGICAL_HAT
	dw DREAM_CLOWN
	dw LAMOON
	dw NEMURIKO
	dw THE_13TH_GRAVE
	dw FIENDS_HAND
	dw MYSTERY_HAND
	dw B_EYED_SIL_ZOMBIE
	dw SPIKED_SNAIL
	dw FLAME_MANIPULATOR
	dw NECROLANCER
	dw DJINN_THE_WATCHER
	dw DARK_KING_ABYSS
	dw SPIRIT_OF_THE_HARP
	dw ARLOWNAY
	dw EYEARMOR
	dw GATE_DEEG
	dw SYNCHAR
	dw KEY_MACE
	dw DORON
	dw TWIN_LONG_RODS_1
	dw PETIT_ANGEL
	dw THUNDER_KID
	dw MEOTOKO
	dw DRYAD
	dw TRAP_MASTER
	dw DARK_TITAN_TERROR
	dw BEAUTIFUL_HEADHUNT
	dw HANIWA
	dw VISHWAR_RANDI
	dw WATER_ELEMENT
	dw WATER_OMOTICS
	dw HYO
	dw ENCHANTING_MERMAID
	dw NEKOGAL_1
	dw ANGELWITCH
	dw EMBRYONIC_BEAST
	dw LUNAR_QUEEN_ELZAIM
	dw PRINCESS_TSURUGI
	dw GREEN_PHANTOM_KING
	dw PROTECTOR_THRONE
	dw MYSTIC_CLOWN
	dw OGRE_OF_THE_BLACK
	dw PSYCHIC_KAPPA
	dw SONIC_MAID
	dw YARANZO
	dw KANAN_THE_SWORD
	dw THREE_LEGGED_ZOMBIES
	dw FAIRYS_GIFT
	dw -1 ; end

CardList_27262:
	dw MYSTICAL_ELF
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw GYAKUTENNO_MEGAMI
	dw SPIRIT_OF_THE_WIND
	dw GODDESS_THIRD_EYE
	dw LAMOON
	dw NEMURIKO
	dw SPIRIT_OF_THE_HARP
	dw ARLOWNAY
	dw KEY_MACE
	dw DRYAD
	dw BEAUTIFUL_HEADHUNT
	dw VISHWAR_RANDI
	dw WATER_ELEMENT
	dw WATER_OMOTICS
	dw ENCHANTING_MERMAID
	dw ANGELWITCH
	dw LUNAR_QUEEN_ELZAIM
	dw PRINCESS_TSURUGI
	dw PROTECTOR_THRONE
	dw SONIC_MAID
	dw -1 ; end

CardList_27290:
	dw FERAL_IMP
	dw SHADOW_SPECTER
	dw BATTLE_STEER
	dw WICKED_WORM_BEAST
	dw BATTLE_OX
	dw BEAVER_WARRIOR
	dw MOUNTAIN_WARRIOR
	dw GRIFFORE
	dw TORIKE
	dw SANGAN
	dw KURIBOH
	dw WOLF
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw TIGER_AXE
	dw SILVER_FANG
	dw BAROX
	dw MYSTIC_HORSEMAN
	dw RABID_HORSEMAN
	dw DARK_GRAY
	dw SLEEPING_LION
	dw DIG_BEAK
	dw LISARK
	dw LORD_OF_ZEMIA
	dw GATE_DEEG
	dw SYNCHAR
	dw FUSIONIST
	dw TURTLE_TIGER
	dw MECH_MOLE_ZOMBIE
	dw HAPPY_LOVER
	dw PENGUIN_KNIGHT
	dw FRENZIED_PANDA
	dw ARCHFIEND_MARMOT
	dw DROLL_BIRD
	dw MEOTOKO
	dw SOLITUDE
	dw RARE_FISH
	dw ONE_WHO_HUNTS_SOUL
	dw MASTER_AND_EXPERT
	dw HYO
	dw NEKOGAL_1
	dw PREVENT_RAT
	dw STONE_ARMADILLER
	dw BEASTKING_OF_SWAMP
	dw WING_EGG_ELF
	dw MYSTICAL_SHEEP_2
	dw OGRE_OF_THE_BLACK
	dw PSYCHIC_KAPPA
	dw BIO_PLANT
	dw KURAMA
	dw STUFFED_ANIMAL
	dw SUPER_WAR_LION
	dw -1 ; end

CardList_272fa:
	dw MYSTICAL_ELF
	dw HITOTSU_ME_GIANT
	dw RYU_KISHIN
	dw SHADOW_SPECTER
	dw SUMMONED_SKULL
	dw SKULL_SERVANT
	dw ZOMBIE_WARRIOR
	dw DRAGON_PIPER
	dw ILLUSION_FACELESS
	dw SANGAN
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw GYAKUTENNO_MEGAMI
	dw CRASS_CLOWN
	dw ARMORED_ZOMBIE
	dw CLOWN_ZOMBIE
	dw PUMPKING_THE_KING
	dw SPIRIT_OF_THE_WIND
	dw GODDESS_THIRD_EYE
	dw DARK_PLANT
	dw LAMOON
	dw NEMURIKO
	dw SPIKED_SNAIL
	dw AKIHIRON
	dw LARVAS
	dw MAN_EATER
	dw LORD_OF_ZEMIA
	dw SPIRIT_OF_THE_HARP
	dw ARLOWNAY
	dw MASKED_CLOWN
	dw GATE_DEEG
	dw SYNCHAR
	dw KEY_MACE
	dw DORON
	dw MECH_MOLE_ZOMBIE
	dw HAPPY_LOVER
	dw FRENZIED_PANDA
	dw TWIN_LONG_RODS_1
	dw DROLL_BIRD
	dw THUNDER_KID
	dw MEOTOKO
	dw DRYAD
	dw KUMOOTOKO
	dw BEAUTIFUL_HEADHUNT
	dw HANIWA
	dw VISHWAR_RANDI
	dw WATER_ELEMENT
	dw WATER_OMOTICS
	dw ENCHANTING_MERMAID
	dw NEKOGAL_1
	dw ANGELWITCH
	dw LUNAR_QUEEN_ELZAIM
	dw PRINCESS_TSURUGI
	dw GREEN_PHANTOM_KING
	dw PROTECTOR_THRONE
	dw SONIC_MAID
	dw KANAN_THE_SWORD
	dw STUFFED_ANIMAL
	dw SUPER_WAR_LION
	dw ZERA_THE_MANT
	dw FAIRYS_GIFT
	dw -1 ; end

CardList_27376:
	dw RYU_KISHIN
	dw SHADOW_SPECTER
	dw SUMMONED_SKULL
	dw SKULL_SERVANT
	dw ZOMBIE_WARRIOR
	dw THE_SNAKE_HAIR
	dw CURSE_OF_DRAGON
	dw GRIFFORE
	dw ARMORED_ZOMBIE
	dw DRAGON_ZOMBIE
	dw CLOWN_ZOMBIE
	dw PUMPKING_THE_KING
	dw MASK_OF_DARKNESS
	dw JOB_CHANGE_MIRROR
	dw CURTAIN_OF_DARK
	dw GRAVEYARD_AND_HAND
	dw THAT_WHICH_FEEDS
	dw TRIAL_OF_NIGHTMARE
	dw YAMATANO_SCROLL
	dw THE_13TH_GRAVE
	dw FIENDS_HAND
	dw MYSTERY_HAND
	dw B_EYED_SIL_ZOMBIE
	dw TOAD_MASTER
	dw SPIKED_SNAIL
	dw TEMPLE_OF_SKULLS
	dw DOKUROIZO_THE_GRIM
	dw FIRE_REAPER
	dw ANCIENT_JAR
	dw DARK_PRISONER
	dw PHANTOM_DEWAN
	dw MECH_MOLE_ZOMBIE
	dw PHANTOM_GHOST
	dw FLAME_GHOST
	dw WOOD_REMAINS
	dw D_ASSAILANT
	dw EMBRYONIC_BEAST
	dw ARCHFIEND_MIRROR
	dw SECTARIAN_SECRET
	dw VERSAGO_DESTROYER
	dw MEGIRUS_LIGHT
	dw GORGON_EGG
	dw YARANZO
	dw THREE_LEGGED_ZOMBIES
	dw FIENDS_MIRROR
	dw -1 ; end

CardList_273d2:
	dw MYSTICAL_ELF
	dw TIME_WIZARD
	dw JUDGE_MAN
	dw CELTIC_GUARDIAN
	dw ILLUSION_FACELESS
	dw ROGUE_DOLL
	dw WATTKID
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw GYAKUTENNO_MEGAMI
	dw SPIRIT_OF_THE_WIND
	dw GODDESS_THIRD_EYE
	dw WHITE_MAGICAL_HAT
	dw SPIRIT_OF_THE_BOOK
	dw DREAM_CLOWN
	dw YAMATANO_SCROLL
	dw ORION_THE_BATTLE
	dw LAMOON
	dw NEMURIKO
	dw WEATHER_CONTROL
	dw MYSTICAL_CAPTURE
	dw FLAME_MANIPULATOR
	dw NECROLANCER
	dw DJINN_THE_WATCHER
	dw BEWITCHING_PHANTOM
	dw THE_JUDGEMENT_HAND
	dw SPIRIT_OF_THE_HARP
	dw HURRICAIL
	dw LUCKY_TRINKET
	dw GENIN
	dw KEY_MACE
	dw HAPPY_LOVER
	dw PETIT_ANGEL
	dw AQUA_MADOOR
	dw DRYAD
	dw WODAN_THE_RESIDENT
	dw WATER_ELEMENT
	dw LUNAR_QUEEN_ELZAIM
	dw WING_EGG_ELF
	dw FURIOUS_SEA_KING
	dw WETHA
	dw ANCIENT_TREE
	dw GREEN_PHANTOM_KING
	dw RAY_AND_TEMPERATURE
	dw PROTECTOR_THRONE
	dw MYSTICAL_SHEEP_2
	dw PSYCHIC_KAPPA
	dw SONIC_MAID
	dw FAIRYS_GIFT
	dw -1 ; end

CardList_27436:
	dw MUSHROOM_MAN
	dw SHADOW_SPECTER
	dw FLAME_SWORDSMAN
	dw ROCK_OGRE_GROTTO1
	dw DRAGON_PIPER
	dw WATTKID
	dw KURIBOH
	dw FIEND_KRAKEN
	dw JELLYFISH
	dw KAIRYU_SHIN
	dw SOLDIER_OF_STONE
	dw MAN_EATING_PLANT
	dw CASTLE_OF_DARK
	dw DRAGON_ZOMBIE
	dw PUMPKING_THE_KING
	dw WINGS_OF_FLAME
	dw MASK_OF_DARKNESS
	dw JOB_CHANGE_MIRROR
	dw CURTAIN_OF_DARK
	dw SPIRIT_OF_THE_WIND
	dw GRAVEYARD_AND_HAND
	dw TRIAL_OF_NIGHTMARE
	dw YAMATANO_SCROLL
	dw DARK_PLANT
	dw WEATHER_CONTROL
	dw CHARUBIN_THE_FIRE
	dw MYSTICAL_CAPTURE
	dw FIENDS_HAND
	dw MYSTERY_HAND
	dw FLAME_MANIPULATOR
	dw TEMPLE_OF_SKULLS
	dw MONSTER_EGG
	dw AKIHIRON
	dw MELTING_RED_SHADOW
	dw FIREGRASS
	dw TAINTED_WISDOM
	dw ANCIENT_JAR
	dw DARKFIRE_DRAGON
	dw BIG_EYE
	dw DARK_PRISONER
	dw HURRICAIL
	dw FIRE_EYE
	dw GENIN
	dw LALA_LI_OON
	dw DOROVER
	dw HINOTAMA_SOUL
	dw THUNDER_KID
	dw KAGEMUSHA_BLUE
	dw FLAME_GHOST
	dw FIEND_SWORD
	dw HITODENCHAK
	dw WOOD_REMAINS
	dw HOURGLASS_OF_LIFE
	dw HANIWA
	dw YASHINOKI
	dw THE_DRDEK
	dw CANDLE_OF_FATE
	dw DISSOLVEROCK
	dw STONE_ARMADILLER
	dw BEASTKING_OF_SWAMP
	dw ARCHFIEND_MIRROR
	dw ROCK_OGRE_GROTTO2
	dw WING_EGG_ELF
	dw ANCIENT_TREE
	dw GROUND_ATTACKER
	dw RAY_AND_TEMPERATURE
	dw GORGON_EGG
	dw KING_FOG
	dw HOLOGRAH
	dw CHANGE_SLIME
	dw FIREYAROU
	dw YARANZO
	dw STUFFED_ANIMAL
	dw MEGASONIC_EYE
	dw MILLENNIUM_SHIELD
	dw FIENDS_MIRROR
	dw -1 ; end

CardList_274d0:
	dw SWAMP_BATTLEGUARD
	dw TYHONE
	dw CATAPULT_TURTLE
	dw ANCIENT_TOOL
	dw M_WARRIOR_1
	dw M_WARRIOR_2
	dw MABARREL
	dw TRAP_MASTER
	dw MADJINN_GUNN
	dw GROUND_ATTACKER
	dw HOLOGRAH
	dw GATEKEEPER
	dw CHANGE_SLIME
	dw CYBER_SOLDIER_DARK
	dw MEGASONIC_EYE
	dw -1 ; end

CardList_274f0:
	dw MUSHROOM_MAN
	dw SWORD_ARM_DRAGON
	dw TYHONE
	dw FLAME_SWORDSMAN
	dw KOUMORI_DRAGON
	dw TWO_HEADED_KING_REX
	dw GRIFFORE
	dw TORIKE
	dw BIG_INSECT
	dw BASIC_INSECT
	dw ARMORED_LIZARD
	dw HERCULES_BEETLE
	dw KILLER_NEEDLE
	dw GOKIBORE
	dw GIANT_FLEA
	dw LARVAE_MOTH
	dw GREAT_MOTH
	dw MAMMOTH_GRAVEYARD
	dw PERFECT_GREAT_MOTH
	dw GAROOZIS
	dw KROKODILUS
	dw GRAPPLER
	dw MEGAZOWLER
	dw URABY
	dw CRAWLING_DRAGON_2
	dw DARK_CHIMERA
	dw WINGS_OF_FLAME
	dw TOMOZAURUS
	dw NIGHTMARE_SCORPION
	dw ANCIENT_TOOL
	dw FLAME_MANIPULATOR
	dw AKIHIRON
	dw RHAIMUNDOS_RED
	dw MELTING_RED_SHADOW
	dw FIRE_REAPER
	dw FIREGRASS
	dw DIG_BEAK
	dw BIG_EYE
	dw FIRE_EYE
	dw SYNCHAR
	dw DORON
	dw ARCHFIEND_MARMOT
	dw MABARREL
	dw TWIN_LONG_RODS_1
	dw WINGED_CLEAVER
	dw HINOTAMA_SOUL
	dw DRYAD
	dw TWO_MOUTH_DARKRULER
	dw HITODENCHAK
	dw CANDLE_OF_FATE
	dw DISSOLVEROCK
	dw ROCK_OGRE_GROTTO2
	dw WING_EGG_ELF
	dw MAVELUS
	dw GROUND_ATTACKER
	dw GORGON_EGG
	dw PETIT_MOTH
	dw SERPENT_MARAUDER
	dw GATEKEEPER
	dw CHANGE_SLIME
	dw FIREYAROU
	dw CYBER_SOLDIER_DARK
	dw YARANZO
	dw STUFFED_ANIMAL
	dw MEGASONIC_EYE
	dw YAMADRON
	dw -1 ; end

CardList_27576:
	dw BABY_DRAGON
	dw RYU_KISHIN
	dw FERAL_IMP
	dw WINGED_DRAGON_1
	dw BLACKLAND_DRAGON
	dw TYHONE
	dw SKULL_SERVANT
	dw KOUMORI_DRAGON
	dw CURSE_OF_DRAGON
	dw ROGUE_DOLL
	dw HERCULES_BEETLE
	dw KILLER_NEEDLE
	dw GREAT_MOTH
	dw HARPIE_LADY
	dw HARPIE_LADY_SISTER
	dw PERFECT_GREAT_MOTH
	dw CASTLE_OF_DARK
	dw REAPER_OF_THE_CARD
	dw BAROX
	dw DARK_CHIMERA
	dw WINGS_OF_FLAME
	dw SPIRIT_OF_THE_WIND
	dw DOMA_THE_ANGEL
	dw THAT_WHICH_FEEDS
	dw DARK_GRAY
	dw SPIRIT_OF_THE_BOOK
	dw FAITH_BIRD
	dw LAMOON
	dw DRAGON_STATUE
	dw DJINN_THE_WATCHER
	dw FIRE_REAPER
	dw LARVAS
	dw LISARK
	dw DARKFIRE_DRAGON
	dw DARK_SHADE
	dw LUCKY_TRINKET
	dw FIEND_REFLECTION2
	dw FUSIONIST
	dw HAPPY_LOVER
	dw PETIT_DRAGON
	dw ARCHFIEND_MARMOT
	dw PHANTOM_GHOST
	dw MABARREL
	dw DROLL_BIRD
	dw PETIT_ANGEL
	dw WINGED_CLEAVER
	dw HINOTAMA_SOUL
	dw FLAME_GHOST
	dw DRYAD
	dw MIDNIGHT_FIEND
	dw HOURGLASS_OF_LIFE
	dw NEKOGAL_1
	dw ANGELWITCH
	dw EMBRYONIC_BEAST
	dw LUNAR_QUEEN_ELZAIM
	dw WING_EGG_ELF
	dw SECTARIAN_SECRET
	dw VERSAGO_DESTROYER
	dw MAVELUS
	dw RAY_AND_TEMPERATURE
	dw KING_FOG
	dw DRAGONESS_WICKED
	dw ONE_EYED_SHIELD
	dw DRAGON_ERSATZ_HEAD
	dw KURAMA
	dw TAKRIMINOS
	dw FLYING_PENGUIN
	dw FAIRYS_GIFT
	dw -1 ; end

CardList_27600:
	dw WATTKID
	dw GREAT_WHITE
	dw FIEND_KRAKEN
	dw JELLYFISH
	dw KAIRYU_SHIN
	dw KROKODILUS
	dw CATAPULT_TURTLE
	dw OCTOBERSER
	dw FIENDS_HAND
	dw TOAD_MASTER
	dw SPIKED_SNAIL
	dw AKIHIRON
	dw MELTING_RED_SHADOW
	dw BIG_EYE
	dw MONSTURTLE
	dw TURTLE_TIGER
	dw TERRA_THE_TERRIBLE
	dw DORON
	dw ARMA_KNIGHT
	dw PENGUIN_KNIGHT
	dw DOROVER
	dw TWIN_LONG_RODS_1
	dw THUNDER_KID
	dw AQUA_MADOOR
	dw ROAR_OCEAN_SNAKE
	dw HITODENCHAK
	dw RARE_FISH
	dw WATER_ELEMENT
	dw ROOT_WATER
	dw WATER_OMOTICS
	dw ENCHANTING_MERMAID
	dw BEASTKING_OF_SWAMP
	dw FURIOUS_SEA_KING
	dw WETHA
	dw CHANGE_SLIME
	dw PSYCHIC_KAPPA
	dw TAKRIMINOS
	dw FLYING_PENGUIN
	dw -1 ; end
