    dw $40 ; wrong bank number

    farcall_table_start
    farfunc Func_1fc004

Func_1fc004::
	push bc
	ld a, [wLoadedCardID + 0]
	ld c, a
	ld a, [wLoadedCardID + 1]
	ld b, a
	ld hl, UncompressedCardGfxPointers
	add hl, bc
	add hl, bc
	ld a, [hli]
	ld e, a
	ld d, [hl]
	ld hl, UncompressedCardGfxBanks
	add hl, bc
	ld a, [hl]
	ld h, d
	ld l, e
	pop de
	jp Func_3f00

UncompressedCardGfxBanks:
	table_width 1
	db BANK(BEyeWhiteDragonGfx_Uncompressed)     ; B_EYE_WHITE_DRAGON
	db BANK(MysticalElfGfx_Uncompressed)         ; MYSTICAL_ELF
	db BANK(HitotsuMeGiantGfx_Uncompressed)      ; HITOTSU_ME_GIANT
	db BANK(BabyDragonGfx_Uncompressed)          ; BABY_DRAGON
	db BANK(RyuKishinGfx_Uncompressed)           ; RYU_KISHIN
	db BANK(FeralImpGfx_Uncompressed)            ; FERAL_IMP
	db BANK(WingedDragon1Gfx_Uncompressed)       ; WINGED_DRAGON_1
	db BANK(MushroomManGfx_Uncompressed)         ; MUSHROOM_MAN
	db BANK(ShadowSpecterGfx_Uncompressed)       ; SHADOW_SPECTER
	db BANK(BlacklandDragonGfx_Uncompressed)     ; BLACKLAND_DRAGON
	db BANK(SwordArmDragonGfx_Uncompressed)      ; SWORD_ARM_DRAGON
	db BANK(SwampBattleguardGfx_Uncompressed)    ; SWAMP_BATTLEGUARD
	db BANK(TyhoneGfx_Uncompressed)              ; TYHONE
	db BANK(BattleSteerGfx_Uncompressed)         ; BATTLE_STEER
	db BANK(FlameSwordsmanGfx_Uncompressed)      ; FLAME_SWORDSMAN
	db BANK(TimeWizardGfx_Uncompressed)          ; TIME_WIZARD
	db BANK(RLegOfForbiddenGfx_Uncompressed)     ; R_LEG_OF_FORBIDDEN
	db BANK(LLegOfForbiddenGfx_Uncompressed)     ; L_LEG_OF_FORBIDDEN
	db BANK(RArmOfForbiddenGfx_Uncompressed)     ; R_ARM_OF_FORBIDDEN
	db BANK(LArmOfForbiddenGfx_Uncompressed)     ; L_ARM_OF_FORBIDDEN
	db BANK(ExodiaForbiddenGfx_Uncompressed)     ; EXODIA_FORBIDDEN
	db BANK(SummonedSkullGfx_Uncompressed)       ; SUMMONED_SKULL
	db BANK(WickedWormBeastGfx_Uncompressed)     ; WICKED_WORM_BEAST
	db BANK(SkullServantGfx_Uncompressed)        ; SKULL_SERVANT
	db BANK(HornImpGfx_Uncompressed)             ; HORN_IMP
	db BANK(BattleOxGfx_Uncompressed)            ; BATTLE_OX
	db BANK(BeaverWarriorGfx_Uncompressed)       ; BEAVER_WARRIOR
	db BANK(RockOgreGrotto1Gfx_Uncompressed)     ; ROCK_OGRE_GROTTO1
	db BANK(MountainWarriorGfx_Uncompressed)     ; MOUNTAIN_WARRIOR
	db BANK(ZombieWarriorGfx_Uncompressed)       ; ZOMBIE_WARRIOR
	db BANK(KoumoriDragonGfx_Uncompressed)       ; KOUMORI_DRAGON
	db BANK(TwoHeadedKingRexGfx_Uncompressed)    ; TWO_HEADED_KING_REX
	db BANK(JudgeManGfx_Uncompressed)            ; JUDGE_MAN
	db BANK(SaggiTheClownGfx_Uncompressed)       ; SAGGI_THE_CLOWN
	db BANK(DarkMagicianGfx_Uncompressed)        ; DARK_MAGICIAN
	db BANK(TheSnakeHairGfx_Uncompressed)        ; THE_SNAKE_HAIR
	db BANK(GaiaDragonChampGfx_Uncompressed)     ; GAIA_DRAGON_CHAMP
	db BANK(GaiaFierceKnightGfx_Uncompressed)    ; GAIA_FIERCE_KNIGHT
	db BANK(CurseOfDragonGfx_Uncompressed)       ; CURSE_OF_DRAGON
	db BANK(DragonPiperGfx_Uncompressed)         ; DRAGON_PIPER
	db BANK(CelticGuardianGfx_Uncompressed)      ; CELTIC_GUARDIAN
	db BANK(IllusionFacelessGfx_Uncompressed)    ; ILLUSION_FACELESS
	db BANK(KarbonalaWarriorGfx_Uncompressed)    ; KARBONALA_WARRIOR
	db BANK(RogueDollGfx_Uncompressed)           ; ROGUE_DOLL
	db BANK(WattkidGfx_Uncompressed)             ; WATTKID
	db BANK(GrifforeGfx_Uncompressed)            ; GRIFFORE
	db BANK(TorikeGfx_Uncompressed)              ; TORIKE
	db BANK(SanganGfx_Uncompressed)              ; SANGAN
	db BANK(BigInsectGfx_Uncompressed)           ; BIG_INSECT
	db BANK(BasicInsectGfx_Uncompressed)         ; BASIC_INSECT
	db BANK(ArmoredLizardGfx_Uncompressed)       ; ARMORED_LIZARD
	db BANK(HerculesBeetleGfx_Uncompressed)      ; HERCULES_BEETLE
	db BANK(KillerNeedleGfx_Uncompressed)        ; KILLER_NEEDLE
	db BANK(GokiboreGfx_Uncompressed)            ; GOKIBORE
	db BANK(GiantFleaGfx_Uncompressed)           ; GIANT_FLEA
	db BANK(LarvaeMothGfx_Uncompressed)          ; LARVAE_MOTH
	db BANK(GreatMothGfx_Uncompressed)           ; GREAT_MOTH
	db BANK(KuribohGfx_Uncompressed)             ; KURIBOH
	db BANK(MammothGraveyardGfx_Uncompressed)    ; MAMMOTH_GRAVEYARD
	db BANK(GreatWhiteGfx_Uncompressed)          ; GREAT_WHITE
	db BANK(WolfGfx_Uncompressed)                ; WOLF
	db BANK(HarpieLadyGfx_Uncompressed)          ; HARPIE_LADY
	db BANK(HarpieLadySisterGfx_Uncompressed)    ; HARPIE_LADY_SISTER
	db BANK(TigerAxeGfx_Uncompressed)            ; TIGER_AXE
	db BANK(SilverFangGfx_Uncompressed)          ; SILVER_FANG
	db BANK(KojikocyGfx_Uncompressed)            ; KOJIKOCY
	db BANK(PerfectGreatMothGfx_Uncompressed)    ; PERFECT_GREAT_MOTH
	db BANK(GaroozisGfx_Uncompressed)            ; GAROOZIS
	db BANK(ThousandDragonGfx_Uncompressed)      ; THOUSAND_DRAGON
	db BANK(FiendKrakenGfx_Uncompressed)         ; FIEND_KRAKEN
	db BANK(JellyfishGfx_Uncompressed)           ; JELLYFISH
	db BANK(CocoonEvolutionGfx_Uncompressed)     ; COCOON_EVOLUTION
	db BANK(KairyuShinGfx_Uncompressed)          ; KAIRYU_SHIN
	db BANK(SoldierOfStoneGfx_Uncompressed)      ; SOLDIER_OF_STONE
	db BANK(ManEatingPlantGfx_Uncompressed)      ; MAN_EATING_PLANT
	db BANK(KrokodilusGfx_Uncompressed)          ; KROKODILUS
	db BANK(GrapplerGfx_Uncompressed)            ; GRAPPLER
	db BANK(AxeRaiderGfx_Uncompressed)           ; AXE_RAIDER
	db BANK(MegazowlerGfx_Uncompressed)          ; MEGAZOWLER
	db BANK(UrabyGfx_Uncompressed)               ; URABY
	db BANK(CrawlingDragon2Gfx_Uncompressed)     ; CRAWLING_DRAGON_2
	db BANK(RedEyesBDragonGfx_Uncompressed)      ; RED_EYES_B_DRAGON
	db BANK(CastleOfDarkGfx_Uncompressed)        ; CASTLE_OF_DARK
	db BANK(ReaperOfTheCardGfx_Uncompressed)     ; REAPER_OF_THE_CARD
	db BANK(KingOfYamimakaiGfx_Uncompressed)     ; KING_OF_YAMIMAKAI
	db BANK(BaroxGfx_Uncompressed)               ; BAROX
	db BANK(DarkChimeraGfx_Uncompressed)         ; DARK_CHIMERA
	db BANK(MetalGuardianGfx_Uncompressed)       ; METAL_GUARDIAN
	db BANK(CatapultTurtleGfx_Uncompressed)      ; CATAPULT_TURTLE
	db BANK(GyakutennoMegamiGfx_Uncompressed)    ; GYAKUTENNO_MEGAMI
	db BANK(MysticHorsemanGfx_Uncompressed)      ; MYSTIC_HORSEMAN
	db BANK(RabidHorsemanGfx_Uncompressed)       ; RABID_HORSEMAN
	db BANK(ZankiGfx_Uncompressed)               ; ZANKI
	db BANK(CrawlingDragonGfx_Uncompressed)      ; CRAWLING_DRAGON
	db BANK(CrassClownGfx_Uncompressed)          ; CRASS_CLOWN
	db BANK(ArmoredZombieGfx_Uncompressed)       ; ARMORED_ZOMBIE
	db BANK(DragonZombieGfx_Uncompressed)        ; DRAGON_ZOMBIE
	db BANK(ClownZombieGfx_Uncompressed)         ; CLOWN_ZOMBIE
	db BANK(PumpkingTheKingGfx_Uncompressed)     ; PUMPKING_THE_KING
	db BANK(BattleWarriorGfx_Uncompressed)       ; BATTLE_WARRIOR
	db BANK(WingsOfFlameGfx_Uncompressed)        ; WINGS_OF_FLAME
	db BANK(MaskOfDarknessGfx_Uncompressed)      ; MASK_OF_DARKNESS
	db BANK(JobChangeMirrorGfx_Uncompressed)     ; JOB_CHANGE_MIRROR
	db BANK(CurtainOfDarkGfx_Uncompressed)       ; CURTAIN_OF_DARK
	db BANK(TomozaurusGfx_Uncompressed)          ; TOMOZAURUS
	db BANK(SpiritOfTheWindGfx_Uncompressed)     ; SPIRIT_OF_THE_WIND
	db BANK(KageningenGfx_Uncompressed)          ; KAGENINGEN
	db BANK(GraveyardAndHandGfx_Uncompressed)    ; GRAVEYARD_AND_HAND
	db BANK(GoddessThirdEyeGfx_Uncompressed)     ; GODDESS_THIRD_EYE
	db BANK(HeroOfTheEastGfx_Uncompressed)       ; HERO_OF_THE_EAST
	db BANK(DomaTheAngelGfx_Uncompressed)        ; DOMA_THE_ANGEL
	db BANK(ThatWhichFeedsGfx_Uncompressed)      ; THAT_WHICH_FEEDS
	db BANK(DarkGrayGfx_Uncompressed)            ; DARK_GRAY
	db BANK(WhiteMagicalHatGfx_Uncompressed)     ; WHITE_MAGICAL_HAT
	db BANK(KamionwizardGfx_Uncompressed)        ; KAMIONWIZARD
	db BANK(NightmareScorpionGfx_Uncompressed)   ; NIGHTMARE_SCORPION
	db BANK(SpiritOfTheBookGfx_Uncompressed)     ; SPIRIT_OF_THE_BOOK
	db BANK(SupporterShadowsGfx_Uncompressed)    ; SUPPORTER_SHADOWS
	db BANK(TrialOfNightmareGfx_Uncompressed)    ; TRIAL_OF_NIGHTMARE
	db BANK(DreamClownGfx_Uncompressed)          ; DREAM_CLOWN
	db BANK(SleepingLionGfx_Uncompressed)        ; SLEEPING_LION
	db BANK(YamatanoScrollGfx_Uncompressed)      ; YAMATANO_SCROLL
	db BANK(DarkPlantGfx_Uncompressed)           ; DARK_PLANT
	db BANK(AncientToolGfx_Uncompressed)         ; ANCIENT_TOOL
	db BANK(FaithBirdGfx_Uncompressed)           ; FAITH_BIRD
	db BANK(OrionTheBattleGfx_Uncompressed)      ; ORION_THE_BATTLE
	db BANK(AnsatsuGfx_Uncompressed)             ; ANSATSU
	db BANK(LamoonGfx_Uncompressed)              ; LAMOON
	db BANK(NemurikoGfx_Uncompressed)            ; NEMURIKO
	db BANK(WeatherControlGfx_Uncompressed)      ; WEATHER_CONTROL
	db BANK(OctoberserGfx_Uncompressed)          ; OCTOBERSER
	db BANK(The13thGraveGfx_Uncompressed)        ; THE_13TH_GRAVE
	db BANK(CharubinTheFireGfx_Uncompressed)     ; CHARUBIN_THE_FIRE
	db BANK(MysticalCaptureGfx_Uncompressed)     ; MYSTICAL_CAPTURE
	db BANK(FiendsHandGfx_Uncompressed)          ; FIENDS_HAND
	db BANK(WittyPhantomGfx_Uncompressed)        ; WITTY_PHANTOM
	db BANK(MysteryHandGfx_Uncompressed)         ; MYSTERY_HAND
	db BANK(DragonStatueGfx_Uncompressed)        ; DRAGON_STATUE
	db BANK(BEyedSilZombieGfx_Uncompressed)      ; B_EYED_SIL_ZOMBIE
	db BANK(ToadMasterGfx_Uncompressed)          ; TOAD_MASTER
	db BANK(SpikedSnailGfx_Uncompressed)         ; SPIKED_SNAIL
	db BANK(FlameManipulatorGfx_Uncompressed)    ; FLAME_MANIPULATOR
	db BANK(NecrolancerGfx_Uncompressed)         ; NECROLANCER
	db BANK(DjinnTheWatcherGfx_Uncompressed)     ; DJINN_THE_WATCHER
	db BANK(BewitchingPhantomGfx_Uncompressed)   ; BEWITCHING_PHANTOM
	db BANK(TempleOfSkullsGfx_Uncompressed)      ; TEMPLE_OF_SKULLS
	db BANK(MonsterEggGfx_Uncompressed)          ; MONSTER_EGG
	db BANK(ShadowWhoControlGfx_Uncompressed)    ; SHADOW_WHO_CONTROL
	db BANK(LordOfTheLampGfx_Uncompressed)       ; LORD_OF_THE_LAMP
	db BANK(AkihironGfx_Uncompressed)            ; AKIHIRON
	db BANK(RhaimundosRedGfx_Uncompressed)       ; RHAIMUNDOS_RED
	db BANK(MeltingRedShadowGfx_Uncompressed)    ; MELTING_RED_SHADOW
	db BANK(DokuroizoTheGrimGfx_Uncompressed)    ; DOKUROIZO_THE_GRIM
	db BANK(FireReaperGfx_Uncompressed)          ; FIRE_REAPER
	db BANK(LarvasGfx_Uncompressed)              ; LARVAS
	db BANK(HardArmorGfx_Uncompressed)           ; HARD_ARMOR
	db BANK(FiregrassGfx_Uncompressed)           ; FIREGRASS
	db BANK(ManEaterGfx_Uncompressed)            ; MAN_EATER
	db BANK(DigBeakGfx_Uncompressed)             ; DIG_BEAK
	db BANK(MWarrior1Gfx_Uncompressed)           ; M_WARRIOR_1
	db BANK(MWarrior2Gfx_Uncompressed)           ; M_WARRIOR_2
	db BANK(TaintedWisdomGfx_Uncompressed)       ; TAINTED_WISDOM
	db BANK(LisarkGfx_Uncompressed)              ; LISARK
	db BANK(LordOfZemiaGfx_Uncompressed)         ; LORD_OF_ZEMIA
	db BANK(TheJudgementHandGfx_Uncompressed)    ; THE_JUDGEMENT_HAND
	db BANK(MysteriousPuppetGfx_Uncompressed)    ; MYSTERIOUS_PUPPET
	db BANK(AncientJarGfx_Uncompressed)          ; ANCIENT_JAR
	db BANK(DarkfireDragonGfx_Uncompressed)      ; DARKFIRE_DRAGON
	db BANK(DarkKingAbyssGfx_Uncompressed)       ; DARK_KING_ABYSS
	db BANK(SpiritOfTheHarpGfx_Uncompressed)     ; SPIRIT_OF_THE_HARP
	db BANK(BigEyeGfx_Uncompressed)              ; BIG_EYE
	db BANK(ArmaillGfx_Uncompressed)             ; ARMAILL
	db BANK(DarkPrisonerGfx_Uncompressed)        ; DARK_PRISONER
	db BANK(HurricailGfx_Uncompressed)           ; HURRICAIL
	db BANK(AncientBrainGfx_Uncompressed)        ; ANCIENT_BRAIN
	db BANK(FireEyeGfx_Uncompressed)             ; FIRE_EYE
	db BANK(MonsturtleGfx_Uncompressed)          ; MONSTURTLE
	db BANK(ClawReacherGfx_Uncompressed)         ; CLAW_REACHER
	db BANK(PhantomDewanGfx_Uncompressed)        ; PHANTOM_DEWAN
	db BANK(ArlownayGfx_Uncompressed)            ; ARLOWNAY
	db BANK(DarkShadeGfx_Uncompressed)           ; DARK_SHADE
	db BANK(MaskedClownGfx_Uncompressed)         ; MASKED_CLOWN
	db BANK(LuckyTrinketGfx_Uncompressed)        ; LUCKY_TRINKET
	db BANK(GeninGfx_Uncompressed)               ; GENIN
	db BANK(EyearmorGfx_Uncompressed)            ; EYEARMOR
	db BANK(FiendReflection2Gfx_Uncompressed)    ; FIEND_REFLECTION2
	db BANK(GateDeegGfx_Uncompressed)            ; GATE_DEEG
	db BANK(SyncharGfx_Uncompressed)             ; SYNCHAR
	db BANK(FusionistGfx_Uncompressed)           ; FUSIONIST
	db BANK(AkakieisuGfx_Uncompressed)           ; AKAKIEISU
	db BANK(LalaLiOonGfx_Uncompressed)           ; LALA_LI_OON
	db BANK(KeyMaceGfx_Uncompressed)             ; KEY_MACE
	db BANK(TurtleTigerGfx_Uncompressed)         ; TURTLE_TIGER
	db BANK(TerraTheTerribleGfx_Uncompressed)    ; TERRA_THE_TERRIBLE
	db BANK(DoronGfx_Uncompressed)               ; DORON
	db BANK(ArmaKnightGfx_Uncompressed)          ; ARMA_KNIGHT
	db BANK(MechMoleZombieGfx_Uncompressed)      ; MECH_MOLE_ZOMBIE
	db BANK(HappyLoverGfx_Uncompressed)          ; HAPPY_LOVER
	db BANK(PenguinKnightGfx_Uncompressed)       ; PENGUIN_KNIGHT
	db BANK(PetitDragonGfx_Uncompressed)         ; PETIT_DRAGON
	db BANK(FrenziedPandaGfx_Uncompressed)       ; FRENZIED_PANDA
	db BANK(ArchfiendMarmotGfx_Uncompressed)     ; ARCHFIEND_MARMOT
	db BANK(PhantomGhostGfx_Uncompressed)        ; PHANTOM_GHOST
	db BANK(MabarrelGfx_Uncompressed)            ; MABARREL
	db BANK(DoroverGfx_Uncompressed)             ; DOROVER
	db BANK(TwinLongRods1Gfx_Uncompressed)       ; TWIN_LONG_RODS_1
	db BANK(DrollBirdGfx_Uncompressed)           ; DROLL_BIRD
	db BANK(PetitAngelGfx_Uncompressed)          ; PETIT_ANGEL
	db BANK(WingedCleaverGfx_Uncompressed)       ; WINGED_CLEAVER
	db BANK(HinotamaSoulGfx_Uncompressed)        ; HINOTAMA_SOUL
	db BANK(ThunderKidGfx_Uncompressed)          ; THUNDER_KID
	db BANK(MeotokoGfx_Uncompressed)             ; MEOTOKO
	db BANK(AquaMadoorGfx_Uncompressed)          ; AQUA_MADOOR
	db BANK(KagemushaBlueGfx_Uncompressed)       ; KAGEMUSHA_BLUE
	db BANK(FlameGhostGfx_Uncompressed)          ; FLAME_GHOST
	db BANK(DryadGfx_Uncompressed)               ; DRYAD
	db BANK(BSkullDragonGfx_Uncompressed)        ; B_SKULL_DRAGON
	db BANK(TwoMouthDarkrulerGfx_Uncompressed)   ; TWO_MOUTH_DARKRULER
	db BANK(SolitudeGfx_Uncompressed)            ; SOLITUDE
	db BANK(MaskedSorcererGfx_Uncompressed)      ; MASKED_SORCERER
	db BANK(KumootokoGfx_Uncompressed)           ; KUMOOTOKO
	db BANK(MidnightFiendGfx_Uncompressed)       ; MIDNIGHT_FIEND
	db BANK(RoarOceanSnakeGfx_Uncompressed)      ; ROAR_OCEAN_SNAKE
	db BANK(TrapMasterGfx_Uncompressed)          ; TRAP_MASTER
	db BANK(FiendSwordGfx_Uncompressed)          ; FIEND_SWORD
	db BANK(SkullStalkerGfx_Uncompressed)        ; SKULL_STALKER
	db BANK(HitodenchakGfx_Uncompressed)         ; HITODENCHAK
	db BANK(WoodRemainsGfx_Uncompressed)         ; WOOD_REMAINS
	db BANK(HourglassOfLifeGfx_Uncompressed)     ; HOURGLASS_OF_LIFE
	db BANK(RareFishGfx_Uncompressed)            ; RARE_FISH
	db BANK(WoodClownGfx_Uncompressed)           ; WOOD_CLOWN
	db BANK(MadjinnGunnGfx_Uncompressed)         ; MADJINN_GUNN
	db BANK(DarkTitanTerrorGfx_Uncompressed)     ; DARK_TITAN_TERROR
	db BANK(BeautifulHeadhuntGfx_Uncompressed)   ; BEAUTIFUL_HEADHUNT
	db BANK(WodanTheResidentGfx_Uncompressed)    ; WODAN_THE_RESIDENT
	db BANK(GuardianLabyrinthGfx_Uncompressed)   ; GUARDIAN_LABYRINTH
	db BANK(HaniwaGfx_Uncompressed)              ; HANIWA
	db BANK(YashinokiGfx_Uncompressed)           ; YASHINOKI
	db BANK(VishwarRandiGfx_Uncompressed)        ; VISHWAR_RANDI
	db BANK(TheDrdekGfx_Uncompressed)            ; THE_DRDEK
	db BANK(DAssailantGfx_Uncompressed)          ; D_ASSAILANT
	db BANK(CandleOfFateGfx_Uncompressed)        ; CANDLE_OF_FATE
	db BANK(WaterElementGfx_Uncompressed)        ; WATER_ELEMENT
	db BANK(DissolverockGfx_Uncompressed)        ; DISSOLVEROCK
	db BANK(MedaBatGfx_Uncompressed)             ; MEDA_BAT
	db BANK(OneWhoHuntsSoulGfx_Uncompressed)     ; ONE_WHO_HUNTS_SOUL
	db BANK(RootWaterGfx_Uncompressed)           ; ROOT_WATER
	db BANK(MasterAndExpertGfx_Uncompressed)     ; MASTER_AND_EXPERT
	db BANK(WaterOmoticsGfx_Uncompressed)        ; WATER_OMOTICS
	db BANK(HyoGfx_Uncompressed)                 ; HYO
	db BANK(EnchantingMermaidGfx_Uncompressed)   ; ENCHANTING_MERMAID
	db BANK(Nekogal1Gfx_Uncompressed)            ; NEKOGAL_1
	db BANK(AngelwitchGfx_Uncompressed)          ; ANGELWITCH
	db BANK(EmbryonicBeastGfx_Uncompressed)      ; EMBRYONIC_BEAST
	db BANK(PreventRatGfx_Uncompressed)          ; PREVENT_RAT
	db BANK(DdWarriorGfx_Uncompressed)           ; DD_WARRIOR
	db BANK(StoneArmadillerGfx_Uncompressed)     ; STONE_ARMADILLER
	db BANK(BeastkingOfSwampGfx_Uncompressed)    ; BEASTKING_OF_SWAMP
	db BANK(AncientSorcererGfx_Uncompressed)     ; ANCIENT_SORCERER
	db BANK(LunarQueenElzaimGfx_Uncompressed)    ; LUNAR_QUEEN_ELZAIM
	db BANK(ArchfiendMirrorGfx_Uncompressed)     ; ARCHFIEND_MIRROR
	db BANK(SwordsmanOfAileGfx_Uncompressed)     ; SWORDSMAN_OF_AILE
	db BANK(RockOgreGrotto2Gfx_Uncompressed)     ; ROCK_OGRE_GROTTO2
	db BANK(WingEggElfGfx_Uncompressed)          ; WING_EGG_ELF
	db BANK(FuriousSeaKingGfx_Uncompressed)      ; FURIOUS_SEA_KING
	db BANK(PrincessTsurugiGfx_Uncompressed)     ; PRINCESS_TSURUGI
	db BANK(UnknownWarriorGfx_Uncompressed)      ; UNKNOWN_WARRIOR
	db BANK(SectarianSecretGfx_Uncompressed)     ; SECTARIAN_SECRET
	db BANK(VersagoDestroyerGfx_Uncompressed)    ; VERSAGO_DESTROYER
	db BANK(WethaGfx_Uncompressed)               ; WETHA
	db BANK(MegirusLightGfx_Uncompressed)        ; MEGIRUS_LIGHT
	db BANK(MavelusGfx_Uncompressed)             ; MAVELUS
	db BANK(AncientTreeGfx_Uncompressed)         ; ANCIENT_TREE
	db BANK(GreenPhantomKingGfx_Uncompressed)    ; GREEN_PHANTOM_KING
	db BANK(GroundAttackerGfx_Uncompressed)      ; GROUND_ATTACKER
	db BANK(RayAndTemperatureGfx_Uncompressed)   ; RAY_AND_TEMPERATURE
	db BANK(GorgonEggGfx_Uncompressed)           ; GORGON_EGG
	db BANK(PetitMothGfx_Uncompressed)           ; PETIT_MOTH
	db BANK(KingFogGfx_Uncompressed)             ; KING_FOG
	db BANK(ProtectorThroneGfx_Uncompressed)     ; PROTECTOR_THRONE
	db BANK(MysticClownGfx_Uncompressed)         ; MYSTIC_CLOWN
	db BANK(MysticalSheep2Gfx_Uncompressed)      ; MYSTICAL_SHEEP_2
	db BANK(HolograhGfx_Uncompressed)            ; HOLOGRAH
	db BANK(TaoTheChanterGfx_Uncompressed)       ; TAO_THE_CHANTER
	db BANK(SerpentMarauderGfx_Uncompressed)     ; SERPENT_MARAUDER
	db BANK(GatekeeperGfx_Uncompressed)          ; GATEKEEPER
	db BANK(OgreOfTheBlackGfx_Uncompressed)      ; OGRE_OF_THE_BLACK
	db BANK(DarkArtistGfx_Uncompressed)          ; DARK_ARTIST
	db BANK(ChangeSlimeGfx_Uncompressed)         ; CHANGE_SLIME
	db BANK(MoonEnvoyGfx_Uncompressed)           ; MOON_ENVOY
	db BANK(FireyarouGfx_Uncompressed)           ; FIREYAROU
	db BANK(PsychicKappaGfx_Uncompressed)        ; PSYCHIC_KAPPA
	db BANK(MasakiTheLegendGfx_Uncompressed)     ; MASAKI_THE_LEGEND
	db BANK(DragonessWickedGfx_Uncompressed)     ; DRAGONESS_WICKED
	db BANK(BioPlantGfx_Uncompressed)            ; BIO_PLANT
	db BANK(OneEyedShieldGfx_Uncompressed)       ; ONE_EYED_SHIELD
	db BANK(CyberSoldierDarkGfx_Uncompressed)    ; CYBER_SOLDIER_DARK
	db BANK(DragonErsatzHeadGfx_Uncompressed)    ; DRAGON_ERSATZ_HEAD
	db BANK(SonicMaidGfx_Uncompressed)           ; SONIC_MAID
	db BANK(KuramaGfx_Uncompressed)              ; KURAMA
	db BANK(LegendarySwordGfx_Uncompressed)      ; LEGENDARY_SWORD
	db BANK(SwordOfDarkGfx_Uncompressed)         ; SWORD_OF_DARK
	db BANK(DarkEnergyGfx_Uncompressed)          ; DARK_ENERGY
	db BANK(AxeOfDespairGfx_Uncompressed)        ; AXE_OF_DESPAIR
	db BANK(LazerCannonArmorGfx_Uncompressed)    ; LAZER_CANNON_ARMOR
	db BANK(InsectArmorLaserGfx_Uncompressed)    ; INSECT_ARMOR_LASER
	db BANK(ElfsLightGfx_Uncompressed)           ; ELFS_LIGHT
	db BANK(BeastFangsGfx_Uncompressed)          ; BEAST_FANGS
	db BANK(SteelShellGfx_Uncompressed)          ; STEEL_SHELL
	db BANK(VileGermsGfx_Uncompressed)           ; VILE_GERMS
	db BANK(BlackPendantGfx_Uncompressed)        ; BLACK_PENDANT
	db BANK(SilverBowAndArrowGfx_Uncompressed)   ; SILVER_BOW_AND_ARROW
	db BANK(HornOfLightGfx_Uncompressed)         ; HORN_OF_LIGHT
	db BANK(HornOfUnicornGfx_Uncompressed)       ; HORN_OF_UNICORN
	db BANK(DragonTreasureGfx_Uncompressed)      ; DRAGON_TREASURE
	db BANK(ElectroWhipGfx_Uncompressed)         ; ELECTRO_WHIP
	db BANK(CyberShieldGfx_Uncompressed)         ; CYBER_SHIELD
	db BANK(ElegantEgotistGfx_Uncompressed)      ; ELEGANT_EGOTIST
	db BANK(MysticalMoonGfx_Uncompressed)        ; MYSTICAL_MOON
	db BANK(StopDefenseGfx_Uncompressed)         ; STOP_DEFENSE
	db BANK(MalevolentNuzzlerGfx_Uncompressed)   ; MALEVOLENT_NUZZLER
	db BANK(VioletCrystalGfx_Uncompressed)       ; VIOLET_CRYSTAL
	db BANK(BookOfSecretArtGfx_Uncompressed)     ; BOOK_OF_SECRET_ART
	db BANK(InvigorationGfx_Uncompressed)        ; INVIGORATION
	db BANK(MachineConversionGfx_Uncompressed)   ; MACHINE_CONVERSION
	db BANK(RaiseBodyHeatGfx_Uncompressed)       ; RAISE_BODY_HEAT
	db BANK(FollowWindGfx_Uncompressed)          ; FOLLOW_WIND
	db BANK(PowerOfKaishinGfx_Uncompressed)      ; POWER_OF_KAISHIN
	db BANK(DragonCaptureJarGfx_Uncompressed)    ; DRAGON_CAPTURE_JAR
	db BANK(ForestGfx_Uncompressed)              ; FOREST
	db BANK(WastelandGfx_Uncompressed)           ; WASTELAND
	db BANK(MountainGfx_Uncompressed)            ; MOUNTAIN
	db BANK(SogenGfx_Uncompressed)               ; SOGEN
	db BANK(UmiGfx_Uncompressed)                 ; UMI
	db BANK(YamiGfx_Uncompressed)                ; YAMI
	db BANK(DarkHoleGfx_Uncompressed)            ; DARK_HOLE
	db BANK(RaigekiGfx_Uncompressed)             ; RAIGEKI
	db BANK(MooyanCurryGfx_Uncompressed)         ; MOOYAN_CURRY
	db BANK(RedMedicineGfx_Uncompressed)         ; RED_MEDICINE
	db BANK(GoblinsRemedyGfx_Uncompressed)       ; GOBLINS_REMEDY
	db BANK(SoulOfThePureGfx_Uncompressed)       ; SOUL_OF_THE_PURE
	db BANK(DianKetoTheCureGfx_Uncompressed)     ; DIAN_KETO_THE_CURE
	db BANK(SparksGfx_Uncompressed)              ; SPARKS
	db BANK(HinotamaGfx_Uncompressed)            ; HINOTAMA
	db BANK(FinalFlameGfx_Uncompressed)          ; FINAL_FLAME
	db BANK(OokaziGfx_Uncompressed)              ; OOKAZI
	db BANK(TremendousFireGfx_Uncompressed)      ; TREMENDOUS_FIRE
	db BANK(SwordsRevealingGfx_Uncompressed)     ; SWORDS_REVEALING
	db BANK(SpellbindCircleGfx_Uncompressed)     ; SPELLBIND_CIRCLE
	db BANK(DarkPierceLightGfx_Uncompressed)     ; DARK_PIERCE_LIGHT
	db BANK(YaranzoGfx_Uncompressed)             ; YARANZO
	db BANK(KananTheSwordGfx_Uncompressed)       ; KANAN_THE_SWORD
	db BANK(TakriminosGfx_Uncompressed)          ; TAKRIMINOS
	db BANK(StuffedAnimalGfx_Uncompressed)       ; STUFFED_ANIMAL
	db BANK(MegasonicEyeGfx_Uncompressed)        ; MEGASONIC_EYE
	db BANK(SuperWarLionGfx_Uncompressed)        ; SUPER_WAR_LION
	db BANK(YamadronGfx_Uncompressed)            ; YAMADRON
	db BANK(SeiyaryuGfx_Uncompressed)            ; SEIYARYU
	db BANK(ThreeLeggedZombiesGfx_Uncompressed)  ; THREE_LEGGED_ZOMBIES
	db BANK(ZeraTheMantGfx_Uncompressed)         ; ZERA_THE_MANT
	db BANK(FlyingPenguinGfx_Uncompressed)       ; FLYING_PENGUIN
	db BANK(MillenniumShieldGfx_Uncompressed)    ; MILLENNIUM_SHIELD
	db BANK(FairysGiftGfx_Uncompressed)          ; FAIRYS_GIFT
	db BANK(BLusterSoldierGfx_Uncompressed)      ; B_LUSTER_SOLDIER
	db BANK(FiendsMirrorGfx_Uncompressed)        ; FIENDS_MIRROR
	db BANK(InvalidCardGfx_Uncompressed)         ; INVALID_CARD
	assert_table_length NUM_CARDS + 1

UncompressedCardGfxPointers:
	table_width 2
	dw BEyeWhiteDragonGfx_Uncompressed     ; B_EYE_WHITE_DRAGON
	dw MysticalElfGfx_Uncompressed         ; MYSTICAL_ELF
	dw HitotsuMeGiantGfx_Uncompressed      ; HITOTSU_ME_GIANT
	dw BabyDragonGfx_Uncompressed          ; BABY_DRAGON
	dw RyuKishinGfx_Uncompressed           ; RYU_KISHIN
	dw FeralImpGfx_Uncompressed            ; FERAL_IMP
	dw WingedDragon1Gfx_Uncompressed       ; WINGED_DRAGON_1
	dw MushroomManGfx_Uncompressed         ; MUSHROOM_MAN
	dw ShadowSpecterGfx_Uncompressed       ; SHADOW_SPECTER
	dw BlacklandDragonGfx_Uncompressed     ; BLACKLAND_DRAGON
	dw SwordArmDragonGfx_Uncompressed      ; SWORD_ARM_DRAGON
	dw SwampBattleguardGfx_Uncompressed    ; SWAMP_BATTLEGUARD
	dw TyhoneGfx_Uncompressed              ; TYHONE
	dw BattleSteerGfx_Uncompressed         ; BATTLE_STEER
	dw FlameSwordsmanGfx_Uncompressed      ; FLAME_SWORDSMAN
	dw TimeWizardGfx_Uncompressed          ; TIME_WIZARD
	dw RLegOfForbiddenGfx_Uncompressed     ; R_LEG_OF_FORBIDDEN
	dw LLegOfForbiddenGfx_Uncompressed     ; L_LEG_OF_FORBIDDEN
	dw RArmOfForbiddenGfx_Uncompressed     ; R_ARM_OF_FORBIDDEN
	dw LArmOfForbiddenGfx_Uncompressed     ; L_ARM_OF_FORBIDDEN
	dw ExodiaForbiddenGfx_Uncompressed     ; EXODIA_FORBIDDEN
	dw SummonedSkullGfx_Uncompressed       ; SUMMONED_SKULL
	dw WickedWormBeastGfx_Uncompressed     ; WICKED_WORM_BEAST
	dw SkullServantGfx_Uncompressed        ; SKULL_SERVANT
	dw HornImpGfx_Uncompressed             ; HORN_IMP
	dw BattleOxGfx_Uncompressed            ; BATTLE_OX
	dw BeaverWarriorGfx_Uncompressed       ; BEAVER_WARRIOR
	dw RockOgreGrotto1Gfx_Uncompressed     ; ROCK_OGRE_GROTTO1
	dw MountainWarriorGfx_Uncompressed     ; MOUNTAIN_WARRIOR
	dw ZombieWarriorGfx_Uncompressed       ; ZOMBIE_WARRIOR
	dw KoumoriDragonGfx_Uncompressed       ; KOUMORI_DRAGON
	dw TwoHeadedKingRexGfx_Uncompressed    ; TWO_HEADED_KING_REX
	dw JudgeManGfx_Uncompressed            ; JUDGE_MAN
	dw SaggiTheClownGfx_Uncompressed       ; SAGGI_THE_CLOWN
	dw DarkMagicianGfx_Uncompressed        ; DARK_MAGICIAN
	dw TheSnakeHairGfx_Uncompressed        ; THE_SNAKE_HAIR
	dw GaiaDragonChampGfx_Uncompressed     ; GAIA_DRAGON_CHAMP
	dw GaiaFierceKnightGfx_Uncompressed    ; GAIA_FIERCE_KNIGHT
	dw CurseOfDragonGfx_Uncompressed       ; CURSE_OF_DRAGON
	dw DragonPiperGfx_Uncompressed         ; DRAGON_PIPER
	dw CelticGuardianGfx_Uncompressed      ; CELTIC_GUARDIAN
	dw IllusionFacelessGfx_Uncompressed    ; ILLUSION_FACELESS
	dw KarbonalaWarriorGfx_Uncompressed    ; KARBONALA_WARRIOR
	dw RogueDollGfx_Uncompressed           ; ROGUE_DOLL
	dw WattkidGfx_Uncompressed             ; WATTKID
	dw GrifforeGfx_Uncompressed            ; GRIFFORE
	dw TorikeGfx_Uncompressed              ; TORIKE
	dw SanganGfx_Uncompressed              ; SANGAN
	dw BigInsectGfx_Uncompressed           ; BIG_INSECT
	dw BasicInsectGfx_Uncompressed         ; BASIC_INSECT
	dw ArmoredLizardGfx_Uncompressed       ; ARMORED_LIZARD
	dw HerculesBeetleGfx_Uncompressed      ; HERCULES_BEETLE
	dw KillerNeedleGfx_Uncompressed        ; KILLER_NEEDLE
	dw GokiboreGfx_Uncompressed            ; GOKIBORE
	dw GiantFleaGfx_Uncompressed           ; GIANT_FLEA
	dw LarvaeMothGfx_Uncompressed          ; LARVAE_MOTH
	dw GreatMothGfx_Uncompressed           ; GREAT_MOTH
	dw KuribohGfx_Uncompressed             ; KURIBOH
	dw MammothGraveyardGfx_Uncompressed    ; MAMMOTH_GRAVEYARD
	dw GreatWhiteGfx_Uncompressed          ; GREAT_WHITE
	dw WolfGfx_Uncompressed                ; WOLF
	dw HarpieLadyGfx_Uncompressed          ; HARPIE_LADY
	dw HarpieLadySisterGfx_Uncompressed    ; HARPIE_LADY_SISTER
	dw TigerAxeGfx_Uncompressed            ; TIGER_AXE
	dw SilverFangGfx_Uncompressed          ; SILVER_FANG
	dw KojikocyGfx_Uncompressed            ; KOJIKOCY
	dw PerfectGreatMothGfx_Uncompressed    ; PERFECT_GREAT_MOTH
	dw GaroozisGfx_Uncompressed            ; GAROOZIS
	dw ThousandDragonGfx_Uncompressed      ; THOUSAND_DRAGON
	dw FiendKrakenGfx_Uncompressed         ; FIEND_KRAKEN
	dw JellyfishGfx_Uncompressed           ; JELLYFISH
	dw CocoonEvolutionGfx_Uncompressed     ; COCOON_EVOLUTION
	dw KairyuShinGfx_Uncompressed          ; KAIRYU_SHIN
	dw SoldierOfStoneGfx_Uncompressed      ; SOLDIER_OF_STONE
	dw ManEatingPlantGfx_Uncompressed      ; MAN_EATING_PLANT
	dw KrokodilusGfx_Uncompressed          ; KROKODILUS
	dw GrapplerGfx_Uncompressed            ; GRAPPLER
	dw AxeRaiderGfx_Uncompressed           ; AXE_RAIDER
	dw MegazowlerGfx_Uncompressed          ; MEGAZOWLER
	dw UrabyGfx_Uncompressed               ; URABY
	dw CrawlingDragon2Gfx_Uncompressed     ; CRAWLING_DRAGON_2
	dw RedEyesBDragonGfx_Uncompressed      ; RED_EYES_B_DRAGON
	dw CastleOfDarkGfx_Uncompressed        ; CASTLE_OF_DARK
	dw ReaperOfTheCardGfx_Uncompressed     ; REAPER_OF_THE_CARD
	dw KingOfYamimakaiGfx_Uncompressed     ; KING_OF_YAMIMAKAI
	dw BaroxGfx_Uncompressed               ; BAROX
	dw DarkChimeraGfx_Uncompressed         ; DARK_CHIMERA
	dw MetalGuardianGfx_Uncompressed       ; METAL_GUARDIAN
	dw CatapultTurtleGfx_Uncompressed      ; CATAPULT_TURTLE
	dw GyakutennoMegamiGfx_Uncompressed    ; GYAKUTENNO_MEGAMI
	dw MysticHorsemanGfx_Uncompressed      ; MYSTIC_HORSEMAN
	dw RabidHorsemanGfx_Uncompressed       ; RABID_HORSEMAN
	dw ZankiGfx_Uncompressed               ; ZANKI
	dw CrawlingDragonGfx_Uncompressed      ; CRAWLING_DRAGON
	dw CrassClownGfx_Uncompressed          ; CRASS_CLOWN
	dw ArmoredZombieGfx_Uncompressed       ; ARMORED_ZOMBIE
	dw DragonZombieGfx_Uncompressed        ; DRAGON_ZOMBIE
	dw ClownZombieGfx_Uncompressed         ; CLOWN_ZOMBIE
	dw PumpkingTheKingGfx_Uncompressed     ; PUMPKING_THE_KING
	dw BattleWarriorGfx_Uncompressed       ; BATTLE_WARRIOR
	dw WingsOfFlameGfx_Uncompressed        ; WINGS_OF_FLAME
	dw MaskOfDarknessGfx_Uncompressed      ; MASK_OF_DARKNESS
	dw JobChangeMirrorGfx_Uncompressed     ; JOB_CHANGE_MIRROR
	dw CurtainOfDarkGfx_Uncompressed       ; CURTAIN_OF_DARK
	dw TomozaurusGfx_Uncompressed          ; TOMOZAURUS
	dw SpiritOfTheWindGfx_Uncompressed     ; SPIRIT_OF_THE_WIND
	dw KageningenGfx_Uncompressed          ; KAGENINGEN
	dw GraveyardAndHandGfx_Uncompressed    ; GRAVEYARD_AND_HAND
	dw GoddessThirdEyeGfx_Uncompressed     ; GODDESS_THIRD_EYE
	dw HeroOfTheEastGfx_Uncompressed       ; HERO_OF_THE_EAST
	dw DomaTheAngelGfx_Uncompressed        ; DOMA_THE_ANGEL
	dw ThatWhichFeedsGfx_Uncompressed      ; THAT_WHICH_FEEDS
	dw DarkGrayGfx_Uncompressed            ; DARK_GRAY
	dw WhiteMagicalHatGfx_Uncompressed     ; WHITE_MAGICAL_HAT
	dw KamionwizardGfx_Uncompressed        ; KAMIONWIZARD
	dw NightmareScorpionGfx_Uncompressed   ; NIGHTMARE_SCORPION
	dw SpiritOfTheBookGfx_Uncompressed     ; SPIRIT_OF_THE_BOOK
	dw SupporterShadowsGfx_Uncompressed    ; SUPPORTER_SHADOWS
	dw TrialOfNightmareGfx_Uncompressed    ; TRIAL_OF_NIGHTMARE
	dw DreamClownGfx_Uncompressed          ; DREAM_CLOWN
	dw SleepingLionGfx_Uncompressed        ; SLEEPING_LION
	dw YamatanoScrollGfx_Uncompressed      ; YAMATANO_SCROLL
	dw DarkPlantGfx_Uncompressed           ; DARK_PLANT
	dw AncientToolGfx_Uncompressed         ; ANCIENT_TOOL
	dw FaithBirdGfx_Uncompressed           ; FAITH_BIRD
	dw OrionTheBattleGfx_Uncompressed      ; ORION_THE_BATTLE
	dw AnsatsuGfx_Uncompressed             ; ANSATSU
	dw LamoonGfx_Uncompressed              ; LAMOON
	dw NemurikoGfx_Uncompressed            ; NEMURIKO
	dw WeatherControlGfx_Uncompressed      ; WEATHER_CONTROL
	dw OctoberserGfx_Uncompressed          ; OCTOBERSER
	dw The13thGraveGfx_Uncompressed        ; THE_13TH_GRAVE
	dw CharubinTheFireGfx_Uncompressed     ; CHARUBIN_THE_FIRE
	dw MysticalCaptureGfx_Uncompressed     ; MYSTICAL_CAPTURE
	dw FiendsHandGfx_Uncompressed          ; FIENDS_HAND
	dw WittyPhantomGfx_Uncompressed        ; WITTY_PHANTOM
	dw MysteryHandGfx_Uncompressed         ; MYSTERY_HAND
	dw DragonStatueGfx_Uncompressed        ; DRAGON_STATUE
	dw BEyedSilZombieGfx_Uncompressed      ; B_EYED_SIL_ZOMBIE
	dw ToadMasterGfx_Uncompressed          ; TOAD_MASTER
	dw SpikedSnailGfx_Uncompressed         ; SPIKED_SNAIL
	dw FlameManipulatorGfx_Uncompressed    ; FLAME_MANIPULATOR
	dw NecrolancerGfx_Uncompressed         ; NECROLANCER
	dw DjinnTheWatcherGfx_Uncompressed     ; DJINN_THE_WATCHER
	dw BewitchingPhantomGfx_Uncompressed   ; BEWITCHING_PHANTOM
	dw TempleOfSkullsGfx_Uncompressed      ; TEMPLE_OF_SKULLS
	dw MonsterEggGfx_Uncompressed          ; MONSTER_EGG
	dw ShadowWhoControlGfx_Uncompressed    ; SHADOW_WHO_CONTROL
	dw LordOfTheLampGfx_Uncompressed       ; LORD_OF_THE_LAMP
	dw AkihironGfx_Uncompressed            ; AKIHIRON
	dw RhaimundosRedGfx_Uncompressed       ; RHAIMUNDOS_RED
	dw MeltingRedShadowGfx_Uncompressed    ; MELTING_RED_SHADOW
	dw DokuroizoTheGrimGfx_Uncompressed    ; DOKUROIZO_THE_GRIM
	dw FireReaperGfx_Uncompressed          ; FIRE_REAPER
	dw LarvasGfx_Uncompressed              ; LARVAS
	dw HardArmorGfx_Uncompressed           ; HARD_ARMOR
	dw FiregrassGfx_Uncompressed           ; FIREGRASS
	dw ManEaterGfx_Uncompressed            ; MAN_EATER
	dw DigBeakGfx_Uncompressed             ; DIG_BEAK
	dw MWarrior1Gfx_Uncompressed           ; M_WARRIOR_1
	dw MWarrior2Gfx_Uncompressed           ; M_WARRIOR_2
	dw TaintedWisdomGfx_Uncompressed       ; TAINTED_WISDOM
	dw LisarkGfx_Uncompressed              ; LISARK
	dw LordOfZemiaGfx_Uncompressed         ; LORD_OF_ZEMIA
	dw TheJudgementHandGfx_Uncompressed    ; THE_JUDGEMENT_HAND
	dw MysteriousPuppetGfx_Uncompressed    ; MYSTERIOUS_PUPPET
	dw AncientJarGfx_Uncompressed          ; ANCIENT_JAR
	dw DarkfireDragonGfx_Uncompressed      ; DARKFIRE_DRAGON
	dw DarkKingAbyssGfx_Uncompressed       ; DARK_KING_ABYSS
	dw SpiritOfTheHarpGfx_Uncompressed     ; SPIRIT_OF_THE_HARP
	dw BigEyeGfx_Uncompressed              ; BIG_EYE
	dw ArmaillGfx_Uncompressed             ; ARMAILL
	dw DarkPrisonerGfx_Uncompressed        ; DARK_PRISONER
	dw HurricailGfx_Uncompressed           ; HURRICAIL
	dw AncientBrainGfx_Uncompressed        ; ANCIENT_BRAIN
	dw FireEyeGfx_Uncompressed             ; FIRE_EYE
	dw MonsturtleGfx_Uncompressed          ; MONSTURTLE
	dw ClawReacherGfx_Uncompressed         ; CLAW_REACHER
	dw PhantomDewanGfx_Uncompressed        ; PHANTOM_DEWAN
	dw ArlownayGfx_Uncompressed            ; ARLOWNAY
	dw DarkShadeGfx_Uncompressed           ; DARK_SHADE
	dw MaskedClownGfx_Uncompressed         ; MASKED_CLOWN
	dw LuckyTrinketGfx_Uncompressed        ; LUCKY_TRINKET
	dw GeninGfx_Uncompressed               ; GENIN
	dw EyearmorGfx_Uncompressed            ; EYEARMOR
	dw FiendReflection2Gfx_Uncompressed    ; FIEND_REFLECTION2
	dw GateDeegGfx_Uncompressed            ; GATE_DEEG
	dw SyncharGfx_Uncompressed             ; SYNCHAR
	dw FusionistGfx_Uncompressed           ; FUSIONIST
	dw AkakieisuGfx_Uncompressed           ; AKAKIEISU
	dw LalaLiOonGfx_Uncompressed           ; LALA_LI_OON
	dw KeyMaceGfx_Uncompressed             ; KEY_MACE
	dw TurtleTigerGfx_Uncompressed         ; TURTLE_TIGER
	dw TerraTheTerribleGfx_Uncompressed    ; TERRA_THE_TERRIBLE
	dw DoronGfx_Uncompressed               ; DORON
	dw ArmaKnightGfx_Uncompressed          ; ARMA_KNIGHT
	dw MechMoleZombieGfx_Uncompressed      ; MECH_MOLE_ZOMBIE
	dw HappyLoverGfx_Uncompressed          ; HAPPY_LOVER
	dw PenguinKnightGfx_Uncompressed       ; PENGUIN_KNIGHT
	dw PetitDragonGfx_Uncompressed         ; PETIT_DRAGON
	dw FrenziedPandaGfx_Uncompressed       ; FRENZIED_PANDA
	dw ArchfiendMarmotGfx_Uncompressed     ; ARCHFIEND_MARMOT
	dw PhantomGhostGfx_Uncompressed        ; PHANTOM_GHOST
	dw MabarrelGfx_Uncompressed            ; MABARREL
	dw DoroverGfx_Uncompressed             ; DOROVER
	dw TwinLongRods1Gfx_Uncompressed       ; TWIN_LONG_RODS_1
	dw DrollBirdGfx_Uncompressed           ; DROLL_BIRD
	dw PetitAngelGfx_Uncompressed          ; PETIT_ANGEL
	dw WingedCleaverGfx_Uncompressed       ; WINGED_CLEAVER
	dw HinotamaSoulGfx_Uncompressed        ; HINOTAMA_SOUL
	dw ThunderKidGfx_Uncompressed          ; THUNDER_KID
	dw MeotokoGfx_Uncompressed             ; MEOTOKO
	dw AquaMadoorGfx_Uncompressed          ; AQUA_MADOOR
	dw KagemushaBlueGfx_Uncompressed       ; KAGEMUSHA_BLUE
	dw FlameGhostGfx_Uncompressed          ; FLAME_GHOST
	dw DryadGfx_Uncompressed               ; DRYAD
	dw BSkullDragonGfx_Uncompressed        ; B_SKULL_DRAGON
	dw TwoMouthDarkrulerGfx_Uncompressed   ; TWO_MOUTH_DARKRULER
	dw SolitudeGfx_Uncompressed            ; SOLITUDE
	dw MaskedSorcererGfx_Uncompressed      ; MASKED_SORCERER
	dw KumootokoGfx_Uncompressed           ; KUMOOTOKO
	dw MidnightFiendGfx_Uncompressed       ; MIDNIGHT_FIEND
	dw RoarOceanSnakeGfx_Uncompressed      ; ROAR_OCEAN_SNAKE
	dw TrapMasterGfx_Uncompressed          ; TRAP_MASTER
	dw FiendSwordGfx_Uncompressed          ; FIEND_SWORD
	dw SkullStalkerGfx_Uncompressed        ; SKULL_STALKER
	dw HitodenchakGfx_Uncompressed         ; HITODENCHAK
	dw WoodRemainsGfx_Uncompressed         ; WOOD_REMAINS
	dw HourglassOfLifeGfx_Uncompressed     ; HOURGLASS_OF_LIFE
	dw RareFishGfx_Uncompressed            ; RARE_FISH
	dw WoodClownGfx_Uncompressed           ; WOOD_CLOWN
	dw MadjinnGunnGfx_Uncompressed         ; MADJINN_GUNN
	dw DarkTitanTerrorGfx_Uncompressed     ; DARK_TITAN_TERROR
	dw BeautifulHeadhuntGfx_Uncompressed   ; BEAUTIFUL_HEADHUNT
	dw WodanTheResidentGfx_Uncompressed    ; WODAN_THE_RESIDENT
	dw GuardianLabyrinthGfx_Uncompressed   ; GUARDIAN_LABYRINTH
	dw HaniwaGfx_Uncompressed              ; HANIWA
	dw YashinokiGfx_Uncompressed           ; YASHINOKI
	dw VishwarRandiGfx_Uncompressed        ; VISHWAR_RANDI
	dw TheDrdekGfx_Uncompressed            ; THE_DRDEK
	dw DAssailantGfx_Uncompressed          ; D_ASSAILANT
	dw CandleOfFateGfx_Uncompressed        ; CANDLE_OF_FATE
	dw WaterElementGfx_Uncompressed        ; WATER_ELEMENT
	dw DissolverockGfx_Uncompressed        ; DISSOLVEROCK
	dw MedaBatGfx_Uncompressed             ; MEDA_BAT
	dw OneWhoHuntsSoulGfx_Uncompressed     ; ONE_WHO_HUNTS_SOUL
	dw RootWaterGfx_Uncompressed           ; ROOT_WATER
	dw MasterAndExpertGfx_Uncompressed     ; MASTER_AND_EXPERT
	dw WaterOmoticsGfx_Uncompressed        ; WATER_OMOTICS
	dw HyoGfx_Uncompressed                 ; HYO
	dw EnchantingMermaidGfx_Uncompressed   ; ENCHANTING_MERMAID
	dw Nekogal1Gfx_Uncompressed            ; NEKOGAL_1
	dw AngelwitchGfx_Uncompressed          ; ANGELWITCH
	dw EmbryonicBeastGfx_Uncompressed      ; EMBRYONIC_BEAST
	dw PreventRatGfx_Uncompressed          ; PREVENT_RAT
	dw DdWarriorGfx_Uncompressed           ; DD_WARRIOR
	dw StoneArmadillerGfx_Uncompressed     ; STONE_ARMADILLER
	dw BeastkingOfSwampGfx_Uncompressed    ; BEASTKING_OF_SWAMP
	dw AncientSorcererGfx_Uncompressed     ; ANCIENT_SORCERER
	dw LunarQueenElzaimGfx_Uncompressed    ; LUNAR_QUEEN_ELZAIM
	dw ArchfiendMirrorGfx_Uncompressed     ; ARCHFIEND_MIRROR
	dw SwordsmanOfAileGfx_Uncompressed     ; SWORDSMAN_OF_AILE
	dw RockOgreGrotto2Gfx_Uncompressed     ; ROCK_OGRE_GROTTO2
	dw WingEggElfGfx_Uncompressed          ; WING_EGG_ELF
	dw FuriousSeaKingGfx_Uncompressed      ; FURIOUS_SEA_KING
	dw PrincessTsurugiGfx_Uncompressed     ; PRINCESS_TSURUGI
	dw UnknownWarriorGfx_Uncompressed      ; UNKNOWN_WARRIOR
	dw SectarianSecretGfx_Uncompressed     ; SECTARIAN_SECRET
	dw VersagoDestroyerGfx_Uncompressed    ; VERSAGO_DESTROYER
	dw WethaGfx_Uncompressed               ; WETHA
	dw MegirusLightGfx_Uncompressed        ; MEGIRUS_LIGHT
	dw MavelusGfx_Uncompressed             ; MAVELUS
	dw AncientTreeGfx_Uncompressed         ; ANCIENT_TREE
	dw GreenPhantomKingGfx_Uncompressed    ; GREEN_PHANTOM_KING
	dw GroundAttackerGfx_Uncompressed      ; GROUND_ATTACKER
	dw RayAndTemperatureGfx_Uncompressed   ; RAY_AND_TEMPERATURE
	dw GorgonEggGfx_Uncompressed           ; GORGON_EGG
	dw PetitMothGfx_Uncompressed           ; PETIT_MOTH
	dw KingFogGfx_Uncompressed             ; KING_FOG
	dw ProtectorThroneGfx_Uncompressed     ; PROTECTOR_THRONE
	dw MysticClownGfx_Uncompressed         ; MYSTIC_CLOWN
	dw MysticalSheep2Gfx_Uncompressed      ; MYSTICAL_SHEEP_2
	dw HolograhGfx_Uncompressed            ; HOLOGRAH
	dw TaoTheChanterGfx_Uncompressed       ; TAO_THE_CHANTER
	dw SerpentMarauderGfx_Uncompressed     ; SERPENT_MARAUDER
	dw GatekeeperGfx_Uncompressed          ; GATEKEEPER
	dw OgreOfTheBlackGfx_Uncompressed      ; OGRE_OF_THE_BLACK
	dw DarkArtistGfx_Uncompressed          ; DARK_ARTIST
	dw ChangeSlimeGfx_Uncompressed         ; CHANGE_SLIME
	dw MoonEnvoyGfx_Uncompressed           ; MOON_ENVOY
	dw FireyarouGfx_Uncompressed           ; FIREYAROU
	dw PsychicKappaGfx_Uncompressed        ; PSYCHIC_KAPPA
	dw MasakiTheLegendGfx_Uncompressed     ; MASAKI_THE_LEGEND
	dw DragonessWickedGfx_Uncompressed     ; DRAGONESS_WICKED
	dw BioPlantGfx_Uncompressed            ; BIO_PLANT
	dw OneEyedShieldGfx_Uncompressed       ; ONE_EYED_SHIELD
	dw CyberSoldierDarkGfx_Uncompressed    ; CYBER_SOLDIER_DARK
	dw DragonErsatzHeadGfx_Uncompressed    ; DRAGON_ERSATZ_HEAD
	dw SonicMaidGfx_Uncompressed           ; SONIC_MAID
	dw KuramaGfx_Uncompressed              ; KURAMA
	dw LegendarySwordGfx_Uncompressed      ; LEGENDARY_SWORD
	dw SwordOfDarkGfx_Uncompressed         ; SWORD_OF_DARK
	dw DarkEnergyGfx_Uncompressed          ; DARK_ENERGY
	dw AxeOfDespairGfx_Uncompressed        ; AXE_OF_DESPAIR
	dw LazerCannonArmorGfx_Uncompressed    ; LAZER_CANNON_ARMOR
	dw InsectArmorLaserGfx_Uncompressed    ; INSECT_ARMOR_LASER
	dw ElfsLightGfx_Uncompressed           ; ELFS_LIGHT
	dw BeastFangsGfx_Uncompressed          ; BEAST_FANGS
	dw SteelShellGfx_Uncompressed          ; STEEL_SHELL
	dw VileGermsGfx_Uncompressed           ; VILE_GERMS
	dw BlackPendantGfx_Uncompressed        ; BLACK_PENDANT
	dw SilverBowAndArrowGfx_Uncompressed   ; SILVER_BOW_AND_ARROW
	dw HornOfLightGfx_Uncompressed         ; HORN_OF_LIGHT
	dw HornOfUnicornGfx_Uncompressed       ; HORN_OF_UNICORN
	dw DragonTreasureGfx_Uncompressed      ; DRAGON_TREASURE
	dw ElectroWhipGfx_Uncompressed         ; ELECTRO_WHIP
	dw CyberShieldGfx_Uncompressed         ; CYBER_SHIELD
	dw ElegantEgotistGfx_Uncompressed      ; ELEGANT_EGOTIST
	dw MysticalMoonGfx_Uncompressed        ; MYSTICAL_MOON
	dw StopDefenseGfx_Uncompressed         ; STOP_DEFENSE
	dw MalevolentNuzzlerGfx_Uncompressed   ; MALEVOLENT_NUZZLER
	dw VioletCrystalGfx_Uncompressed       ; VIOLET_CRYSTAL
	dw BookOfSecretArtGfx_Uncompressed     ; BOOK_OF_SECRET_ART
	dw InvigorationGfx_Uncompressed        ; INVIGORATION
	dw MachineConversionGfx_Uncompressed   ; MACHINE_CONVERSION
	dw RaiseBodyHeatGfx_Uncompressed       ; RAISE_BODY_HEAT
	dw FollowWindGfx_Uncompressed          ; FOLLOW_WIND
	dw PowerOfKaishinGfx_Uncompressed      ; POWER_OF_KAISHIN
	dw DragonCaptureJarGfx_Uncompressed    ; DRAGON_CAPTURE_JAR
	dw ForestGfx_Uncompressed              ; FOREST
	dw WastelandGfx_Uncompressed           ; WASTELAND
	dw MountainGfx_Uncompressed            ; MOUNTAIN
	dw SogenGfx_Uncompressed               ; SOGEN
	dw UmiGfx_Uncompressed                 ; UMI
	dw YamiGfx_Uncompressed                ; YAMI
	dw DarkHoleGfx_Uncompressed            ; DARK_HOLE
	dw RaigekiGfx_Uncompressed             ; RAIGEKI
	dw MooyanCurryGfx_Uncompressed         ; MOOYAN_CURRY
	dw RedMedicineGfx_Uncompressed         ; RED_MEDICINE
	dw GoblinsRemedyGfx_Uncompressed       ; GOBLINS_REMEDY
	dw SoulOfThePureGfx_Uncompressed       ; SOUL_OF_THE_PURE
	dw DianKetoTheCureGfx_Uncompressed     ; DIAN_KETO_THE_CURE
	dw SparksGfx_Uncompressed              ; SPARKS
	dw HinotamaGfx_Uncompressed            ; HINOTAMA
	dw FinalFlameGfx_Uncompressed          ; FINAL_FLAME
	dw OokaziGfx_Uncompressed              ; OOKAZI
	dw TremendousFireGfx_Uncompressed      ; TREMENDOUS_FIRE
	dw SwordsRevealingGfx_Uncompressed     ; SWORDS_REVEALING
	dw SpellbindCircleGfx_Uncompressed     ; SPELLBIND_CIRCLE
	dw DarkPierceLightGfx_Uncompressed     ; DARK_PIERCE_LIGHT
	dw YaranzoGfx_Uncompressed             ; YARANZO
	dw KananTheSwordGfx_Uncompressed       ; KANAN_THE_SWORD
	dw TakriminosGfx_Uncompressed          ; TAKRIMINOS
	dw StuffedAnimalGfx_Uncompressed       ; STUFFED_ANIMAL
	dw MegasonicEyeGfx_Uncompressed        ; MEGASONIC_EYE
	dw SuperWarLionGfx_Uncompressed        ; SUPER_WAR_LION
	dw YamadronGfx_Uncompressed            ; YAMADRON
	dw SeiyaryuGfx_Uncompressed            ; SEIYARYU
	dw ThreeLeggedZombiesGfx_Uncompressed  ; THREE_LEGGED_ZOMBIES
	dw ZeraTheMantGfx_Uncompressed         ; ZERA_THE_MANT
	dw FlyingPenguinGfx_Uncompressed       ; FLYING_PENGUIN
	dw MillenniumShieldGfx_Uncompressed    ; MILLENNIUM_SHIELD
	dw FairysGiftGfx_Uncompressed          ; FAIRYS_GIFT
	dw BLusterSoldierGfx_Uncompressed      ; B_LUSTER_SOLDIER
	dw FiendsMirrorGfx_Uncompressed        ; FIENDS_MIRROR
	dw InvalidCardGfx_Uncompressed         ; INVALID_CARD
	assert_table_length NUM_CARDS + 1
