CardNamePointersJp:
	table_width 2
	dw BEyeWhiteDragonNameJp    ; B_EYE_WHITE_DRAGON
	dw MysticalElfNameJp        ; MYSTICAL_ELF
	dw HitotsuMeGiantNameJp     ; HITOTSU_ME_GIANT
	dw BabyDragonNameJp         ; BABY_DRAGON
	dw RyuKishinNameJp          ; RYU_KISHIN
	dw FeralImpNameJp           ; FERAL_IMP
	dw WingedDragon1NameJp      ; WINGED_DRAGON_1
	dw MushroomManNameJp        ; MUSHROOM_MAN
	dw ShadowSpecterNameJp      ; SHADOW_SPECTER
	dw BlacklandDragonNameJp    ; BLACKLAND_DRAGON
	dw SwordArmDragonNameJp     ; SWORD_ARM_DRAGON
	dw SwampBattleguardNameJp   ; SWAMP_BATTLEGUARD
	dw TyhoneNameJp             ; TYHONE
	dw BattleSteerNameJp        ; BATTLE_STEER
	dw FlameSwordsmanNameJp     ; FLAME_SWORDSMAN
	dw TimeWizardNameJp         ; TIME_WIZARD
	dw RLegOfForbiddenNameJp    ; R_LEG_OF_FORBIDDEN
	dw LLegOfForbiddenNameJp    ; L_LEG_OF_FORBIDDEN
	dw RArmOfForbiddenNameJp    ; R_ARM_OF_FORBIDDEN
	dw LArmOfForbiddenNameJp    ; L_ARM_OF_FORBIDDEN
	dw ExodiaForbiddenNameJp    ; EXODIA_FORBIDDEN
	dw SummonedSkullNameJp      ; SUMMONED_SKULL
	dw WickedWormBeastNameJp    ; WICKED_WORM_BEAST
	dw SkullServantNameJp       ; SKULL_SERVANT
	dw HornImpNameJp            ; HORN_IMP
	dw BattleOxNameJp           ; BATTLE_OX
	dw BeaverWarriorNameJp      ; BEAVER_WARRIOR
	dw RockOgreGrotto1NameJp    ; ROCK_OGRE_GROTTO1
	dw MountainWarriorNameJp    ; MOUNTAIN_WARRIOR
	dw ZombieWarriorNameJp      ; ZOMBIE_WARRIOR
	dw KoumoriDragonNameJp      ; KOUMORI_DRAGON
	dw TwoHeadedKingRexNameJp   ; TWO_HEADED_KING_REX
	dw JudgeManNameJp           ; JUDGE_MAN
	dw SaggiTheClownNameJp      ; SAGGI_THE_CLOWN
	dw DarkMagicianNameJp       ; DARK_MAGICIAN
	dw TheSnakeHairNameJp       ; THE_SNAKE_HAIR
	dw GaiaDragonChampNameJp    ; GAIA_DRAGON_CHAMP
	dw GaiaFierceKnightNameJp   ; GAIA_FIERCE_KNIGHT
	dw CurseOfDragonNameJp      ; CURSE_OF_DRAGON
	dw DragonPiperNameJp        ; DRAGON_PIPER
	dw CelticGuardianNameJp     ; CELTIC_GUARDIAN
	dw IllusionFacelessNameJp   ; ILLUSION_FACELESS
	dw KarbonalaWarriorNameJp   ; KARBONALA_WARRIOR
	dw RogueDollNameJp          ; ROGUE_DOLL
	dw WattkidNameJp            ; WATTKID
	dw GrifforeNameJp           ; GRIFFORE
	dw TorikeNameJp             ; TORIKE
	dw SanganNameJp             ; SANGAN
	dw BigInsectNameJp          ; BIG_INSECT
	dw BasicInsectNameJp        ; BASIC_INSECT
	dw ArmoredLizardNameJp      ; ARMORED_LIZARD
	dw HerculesBeetleNameJp     ; HERCULES_BEETLE
	dw KillerNeedleNameJp       ; KILLER_NEEDLE
	dw GokiboreNameJp           ; GOKIBORE
	dw GiantFleaNameJp          ; GIANT_FLEA
	dw LarvaeMothNameJp         ; LARVAE_MOTH
	dw GreatMothNameJp          ; GREAT_MOTH
	dw KuribohNameJp            ; KURIBOH
	dw MammothGraveyardNameJp   ; MAMMOTH_GRAVEYARD
	dw GreatWhiteNameJp         ; GREAT_WHITE
	dw WolfNameJp               ; WOLF
	dw HarpieLadyNameJp         ; HARPIE_LADY
	dw HarpieLadySisterNameJp   ; HARPIE_LADY_SISTER
	dw TigerAxeNameJp           ; TIGER_AXE
	dw SilverFangNameJp         ; SILVER_FANG
	dw KojikocyNameJp           ; KOJIKOCY
	dw PerfectGreatMothNameJp   ; PERFECT_GREAT_MOTH
	dw GaroozisNameJp           ; GAROOZIS
	dw ThousandDragonNameJp     ; THOUSAND_DRAGON
	dw FiendKrakenNameJp        ; FIEND_KRAKEN
	dw JellyfishNameJp          ; JELLYFISH
	dw CocoonEvolutionNameJp    ; COCOON_EVOLUTION
	dw KairyuShinNameJp         ; KAIRYU_SHIN
	dw SoldierOfStoneNameJp     ; SOLDIER_OF_STONE
	dw ManEatingPlantNameJp     ; MAN_EATING_PLANT
	dw KrokodilusNameJp         ; KROKODILUS
	dw GrapplerNameJp           ; GRAPPLER
	dw AxeRaiderNameJp          ; AXE_RAIDER
	dw MegazowlerNameJp         ; MEGAZOWLER
	dw UrabyNameJp              ; URABY
	dw CrawlingDragon2NameJp    ; CRAWLING_DRAGON_2
	dw RedEyesBDragonNameJp     ; RED_EYES_B_DRAGON
	dw CastleOfDarkNameJp       ; CASTLE_OF_DARK
	dw ReaperOfTheCardNameJp    ; REAPER_OF_THE_CARD
	dw KingOfYamimakaiNameJp    ; KING_OF_YAMIMAKAI
	dw BaroxNameJp              ; BAROX
	dw DarkChimeraNameJp        ; DARK_CHIMERA
	dw MetalGuardianNameJp      ; METAL_GUARDIAN
	dw CatapultTurtleNameJp     ; CATAPULT_TURTLE
	dw GyakutennoMegamiNameJp   ; GYAKUTENNO_MEGAMI
	dw MysticHorsemanNameJp     ; MYSTIC_HORSEMAN
	dw RabidHorsemanNameJp      ; RABID_HORSEMAN
	dw ZankiNameJp              ; ZANKI
	dw CrawlingDragonNameJp     ; CRAWLING_DRAGON
	dw CrassClownNameJp         ; CRASS_CLOWN
	dw ArmoredZombieNameJp      ; ARMORED_ZOMBIE
	dw DragonZombieNameJp       ; DRAGON_ZOMBIE
	dw ClownZombieNameJp        ; CLOWN_ZOMBIE
	dw PumpkingTheKingNameJp    ; PUMPKING_THE_KING
	dw BattleWarriorNameJp      ; BATTLE_WARRIOR
	dw WingsOfFlameNameJp       ; WINGS_OF_FLAME
	dw MaskOfDarknessNameJp     ; MASK_OF_DARKNESS
	dw JobChangeMirrorNameJp    ; JOB_CHANGE_MIRROR
	dw CurtainOfDarkNameJp      ; CURTAIN_OF_DARK
	dw TomozaurusNameJp         ; TOMOZAURUS
	dw SpiritOfTheWindNameJp    ; SPIRIT_OF_THE_WIND
	dw KageningenNameJp         ; KAGENINGEN
	dw GraveyardAndHandNameJp   ; GRAVEYARD_AND_HAND
	dw GoddessThirdEyeNameJp    ; GODDESS_THIRD_EYE
	dw HeroOfTheEastNameJp      ; HERO_OF_THE_EAST
	dw DomaTheAngelNameJp       ; DOMA_THE_ANGEL
	dw ThatWhichFeedsNameJp     ; THAT_WHICH_FEEDS
	dw DarkGrayNameJp           ; DARK_GRAY
	dw WhiteMagicalHatNameJp    ; WHITE_MAGICAL_HAT
	dw KamionwizardNameJp       ; KAMIONWIZARD
	dw NightmareScorpionNameJp  ; NIGHTMARE_SCORPION
	dw SpiritOfTheBookNameJp    ; SPIRIT_OF_THE_BOOK
	dw SupporterShadowsNameJp   ; SUPPORTER_SHADOWS
	dw TrialOfNightmareNameJp   ; TRIAL_OF_NIGHTMARE
	dw DreamClownNameJp         ; DREAM_CLOWN
	dw SleepingLionNameJp       ; SLEEPING_LION
	dw YamatanoScrollNameJp     ; YAMATANO_SCROLL
	dw DarkPlantNameJp          ; DARK_PLANT
	dw AncientToolNameJp        ; ANCIENT_TOOL
	dw FaithBirdNameJp          ; FAITH_BIRD
	dw OrionTheBattleNameJp     ; ORION_THE_BATTLE
	dw AnsatsuNameJp            ; ANSATSU
	dw LamoonNameJp             ; LAMOON
	dw NemurikoNameJp           ; NEMURIKO
	dw WeatherControlNameJp     ; WEATHER_CONTROL
	dw OctoberserNameJp         ; OCTOBERSER
	dw The13thGraveNameJp       ; THE_13TH_GRAVE
	dw CharubinTheFireNameJp    ; CHARUBIN_THE_FIRE
	dw MysticalCaptureNameJp    ; MYSTICAL_CAPTURE
	dw FiendsHandNameJp         ; FIENDS_HAND
	dw WittyPhantomNameJp       ; WITTY_PHANTOM
	dw MysteryHandNameJp        ; MYSTERY_HAND
	dw DragonStatueNameJp       ; DRAGON_STATUE
	dw BEyedSilZombieNameJp     ; B_EYED_SIL_ZOMBIE
	dw ToadMasterNameJp         ; TOAD_MASTER
	dw SpikedSnailNameJp        ; SPIKED_SNAIL
	dw FlameManipulatorNameJp   ; FLAME_MANIPULATOR
	dw NecrolancerNameJp        ; NECROLANCER
	dw DjinnTheWatcherNameJp    ; DJINN_THE_WATCHER
	dw BewitchingPhantomNameJp  ; BEWITCHING_PHANTOM
	dw TempleOfSkullsNameJp     ; TEMPLE_OF_SKULLS
	dw MonsterEggNameJp         ; MONSTER_EGG
	dw ShadowWhoControlNameJp   ; SHADOW_WHO_CONTROL
	dw LordOfTheLampNameJp      ; LORD_OF_THE_LAMP
	dw AkihironNameJp           ; AKIHIRON
	dw RhaimundosRedNameJp      ; RHAIMUNDOS_RED
	dw MeltingRedShadowNameJp   ; MELTING_RED_SHADOW
	dw DokuroizoTheGrimNameJp   ; DOKUROIZO_THE_GRIM
	dw FireReaperNameJp         ; FIRE_REAPER
	dw LarvasNameJp             ; LARVAS
	dw HardArmorNameJp          ; HARD_ARMOR
	dw FiregrassNameJp          ; FIREGRASS
	dw ManEaterNameJp           ; MAN_EATER
	dw DigBeakNameJp            ; DIG_BEAK
	dw MWarrior1NameJp          ; M_WARRIOR_1
	dw MWarrior2NameJp          ; M_WARRIOR_2
	dw TaintedWisdomNameJp      ; TAINTED_WISDOM
	dw LisarkNameJp             ; LISARK
	dw LordOfZemiaNameJp        ; LORD_OF_ZEMIA
	dw TheJudgementHandNameJp   ; THE_JUDGEMENT_HAND
	dw MysteriousPuppetNameJp   ; MYSTERIOUS_PUPPET
	dw AncientJarNameJp         ; ANCIENT_JAR
	dw DarkfireDragonNameJp     ; DARKFIRE_DRAGON
	dw DarkKingAbyssNameJp      ; DARK_KING_ABYSS
	dw SpiritOfTheHarpNameJp    ; SPIRIT_OF_THE_HARP
	dw BigEyeNameJp             ; BIG_EYE
	dw ArmaillNameJp            ; ARMAILL
	dw DarkPrisonerNameJp       ; DARK_PRISONER
	dw HurricailNameJp          ; HURRICAIL
	dw AncientBrainNameJp       ; ANCIENT_BRAIN
	dw FireEyeNameJp            ; FIRE_EYE
	dw MonsturtleNameJp         ; MONSTURTLE
	dw ClawReacherNameJp        ; CLAW_REACHER
	dw PhantomDewanNameJp       ; PHANTOM_DEWAN
	dw ArlownayNameJp           ; ARLOWNAY
	dw DarkShadeNameJp          ; DARK_SHADE
	dw MaskedClownNameJp        ; MASKED_CLOWN
	dw LuckyTrinketNameJp       ; LUCKY_TRINKET
	dw GeninNameJp              ; GENIN
	dw EyearmorNameJp           ; EYEARMOR
	dw FiendReflection2NameJp   ; FIEND_REFLECTION2
	dw GateDeegNameJp           ; GATE_DEEG
	dw SyncharNameJp            ; SYNCHAR
	dw FusionistNameJp          ; FUSIONIST
	dw AkakieisuNameJp          ; AKAKIEISU
	dw LalaLiOonNameJp          ; LALA_LI_OON
	dw KeyMaceNameJp            ; KEY_MACE
	dw TurtleTigerNameJp        ; TURTLE_TIGER
	dw TerraTheTerribleNameJp   ; TERRA_THE_TERRIBLE
	dw DoronNameJp              ; DORON
	dw ArmaKnightNameJp         ; ARMA_KNIGHT
	dw MechMoleZombieNameJp     ; MECH_MOLE_ZOMBIE
	dw HappyLoverNameJp         ; HAPPY_LOVER
	dw PenguinKnightNameJp      ; PENGUIN_KNIGHT
	dw PetitDragonNameJp        ; PETIT_DRAGON
	dw FrenziedPandaNameJp      ; FRENZIED_PANDA
	dw ArchfiendMarmotNameJp    ; ARCHFIEND_MARMOT
	dw PhantomGhostNameJp       ; PHANTOM_GHOST
	dw MabarrelNameJp           ; MABARREL
	dw DoroverNameJp            ; DOROVER
	dw TwinLongRods1NameJp      ; TWIN_LONG_RODS_1
	dw DrollBirdNameJp          ; DROLL_BIRD
	dw PetitAngelNameJp         ; PETIT_ANGEL
	dw WingedCleaverNameJp      ; WINGED_CLEAVER
	dw HinotamaSoulNameJp       ; HINOTAMA_SOUL
	dw ThunderKidNameJp         ; THUNDER_KID
	dw MeotokoNameJp            ; MEOTOKO
	dw AquaMadoorNameJp         ; AQUA_MADOOR
	dw KagemushaBlueNameJp      ; KAGEMUSHA_BLUE
	dw FlameGhostNameJp         ; FLAME_GHOST
	dw DryadNameJp              ; DRYAD
	dw BSkullDragonNameJp       ; B_SKULL_DRAGON
	dw TwoMouthDarkrulerNameJp  ; TWO_MOUTH_DARKRULER
	dw SolitudeNameJp           ; SOLITUDE
	dw MaskedSorcererNameJp     ; MASKED_SORCERER
	dw KumootokoNameJp          ; KUMOOTOKO
	dw MidnightFiendNameJp      ; MIDNIGHT_FIEND
	dw RoarOceanSnakeNameJp     ; ROAR_OCEAN_SNAKE
	dw TrapMasterNameJp         ; TRAP_MASTER
	dw FiendSwordNameJp         ; FIEND_SWORD
	dw SkullStalkerNameJp       ; SKULL_STALKER
	dw HitodenchakNameJp        ; HITODENCHAK
	dw WoodRemainsNameJp        ; WOOD_REMAINS
	dw HourglassOfLifeNameJp    ; HOURGLASS_OF_LIFE
	dw RareFishNameJp           ; RARE_FISH
	dw WoodClownNameJp          ; WOOD_CLOWN
	dw MadjinnGunnNameJp        ; MADJINN_GUNN
	dw DarkTitanTerrorNameJp    ; DARK_TITAN_TERROR
	dw BeautifulHeadhuntNameJp  ; BEAUTIFUL_HEADHUNT
	dw WodanTheResidentNameJp   ; WODAN_THE_RESIDENT
	dw GuardianLabyrinthNameJp  ; GUARDIAN_LABYRINTH
	dw HaniwaNameJp             ; HANIWA
	dw YashinokiNameJp          ; YASHINOKI
	dw VishwarRandiNameJp       ; VISHWAR_RANDI
	dw TheDrdekNameJp           ; THE_DRDEK
	dw DAssailantNameJp         ; D_ASSAILANT
	dw CandleOfFateNameJp       ; CANDLE_OF_FATE
	dw WaterElementNameJp       ; WATER_ELEMENT
	dw DissolverockNameJp       ; DISSOLVEROCK
	dw MedaBatNameJp            ; MEDA_BAT
	dw OneWhoHuntsSoulNameJp    ; ONE_WHO_HUNTS_SOUL
	dw RootWaterNameJp          ; ROOT_WATER
	dw MasterAndExpertNameJp    ; MASTER_AND_EXPERT
	dw WaterOmoticsNameJp       ; WATER_OMOTICS
	dw HyoNameJp                ; HYO
	dw EnchantingMermaidNameJp  ; ENCHANTING_MERMAID
	dw Nekogal1NameJp           ; NEKOGAL_1
	dw AngelwitchNameJp         ; ANGELWITCH
	dw EmbryonicBeastNameJp     ; EMBRYONIC_BEAST
	dw PreventRatNameJp         ; PREVENT_RAT
	dw DdWarriorNameJp          ; DD_WARRIOR
	dw StoneArmadillerNameJp    ; STONE_ARMADILLER
	dw BeastkingOfSwampNameJp   ; BEASTKING_OF_SWAMP
	dw AncientSorcererNameJp    ; ANCIENT_SORCERER
	dw LunarQueenElzaimNameJp   ; LUNAR_QUEEN_ELZAIM
	dw ArchfiendMirrorNameJp    ; ARCHFIEND_MIRROR
	dw SwordsmanOfAileNameJp    ; SWORDSMAN_OF_AILE
	dw RockOgreGrotto2NameJp    ; ROCK_OGRE_GROTTO2
	dw WingEggElfNameJp         ; WING_EGG_ELF
	dw FuriousSeaKingNameJp     ; FURIOUS_SEA_KING
	dw PrincessTsurugiNameJp    ; PRINCESS_TSURUGI
	dw UnknownWarriorNameJp     ; UNKNOWN_WARRIOR
	dw SectarianSecretNameJp    ; SECTARIAN_SECRET
	dw VersagoDestroyerNameJp   ; VERSAGO_DESTROYER
	dw WethaNameJp              ; WETHA
	dw MegirusLightNameJp       ; MEGIRUS_LIGHT
	dw MavelusNameJp            ; MAVELUS
	dw AncientTreeNameJp        ; ANCIENT_TREE
	dw GreenPhantomKingNameJp   ; GREEN_PHANTOM_KING
	dw GroundAttackerNameJp     ; GROUND_ATTACKER
	dw RayAndTemperatureNameJp  ; RAY_AND_TEMPERATURE
	dw GorgonEggNameJp          ; GORGON_EGG
	dw PetitMothNameJp          ; PETIT_MOTH
	dw KingFogNameJp            ; KING_FOG
	dw ProtectorThroneNameJp    ; PROTECTOR_THRONE
	dw MysticClownNameJp        ; MYSTIC_CLOWN
	dw MysticalSheep2NameJp     ; MYSTICAL_SHEEP_2
	dw HolograhNameJp           ; HOLOGRAH
	dw TaoTheChanterNameJp      ; TAO_THE_CHANTER
	dw SerpentMarauderNameJp    ; SERPENT_MARAUDER
	dw GatekeeperNameJp         ; GATEKEEPER
	dw OgreOfTheBlackNameJp     ; OGRE_OF_THE_BLACK
	dw DarkArtistNameJp         ; DARK_ARTIST
	dw ChangeSlimeNameJp        ; CHANGE_SLIME
	dw MoonEnvoyNameJp          ; MOON_ENVOY
	dw FireyarouNameJp          ; FIREYAROU
	dw PsychicKappaNameJp       ; PSYCHIC_KAPPA
	dw MasakiTheLegendNameJp    ; MASAKI_THE_LEGEND
	dw DragonessWickedNameJp    ; DRAGONESS_WICKED
	dw BioPlantNameJp           ; BIO_PLANT
	dw OneEyedShieldNameJp      ; ONE_EYED_SHIELD
	dw CyberSoldierDarkNameJp   ; CYBER_SOLDIER_DARK
	dw DragonErsatzHeadNameJp   ; DRAGON_ERSATZ_HEAD
	dw SonicMaidNameJp          ; SONIC_MAID
	dw KuramaNameJp             ; KURAMA
	dw LegendarySwordNameJp     ; LEGENDARY_SWORD
	dw SwordOfDarkNameJp        ; SWORD_OF_DARK
	dw DarkEnergyNameJp         ; DARK_ENERGY
	dw AxeOfDespairNameJp       ; AXE_OF_DESPAIR
	dw LazerCannonArmorNameJp   ; LAZER_CANNON_ARMOR
	dw InsectArmorLaserNameJp   ; INSECT_ARMOR_LASER
	dw ElfsLightNameJp          ; ELFS_LIGHT
	dw BeastFangsNameJp         ; BEAST_FANGS
	dw SteelShellNameJp         ; STEEL_SHELL
	dw VileGermsNameJp          ; VILE_GERMS
	dw BlackPendantNameJp       ; BLACK_PENDANT
	dw SilverBowAndArrowNameJp  ; SILVER_BOW_AND_ARROW
	dw HornOfLightNameJp        ; HORN_OF_LIGHT
	dw HornOfUnicornNameJp      ; HORN_OF_UNICORN
	dw DragonTreasureNameJp     ; DRAGON_TREASURE
	dw ElectroWhipNameJp        ; ELECTRO_WHIP
	dw CyberShieldNameJp        ; CYBER_SHIELD
	dw ElegantEgotistNameJp     ; ELEGANT_EGOTIST
	dw MysticalMoonNameJp       ; MYSTICAL_MOON
	dw StopDefenseNameJp        ; STOP_DEFENSE
	dw MalevolentNuzzlerNameJp  ; MALEVOLENT_NUZZLER
	dw VioletCrystalNameJp      ; VIOLET_CRYSTAL
	dw BookOfSecretArtNameJp    ; BOOK_OF_SECRET_ART
	dw InvigorationNameJp       ; INVIGORATION
	dw MachineConversionNameJp  ; MACHINE_CONVERSION
	dw RaiseBodyHeatNameJp      ; RAISE_BODY_HEAT
	dw FollowWindNameJp         ; FOLLOW_WIND
	dw PowerOfKaishinNameJp     ; POWER_OF_KAISHIN
	dw DragonCaptureJarNameJp   ; DRAGON_CAPTURE_JAR
	dw ForestNameJp             ; FOREST
	dw WastelandNameJp          ; WASTELAND
	dw MountainNameJp           ; MOUNTAIN
	dw SogenNameJp              ; SOGEN
	dw UmiNameJp                ; UMI
	dw YamiNameJp               ; YAMI
	dw DarkHoleNameJp           ; DARK_HOLE
	dw RaigekiNameJp            ; RAIGEKI
	dw MooyanCurryNameJp        ; MOOYAN_CURRY
	dw RedMedicineNameJp        ; RED_MEDICINE
	dw GoblinsRemedyNameJp      ; GOBLINS_REMEDY
	dw SoulOfThePureNameJp      ; SOUL_OF_THE_PURE
	dw DianKetoTheCureNameJp    ; DIAN_KETO_THE_CURE
	dw SparksNameJp             ; SPARKS
	dw HinotamaNameJp           ; HINOTAMA
	dw FinalFlameNameJp         ; FINAL_FLAME
	dw OokaziNameJp             ; OOKAZI
	dw TremendousFireNameJp     ; TREMENDOUS_FIRE
	dw SwordsRevealingNameJp    ; SWORDS_REVEALING
	dw SpellbindCircleNameJp    ; SPELLBIND_CIRCLE
	dw DarkPierceLightNameJp    ; DARK_PIERCE_LIGHT
	dw YaranzoNameJp            ; YARANZO
	dw KananTheSwordNameJp      ; KANAN_THE_SWORD
	dw TakriminosNameJp         ; TAKRIMINOS
	dw StuffedAnimalNameJp      ; STUFFED_ANIMAL
	dw MegasonicEyeNameJp       ; MEGASONIC_EYE
	dw SuperWarLionNameJp       ; SUPER_WAR_LION
	dw YamadronNameJp           ; YAMADRON
	dw SeiyaryuNameJp           ; SEIYARYU
	dw ThreeLeggedZombiesNameJp ; THREE_LEGGED_ZOMBIES
	dw ZeraTheMantNameJp        ; ZERA_THE_MANT
	dw FlyingPenguinNameJp      ; FLYING_PENGUIN
	dw MillenniumShieldNameJp   ; MILLENNIUM_SHIELD
	dw FairysGiftNameJp         ; FAIRYS_GIFT
	dw BLusterSoldierNameJp     ; B_LUSTER_SOLDIER
	dw FiendsMirrorNameJp       ; FIENDS_MIRROR
	dw InvalidCardNameJp        ; INVALID_CARD
	dw InvalidCardNameJp + (InvalidCardNameJp.end - InvalidCardNameJp)
	assert_table_length NUM_CARDS + 2
