PUSHC credits
Credits:
	text "    ゛        ゛゛     "
	text "  オりシナルキャラクタ-テサイン   "
	text "    ゛       ゛゛      "
	text "  オりシナルモンスタ-テサイン    "
	text "            ゛       "
	text "      たかはし かすき      "
	text "                    "
	text "                    "
	text "  ゛  ゛゛   ゛         "
	text "  ケ-ムテサイン·ティレクション   "
	text "        ゛  ゛        "
	text "      やまた のふひろ      "
	text "                    "
	text "                    "
	text "  ゜ ゛               "
	text "  フロクラム             "
	text "        ゛  ゛        "
	text "      やまた のふひろ      "
	text "       ゛            "
	text "      ちた たくり        "
	text "                    "
	text "                    "
	text "  ゛     ゛           "
	text "  クラフィックティレクション     "
	text "                    "
	text "      はしもと かなこ      "
	text "                    "
	text "                    "
	text "     ゛              "
	text "  サウント              "
	text "                    "
	text "      かみお けんいち      "
	text "                    "
	text "                    "
	text "       ゛゛           "
	text "  モンスタ-テサイン         "
	text "                    "
	text "      ···           "
	text "          ゛         "
	text "      いぅすんほうし       "
	text "                    "
	text "      いつもり なゆ       "
	text "       ゛            "
	text "      エウァ14         "
	text "                    "
	text "      エス·エ-         "
	text "                    "
	text "      エフ            "
	text "         ゛゛ ゛       "
	text "      くされけとうしん      "
	text "                    "
	text "      サイコ-くん        "
	text "                    "
	text "      シエル           "
	text "      ゜             "
	text "      ヒ-マン          "
	text "      ゜゛            "
	text "      ヒクモン          "
	text "       ゛            "
	text "      ひしり りゅうか      "
	text "         ゛          "
	text "      ふりんし          "
	text "      ゜ ゜           "
	text "      ホンホコタヌキ       "
	text "        ゛           "
	text "      みかけやま こてん     "
	text "                    "
	text "      ムラカミ          "
	text "        ゛゛          "
	text "      ゆうきシュニア       "
	text "                    "
	text "      あおい たかひろ      "
	text "                    "
	text "      あおき たかゆき      "
	text "        ゛           "
	text "      あかほし みさき      "
	text "                    "
	text "      あさの ゆうすけ      "
	text "       ゛            "
	text "      あたち としろう      "
	text "       ゛            "
	text "      あへ ひろゆき       "
	text "        ゛           "
	text "      あんさい あきら      "
	text "        ゛           "
	text "      あんさい しん       "
	text "        ゛     ゛     "
	text "      いけかみ きょうし     "
	text "        ゛           "
	text "      いけた よういち      "
	text "                    "
	text "      いしい あつし       "
	text "        ゛           "
	text "      いしさか けいた      "
	text "       ゛            "
	text "      いすた まさたか      "
	text "                    "
	text "      いちかわ ひろゆき     "
	text "                    "
	text "      いとう ゆういち      "
	text "        ゛           "
	text "      いなかき りょう      "
	text "             ゛      "
	text "      いまむら こうし      "
	text "                    "
	text "      いわこし たけし      "
	text "             ゛      "
	text "      いわさか まなふ      "
	text "                    "
	text "      いわさき れいな      "
	text "        ゛           "
	text "      うえた けんたろう     "
	text "        ゛           "
	text "      うえた ひろし       "
	text "       ゛            "
	text "      えとたに みほ       "
	text "                    "
	text "      おおいし ほたけ      "
	text "                    "
	text "      おおしろ みわこ      "
	text "                    "
	text "      おおや ともみ       "
	text "             ゛      "
	text "      おかむら せいしゅ     "
	text "            ゛       "
	text "      おくむら かすや      "
	text "       ゛   ゛ ゛      "
	text "      おさき ひてかす      "
	text "              ゛     "
	text "      おちあい ひろのふ     "
	text "        ゛           "
	text "      おのてら まさし      "
	text "                    "
	text "      かたおか てつや      "
	text "        ゛   ゛       "
	text "      かたきり はしめ      "
	text "                    "
	text "      かとう しゅんすけ     "
	text "            ゛       "
	text "      かとう ゆうし       "
	text "       ゛  ゛         "
	text "      かとた かくし       "
	text "             ゛      "
	text "      かないわ こうし      "
	text "           ゛        "
	text "      かねこ ひてき       "
	text "                    "
	text "      かみこうす ひろたけ    "
	text "                    "
	text "      かみこうす りょうすけ   "
	text "                    "
	text "      かわさき こうへい     "
	text "                    "
	text "      かわはら ともひさ     "
	text "                    "
	text "      きたい まさき       "
	text "       ゛            "
	text "      きと しゅうへい      "
	text "           ゛        "
	text "      きむら しけひろ      "
	text "           ゛        "
	text "      くさみち こうき      "
	text "        ゛           "
	text "      くにかた          "
	text "       ゛ ゛          "
	text "      くほ しゅんこ       "
	text "       ゛            "
	text "      くほた まり        "
	text "        ゛           "
	text "      くまかや もりたか     "
	text "                    "
	text "      くらの まさと       "
	text "            ゛       "
	text "      くらもと かすや      "
	text "                    "
	text "      くわはら おさむ      "
	text "        ゛           "
	text "      こうかく なお       "
	text "        ゛           "
	text "      こうたき まもる      "
	text "       ゛            "
	text "      こしま しん        "
	text "       ゛            "
	text "      こしま よしのり      "
	text "                    "
	text "      こたけ まこと       "
	text "                    "
	text "      こにし たかゆき      "
	text "        ゛           "
	text "      こまは しんすけ      "
	text "                    "
	text "      こみなみ たかなお     "
	text "        ゛           "
	text "      こんとう みゆき      "
	text "                    "
	text "      さいき ゆうき       "
	text "           ゛        "
	text "      さいとう しゅん      "
	text "                    "
	text "      さいとう ちえみ      "
	text "                    "
	text "      さいとう つかさ      "
	text "                    "
	text "      さいとう てつなり     "
	text "           ゛        "
	text "      ささき かすみ       "
	text "                    "
	text "      ささき かつひと      "
	text "                    "
	text "      さそう ともひこ      "
	text "                    "
	text "      さとう かおり       "
	text "                    "
	text "      さとう けいすけ      "
	text "          ゛         "
	text "      さとう こう        "
	text "             ゛      "
	text "      さとう ひろかす      "
	text "                    "
	text "      さるわたり たくみ     "
	text "                    "
	text "      しいな かつゆき      "
	text "        ゛           "
	text "      しおさき りょうた     "
	text "       ゛            "
	text "      しけひさ としあき     "
	text "       ゛            "
	text "      しけまつ さとひろ     "
	text "                    "
	text "      しも りょうすけ      "
	text "        ゛           "
	text "      しもた たけし       "
	text "         ゛   ゛      "
	text "      しんなへ けんし      "
	text "       ゛            "
	text "      すかい あつし       "
	text "       ゛            "
	text "      すき なおと        "
	text "       ゛            "
	text "      すきた おおか       "
	text "       ゛   ゛        "
	text "      すすき かすほ       "
	text "       ゛   ゛        "
	text "      すすき かすや       "
	text "       ゛   ゛        "
	text "      すすき かすゆき      "
	text "                    "
	text "      せきね あきら       "
	text "                    "
	text "      そうま ひとし       "
	text "         ゛  ゛       "
	text "      そとかと かすき      "
	text "           ゛        "
	text "      たかはし しゅん      "
	text "                    "
	text "      たかはし ふみひと     "
	text "                    "
	text "      たかはま なりとも     "
	text "                    "
	text "      たしろ ゆうこ       "
	text "       ゛            "
	text "      たたの こたろう      "
	text "             ゛      "
	text "      たてやま けんし      "
	text "                    "
	text "      たなか けんしろう     "
	text "        ゛   ゛       "
	text "      たなへ ゆうし       "
	text "                    "
	text "      たむら ゆういちろう    "
	text "                    "
	text "      たるした けんた      "
	text "        ゛           "
	text "      つかた こうへい      "
	text "                    "
	text "      つちや あきひろ      "
	text "                    "
	text "      つつみ ともこ       "
	text "                    "
	text "      つるみ ともひろ      "
	text "       ゛            "
	text "      とた まさやす       "
	text "       ゛            "
	text "      とは たけし        "
	text "                    "
	text "      とみた けいすけ      "
	text "           ゛        "
	text "      とみやま たいち      "
	text "                    "
	text "      とやま ともたか      "
	text "                    "
	text "      なかお あつし       "
	text "                    "
	text "      なかお ゆうた       "
	text "       ゛            "
	text "      なかお りゅうた      "
	text "        ゛           "
	text "      なかしま たくみ      "
	text "       ゛            "
	text "      なかた まさき       "
	text "                    "
	text "      なかつる まゆ       "
	text "                    "
	text "      なかにし よういち     "
	text "                    "
	text "      なかもと あきこ      "
	text "                    "
	text "      なかや しゅか       "
	text "       ゛            "
	text "      なかや ひろし       "
	text "                    "
	text "      にしさと みき       "
	text "                    "
	text "      にしむら あきこ      "
	text "                    "
	text "      にしむら たくろう     "
	text "                    "
	text "      にぅた まりこ       "
	text "                    "
	text "      にのみや しゅんいちろう  "
	text "       ゛            "
	text "      のくち るり        "
	text "              ゛     "
	text "      ののむら まさかす     "
	text "                    "
	text "      はたの ひろのり      "
	text "                    "
	text "      はまの たくや       "
	text "                    "
	text "      はやし きいち       "
	text "             ゛      "
	text "      はやたけ ゆうし      "
	text "        ゛  ゛        "
	text "      はらた ひてあき      "
	text "           ゛        "
	text "      ひさかわ しゅん      "
	text "       ゛            "
	text "      ひた ゆうや        "
	text "                    "
	text "      ひら としあき       "
	text "                    "
	text "      ひろの まさき       "
	text "         ゛          "
	text "      ふくなか やよい      "
	text "       ゛            "
	text "      ふしい たけし       "
	text "       ゛            "
	text "      ふした けんいち      "
	text "       ゛            "
	text "      ふした ちえ        "
	text "       ゛            "
	text "      ふした まさとし      "
	text "       ゛            "
	text "      ふした みつまさ      "
	text "       ゛            "
	text "      ふしはら かつひと     "
	text "       ゛     ゛      "
	text "      ふしよし えいし      "
	text "             ゛      "
	text "      ふたみ としかす      "
	text "                    "
	text "      ふるかわ あさみ      "
	text "                    "
	text "      ふるかわ さとし      "
	text "        ゛           "
	text "      ふるたか ゆうき      "
	text "                    "
	text "      ほかり しょうたろう    "
	text "                    "
	text "      ほそめ けいすけ      "
	text "        ゛  ゛        "
	text "      ほんさわ こう       "
	text "            ゛       "
	text "      まえしま ひてふみ     "
	text "        ゛           "
	text "      まえた かよ        "
	text "        ゛           "
	text "      ますた けんた       "
	text "                    "
	text "      まつうら なお       "
	text "        ゛           "
	text "      まつさわ けいすけ     "
	text "        ゛           "
	text "      まつた あゆみ       "
	text "         ゛          "
	text "      みつなか まさひろ     "
	text "                    "
	text "      みやさと かいり      "
	text "                    "
	text "      むかい さおり       "
	text "             ゛      "
	text "      むらい きょうし      "
	text "                    "
	text "      むらの まさゆき      "
	text "        ゛           "
	text "      もちつき ゆうま      "
	text "                    "
	text "      もとやま せいいち     "
	text "                    "
	text "      もりた しゅんいち     "
	text "            ゛       "
	text "      もんま せいし       "
	text "        ゛           "
	text "      やまさき しょうた     "
	text "        ゛           "
	text "      やまさき ひろし      "
	text "        ゛           "
	text "      やまた けいすけ      "
	text "        ゛           "
	text "      やまた たいし       "
	text "        ゛           "
	text "      やまた ゆきひさ      "
	text "                    "
	text "      やまもと いくお      "
	text "             ゛      "
	text "      やまもと けんし      "
	text "                    "
	text "      やまもと ひろき      "
	text "                    "
	text "      やまもと まさひろ     "
	text "       ゛ ゛          "
	text "      ゆひやと やすし      "
	text "        ゛           "
	text "      よしさき ゆきお      "
	text "        ゛           "
	text "      よしさわ みゆき      "
	text "        ゛  ゛        "
	text "      よした かすや       "
	text "        ゛           "
	text "      よした たくみ       "
	text "        ゛           "
	text "      よした よしひろ      "
	text "       ゛            "
	text "      よた たろう        "
	text "         ゛          "
	text "      わたなへ たかゆき     "
	text "                    "
	text "                    "
	text "                    "
	text "  モンスタ-ノ-ツ          "
	text "                    "
	text "      シモムラ ケイタ      "
	text "                    "
	text "                    "
	text "   ゜                "
	text "  スへシャルサンクス         "
	text "            ゛       "
	text "      とりしま かすひこ     "
	text "                    "
	text "      たかはし としまさ     "
	text "                    "
	text "      へいし よしひさ      "
	text "        ゛           "
	text "      たけた ふゆと       "
	text "                    "
	text "      しま ともゆき       "
	text "                    "
	text "                    "
	text "            ゛       "
	text "      よしくら ひてお      "
	text "        ゛           "
	text "      こんとう ゆう       "
	text "        ゛           "
	text "      まちた むねはる      "
	text "           ゛  ゛     "
	text "      やまもと しゅんし     "
	text "                    "
	text "                    "
	text "               ゛    "
	text "      ライトりンクミュ-シック  "
	text "                    "
	text "      アイ·ティ-·エル     "
	text "                    "
	text "                    "
	text "                    "
	text "      ところ みちこ       "
	text "                    "
	text "      ふくい ひろゆき      "
	text "         ゛          "
	text "      わたなへ つとむ      "
	text "           ゛        "
	text "      ひらた ひてひろ      "
	text "                    "
	text "                    "
	text "                    "
	text "      なかやま かつひろ     "
	text "                    "
	text "      さかい まさと       "
	text "       ゛            "
	text "      やき よしこ        "
	text "        ゛           "
	text "      せきくち ようこ      "
	text "                    "
	text "                    "
	text "  ゜ ゛               "
	text "  フロテュ-サ-           "
	text "                    "
	text "      しもむら さとし      "
	text "                    "
	text "                    "
	text "   ゛゛   ゛゜ ゛        "
	text "  エクセクティフフロテュ-サ-    "
	text "            ゛       "
	text "      きたうえ かすみ      "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "        おわり         "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	text "                    "
	db $ff ; end
POPC
