INCLUDE "constants/hardware.inc"

INCLUDE "macros/const.asm"
INCLUDE "constants/charmap.asm"

INCLUDE "constants/card_constants.asm"
INCLUDE "constants/character_constants.asm"
INCLUDE "constants/duel_constants.asm"
INCLUDE "constants/effect_constants.asm"
INCLUDE "constants/gfx_constants.asm"
INCLUDE "constants/job_constants.asm"
INCLUDE "constants/menu_constants.asm"
INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/sgb_constants.asm"
INCLUDE "constants/text_constants.asm"

INCLUDE "macros/code.asm"
INCLUDE "macros/coords.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/ram.asm"
INCLUDE "macros/sgb.asm"
INCLUDE "macros/text.asm"
